### ISSUE TITLE
1.2開発版を新規インストールをした場合にenju_leaf:setupでエラーになる

### ISSUE THREAD

**Issue by nakamura-akifumi** [next-l/enju_leaf#1127]
- [x] markdown のマニュアル修正ない #1191

https://github.com/next-l/enju_leaf/wiki/Install
を参考にインストールを実施すると enju_leaf:setup で以下のエラーが発生する。

```
NakamuraAkifumi-no-MacBook-Air:enju_1_2_dev nakamura$  rails g enju_leaf:setup
[Simple Form] Simple Form is not configured in the application and will use the default values. Use `rails generate simple_form:install` to generate the Simple Form configuration.
      create  db/fixtures/enju_leaf
      create  db/fixtures/enju_leaf/roles.yml
      create  db/fixtures/enju_leaf/user_groups.yml
      create  example/solr
      create  example/solr/conf/schema.xml
      create  example/solr/conf/solrconfig.xml
      create  Procfile
      create  config/schedule.rb
      create  config/initializers/enju_leaf.rb
      create  config/initializers/resque.rb
      append  config/initializers/assets.rb
      insert  config/application.rb
        gsub  config/application.rb
        gsub  config/application.rb
        gsub  config/schedule.rb
      append  Rakefile
      append  Rakefile
      append  db/seeds.rb
    generate  devise:install
/Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.5/lib/active_record/dynamic_matchers.rb:26:in `method_missing': private method `include' called for Item (call 'Item.connection' to establish a connection):Class (NoMethodError)
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/config/initializers/enju_leaf.rb:1:in `<top (required)>'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `block in load'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/engine.rb:652:in `block in load_config_initializer'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.5/lib/active_support/notifications.rb:166:in `instrument'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/engine.rb:651:in `load_config_initializer'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/engine.rb:615:in `each'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/engine.rb:615:in `block in <class:Engine>'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `instance_exec'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `run'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tsort.rb:150:in `block in tsort_each'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tsort.rb:183:in `block (2 levels) in each_strongly_connected_component'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tsort.rb:210:in `block (2 levels) in each_strongly_connected_component_from'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tsort.rb:219:in `each_strongly_connected_component_from'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tsort.rb:209:in `block in each_strongly_connected_component_from'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/initializable.rb:44:in `each'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/initializable.rb:44:in `tsort_each_child'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tsort.rb:203:in `each_strongly_connected_component_from'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tsort.rb:182:in `block in each_strongly_connected_component'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tsort.rb:180:in `each'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tsort.rb:180:in `each_strongly_connected_component'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tsort.rb:148:in `tsort_each'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/initializable.rb:54:in `run_initializers'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/application.rb:352:in `initialize!'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/config/environment.rb:5:in `<top (required)>'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/application.rb:328:in `require_environment!'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:142:in `require_application_and_environment!'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:128:in `generate_or_destroy'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:50:in `generate'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/commands.rb:17:in `<top (required)>'
    from bin/rails:4:in `require'
    from bin/rails:4:in `<main>'
    generate  devise
/Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.5/lib/active_record/dynamic_matchers.rb:26:in `method_missing': private method `include' called for Item (call 'Item.connection' to establish a connection):Class (NoMethodError)
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/config/initializers/enju_leaf.rb:1:in `<top (required)>'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `block in load'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/engine.rb:652:in `block in load_config_initializer'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.5/lib/active_support/notifications.rb:166:in `instrument'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/engine.rb:651:in `load_config_initializer'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/engine.rb:615:in `each'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/engine.rb:615:in `block in <class:Engine>'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `instance_exec'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `run'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tsort.rb:150:in `block in tsort_each'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tsort.rb:183:in `block (2 levels) in each_strongly_connected_component'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tsort.rb:210:in `block (2 levels) in each_strongly_connected_component_from'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tsort.rb:219:in `each_strongly_connected_component_from'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tsort.rb:209:in `block in each_strongly_connected_component_from'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/initializable.rb:44:in `each'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/initializable.rb:44:in `tsort_each_child'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tsort.rb:203:in `each_strongly_connected_component_from'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tsort.rb:182:in `block in each_strongly_connected_component'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tsort.rb:180:in `each'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tsort.rb:180:in `each_strongly_connected_component'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tsort.rb:148:in `tsort_each'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/initializable.rb:54:in `run_initializers'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/application.rb:352:in `initialize!'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/config/environment.rb:5:in `<top (required)>'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/application.rb:328:in `require_environment!'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:142:in `require_application_and_environment!'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:128:in `generate_or_destroy'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:50:in `generate'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/commands.rb:17:in `<top (required)>'
    from bin/rails:4:in `require'
    from bin/rails:4:in `<main>'
        gsub  app/models/user.rb
/Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:231:in `binread': No such file or directory - /Users/nakamura/src/enju-tanabe/enju_1_2_dev/app/models/user.rb (Errno::ENOENT)
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:231:in `gsub_file'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/bundler/gems/enju_leaf-82ede8df5742/lib/generators/enju_leaf/setup/setup_generator.rb:39:in `copy_setup_files'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/generators.rb:157:in `invoke'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/commands/generate.rb:13:in `<top (required)>'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:130:in `generate_or_destroy'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:50:in `generate'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
    from /Users/nakamura/src/enju-tanabe/enju_1_2_dev/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/commands.rb:17:in `<top (required)>'
    from bin/rails:4:in `require'
    from bin/rails:4:in `<main>'
```

**Comment by yegusa** [comment]
手元の仮想マシン（enju_leaf_vm_default_1447225364001_72894）では再現しませんでした。mac特有の問題ですかねえ。

**Comment by nabeta** [comment]
OSX 10.11.3とRuby 2.0.0の環境で再現しました。Ruby 2.1以降で実行するとどうなりますか？

**Comment by nakamura-akifumi** [comment]
OS X 10.11.3 
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
の環境で発生しています。

**Comment by nabeta** [comment]
rbenvで2.2.3をインストールしましたが、再現しません。
@nakamura-akifumi さんの環境ではgemは vendor/bundle/ruby/2.0.0 にインストールされているようですが、私の環境では vendor/bundle/ruby/2.2.0 にインストールされています。

**Comment by nabeta** [comment]
なお、enju_leaf-1.2系はRuby 2.1以上でしかテストしていません。

**Comment by nabeta** [comment]
1.2.0.beta.3とGitHubの1.2ブランチでセットアップを試してみていただけますか。

1.2.0.beta.3:

```sh
$ rails new enju_leaf_12 -m https://gist.github.com/nabeta/8024918f41242a16719796c962ed2af1.txt
```

GitHubの1.2ブランチ:

```sh
$ rails new enju_leaf_12 -m https://gist.github.com/nabeta/6319160.txt 
```

**Comment by yegusa** [comment]
これの確認、 @nakamura-akifumi にお願いしたいです。

ま、私の環境でやってみてできたらクローズでもいいかな？

**Comment by masao** [comment]
本件、再現できていないようなので、ひとまずいったんクローズします。また再現したら、Reopenするか、新規であげていただけると助かります。
