### ISSUE TITLE
enju_subject:setupでエラー

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1133]
1.2系の新規インストールしようとするとenju_subject:setupのところでエラーになります。
```
    generate  enju_subject:setup
[WARNING] Could not load generator "generators/enju_subject/setup/setup_generator". Error: /home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/enju_subject-b7979958eb84/lib/generators/enju_subject/setup/setup_generator.rb:14: syntax error, unexpected end-of-input, expecting keyword_end.
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:244:in `rescue in load_dependency'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:237:in `load_dependency'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.5/lib/rails/generators.rb:332:in `block (2 levels) in lookup'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.5/lib/rails/generators.rb:328:in `each'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.5/lib/rails/generators.rb:328:in `block in lookup'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.5/lib/rails/generators.rb:327:in `each'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.5/lib/rails/generators.rb:327:in `lookup'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.5/lib/rails/generators.rb:138:in `find_by_namespace'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.5/lib/rails/generators.rb:155:in `invoke'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.5/lib/rails/commands/generate.rb:13:in `<top (required)>'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:130:in `generate_or_destroy'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:50:in `generate'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.5/lib/rails/commands.rb:17:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Could not find generator 'enju_subject:setup'. Maybe you meant 'enju_event:setup'と'enju_biblio:setup' or 'enju_leaf:setup'
Run `rails generate --help` for more options.
```

**Comment by masao** [comment]
単なるsyntax errorだったようなので、一応、修正しておきました。

**Comment by yegusa** [comment]
さすがに、syntax error はテストでチェックできるうようにしておく必要があるのでは。。。

**Comment by yegusa** [comment]
テスト作成については #1136 でやりましょう。

残作業：　エラーが起きずに新規インストールできるようになるか確認する

**Comment by yegusa** [comment]
確認しましたので、クローズします。

確認方法：
手元の仮想マシンで、
 $ sudo stop enju_leaf 

としてもともと動いていたEnjuをストップしたうえで、

https://github.com/next-l/enju_leaf/wiki/Install

の手順通りにやって、1.2系をインストールし、Enjuが起動し、Enjuが動くことを確認しました
（NDLインポートができることを確認しました）

![image](https://cloud.githubusercontent.com/assets/1328499/12694440/3f5eaeac-c771-11e5-8443-58b21308e8a5.png)
