### ISSUE TITLE
モジュール追加方法の修正: enju_purchase_request

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1171]
- [x] マニュアル修正 #1191

app/models/user.rb および app/controllers/application_controller.rb への設定方法が変更になっているのでマニュアルを修正する必要がある。

**Comment by yegusa** [comment]
確かめる方法：
5-4 [enju_purchase_request]モジュール（発注リスト作成機能）
https://next-l.github.io/manual/1.2/enju_install_vm_5.html#section5-4

この通りにやってで、当該モジュールが追加できるかどうか確かめる。

**Comment by yegusa** [comment]
vagrant@vagrant-ubuntu-trusty-64:~/enju$ gem search -r enju_purchase_request --pre

*** REMOTE GEMS ***

enju_purchase_request (0.1.0.pre15, 0.1.0.pre14, 0.1.0.pre13, 0.1.0.pre12, 0.1.0.pre11, 0.1.0.pre10, 0.1.0.pre9, 0.1.0.pre8, 0.1.0.pre7, 0.1.0.pre6, 0.1.0.pre5, 0.1.0.pre4, 0.1.0.pre3, 0.1.0.pre2, 0.1.0.pre)

ってなってるので、

> gem "enju_purchase_request", '~> 0.2.0.beta.1'

ができません。

**Comment by nabeta** [comment]
リリース作業を行うこと。

**Comment by yegusa** [comment]
以下の、2つのコマンド以外は、マニュアルどおりにしてできました。

場合によって（？）bundle exec を付ける必要がある旨、マニュアルに書く必要がある気がします。

どういうときに、bundle exec をつけないといけないのか、
わからないので、私の方ではマニュアルにかけないので、だれかわかる人よろしくです。
なので、いったん、checking からはずします。

a) bundle exec を前につけたらうまくいきました。

   $ bundle exec rake enju_purchase_request_engine:install:migrations

b) bundle exec を前につけたらうまくいきました。

  $ bundle exec rake db:migrate RAILS_ENV=production

----

a) つけなかったときの、エラーの内容

```
vagrant@vagrant-ubuntu-trusty-64:~/enju$ rake enju_purchase_request_engine:install:migrations
rake aborted!
Gem::LoadError: You have already activated rake 11.2.2, but your Gemfile requires rake 11.3.0. Prepending `bundle exec` to your command may solve this.
/var/lib/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:35:in `block in setup'
/var/lib/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:20:in `map'
/var/lib/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:20:in `setup'
/var/lib/gems/2.3.0/gems/bundler-1.12.5/lib/bundler.rb:95:in `setup'
/var/lib/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/setup.rb:9:in `<top (required)>'
/home/vagrant/enju/config/boot.rb:3:in `<top (required)>'
/home/vagrant/enju/config/application.rb:1:in `<top (required)>'
/home/vagrant/enju/Rakefile:4:in `<top (required)>'
/var/lib/gems/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
LoadError: cannot load such file -- bundler/setup
/home/vagrant/enju/config/boot.rb:3:in `<top (required)>'
/home/vagrant/enju/config/application.rb:1:in `<top (required)>'
/home/vagrant/enju/Rakefile:4:in `<top (required)>'
/var/lib/gems/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle exec rake enju_purchase_request_engine:install:migrations
Copied migration 20161019113610_create_purchase_requests.enju_purchase_request_engine.rb from enju_purchase_request_engine
Copied migration 20161019113611_create_orders.enju_purchase_request_engine.rb from enju_purchase_request_engine
Copied migration 20161019113612_create_order_lists.enju_purchase_request_engine.rb from enju_purchase_request_engine
Copied migration 20161019113613_create_order_list_transitions.enju_purchase_request_engine.rb from enju_purchase_request_engine
Copied migration 20161019113614_add_most_recent_to_order_list_transitions.enju_purchase_request_engine.rb from enju_purchase_request_engine
vagrant@vagrant-ubuntu-trusty-64:~/enju$ rake db:migrate RAILS_ENV=production
rake aborted!
Gem::LoadError: You have already activated rake 11.2.2, but your Gemfile requires rake 11.3.0. Prepending `bundle exec` to your command may solve this.
/var/lib/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:35:in `block in setup'
/var/lib/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:20:in `map'
/var/lib/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:20:in `setup'
/var/lib/gems/2.3.0/gems/bundler-1.12.5/lib/bundler.rb:95:in `setup'
/var/lib/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/setup.rb:9:in `<top (required)>'
/home/vagrant/enju/config/boot.rb:3:in `<top (required)>'
/home/vagrant/enju/config/application.rb:1:in `<top (required)>'
/home/vagrant/enju/Rakefile:4:in `<top (required)>'
/var/lib/gems/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
LoadError: cannot load such file -- bundler/setup
/home/vagrant/enju/config/boot.rb:3:in `<top (required)>'
/home/vagrant/enju/config/application.rb:1:in `<top (required)>'
/home/vagrant/enju/Rakefile:4:in `<top (required)>'
/var/lib/gems/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)

```

b) bundle exec をつけなかったときの、エラーの内容

```
vagrant@vagrant-ubuntu-trusty-64:~/enju$ rake db:migrate RAILS_ENV=production
rake aborted!
Gem::LoadError: You have already activated rake 11.2.2, but your Gemfile requires rake 11.3.0. Prepending `bundle exec` to your command may solve this.
/var/lib/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:35:in `block in setup'
/var/lib/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:20:in `map'
/var/lib/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:20:in `setup'
/var/lib/gems/2.3.0/gems/bundler-1.12.5/lib/bundler.rb:95:in `setup'
/var/lib/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/setup.rb:9:in `<top (required)>'
/home/vagrant/enju/config/boot.rb:3:in `<top (required)>'
/home/vagrant/enju/config/application.rb:1:in `<top (required)>'
/home/vagrant/enju/Rakefile:4:in `<top (required)>'
/var/lib/gems/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
LoadError: cannot load such file -- bundler/setup
/home/vagrant/enju/config/boot.rb:3:in `<top (required)>'
/home/vagrant/enju/config/application.rb:1:in `<top (required)>'
/home/vagrant/enju/Rakefile:4:in `<top (required)>'
/var/lib/gems/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
```

![image](https://cloud.githubusercontent.com/assets/1328499/19517912/f40e0338-963e-11e6-8369-e42d8df4045e.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.4 1dfb459)
  * enju_bookmark (0.2.0.beta.5)
  * enju_circulation (0.2.0.beta.3 9beab43)
  * enju_event (0.2.0.beta.3)
  * enju_leaf (1.2.0.beta.3 bf2a940)
  * enju_library (0.2.0.beta.9 aac73f4)
  * enju_loc (0.2.0.beta.3 795d91e)
  * enju_manifestation_viewer (0.2.0.beta.4 fb76dd9)
  * enju_message (0.2.0.beta.4)
  * enju_ndl (0.2.0.beta.2 748493b)
  * enju_nii (0.2.0.beta.3 9225546)
  * enju_oai (0.2.0.beta.4 cdeba20)
  * enju_purchase_request (0.2.0.beta.2)
  * enju_seed (0.2.0.beta.6)
  * enju_subject (0.2.0.beta.5)

**Comment by masao** [comment]
基本的には bundle exec をつけた状態で問題がないはずなので、bundle execをマニュアル記述してしまってよいのではないでしょうか。

**Comment by yegusa** [comment]
マニュアルも修正しましたので、クローズします。
