### ISSUE TITLE
ISBN登録時に同名の出版社が複数ある場合にエラーとなる

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1192]
- [x] バグ修正なのでマニュアル修正必要ない ( #1191 )

http://iss.ndl.go.jp/books/R100000002-I024414063-00 のように住所の異なる複数の同名出版社がある場合、ISBN登録時にエラーが発生します。
![the change you wanted was rejected 422](https://cloud.githubusercontent.com/assets/38825/17878257/92078304-6924-11e6-92cc-5773e3230f8e.png)

エラーメッセージは以下の通り：

```
2016-08-23T02:28:02.588339+00:00 app[web.1]: ActiveRecord::RecordInvalid (バリデーションに失敗しました。 Manifestationはすでに存在します。):
2016-08-23T02:28:02.588340+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/validations.rb:79:in `raise_record_invalid'
2016-08-23T02:28:02.588341+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/validations.rb:43:in `save!'
2016-08-23T02:28:02.588342+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
2016-08-23T02:28:02.588342+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/transactions.rb:291:in `block in save!'
2016-08-23T02:28:02.588343+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
2016-08-23T02:28:02.588344+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
2016-08-23T02:28:02.588345+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/transactions.rb:220:in `transaction'
2016-08-23T02:28:02.588345+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
2016-08-23T02:28:02.588346+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/transactions.rb:291:in `save!'
2016-08-23T02:28:02.588347+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/active_record_helper.rb:34:in `block in save!'
2016-08-23T02:28:02.588347+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/transaction.rb:849:in `with_database_metric_name'
2016-08-23T02:28:02.588348+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent.rb:569:in `with_database_metric_name'
2016-08-23T02:28:02.588349+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/active_record_helper.rb:33:in `save!'
2016-08-23T02:28:02.588349+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/associations/has_many_through_association.rb:117:in `save_through_record'
2016-08-23T02:28:02.588350+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/associations/has_many_through_association.rb:66:in `insert_record'
2016-08-23T02:28:02.588351+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/associations/collection_association.rb:563:in `block (2 levels) in concat_records'
2016-08-23T02:28:02.588351+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/associations/collection_association.rb:408:in `replace_on_target'
2016-08-23T02:28:02.588352+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/associations/collection_association.rb:403:in `add_to_target'
2016-08-23T02:28:02.588353+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/associations/collection_association.rb:562:in `block in concat_records'
2016-08-23T02:28:02.588354+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/associations/collection_association.rb:560:in `each'
2016-08-23T02:28:02.588354+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/associations/collection_association.rb:560:in `concat_records'
2016-08-23T02:28:02.588355+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/associations/has_many_association.rb:180:in `concat_records'
2016-08-23T02:28:02.588355+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/associations/has_many_through_association.rb:44:in `concat_records'
2016-08-23T02:28:02.588356+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/associations/collection_association.rb:168:in `block in concat'
2016-08-23T02:28:02.588357+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/associations/collection_association.rb:183:in `block in transaction'
2016-08-23T02:28:02.588358+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
2016-08-23T02:28:02.588358+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/transactions.rb:220:in `transaction'
2016-08-23T02:28:02.588359+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/associations/collection_association.rb:182:in `transaction'
2016-08-23T02:28:02.588359+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/associations/collection_association.rb:168:in `concat'
2016-08-23T02:28:02.588360+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/associations/has_many_through_association.rb:38:in `concat'
2016-08-23T02:28:02.588360+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/associations/collection_proxy.rb:970:in `<<'
2016-08-23T02:28:02.588364+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/bundler/gems/enju_ndl-2d25d11d4e5f/lib/enju_ndl/ndl_search.rb:164:in `block in import_record'
2016-08-23T02:28:02.588365+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
2016-08-23T02:28:02.588366+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
2016-08-23T02:28:02.588366+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
2016-08-23T02:28:02.588367+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/transactions.rb:220:in `transaction'
2016-08-23T02:28:02.588367+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/bundler/gems/enju_ndl-2d25d11d4e5f/lib/enju_ndl/ndl_search.rb:114:in `import_record'
2016-08-23T02:28:02.588368+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/bundler/gems/enju_ndl-2d25d11d4e5f/app/models/ndl_book.rb:78:in `import_from_sru_response'
2016-08-23T02:28:02.588369+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/bundler/gems/enju_ndl-2d25d11d4e5f/app/controllers/ndl_books_controller.rb:25:in `create'
2016-08-23T02:28:02.588369+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
2016-08-23T02:28:02.588370+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7/lib/abstract_controller/base.rb:198:in `process_action'
2016-08-23T02:28:02.588370+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7/lib/action_controller/metal/rendering.rb:10:in `process_action'
2016-08-23T02:28:02.588373+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
2016-08-23T02:28:02.588374+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:117:in `call'
2016-08-23T02:28:02.588374+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
2016-08-23T02:28:02.588375+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:505:in `call'
2016-08-23T02:28:02.588375+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
2016-08-23T02:28:02.588376+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
2016-08-23T02:28:02.588377+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:81:in `run_callbacks'
2016-08-23T02:28:02.588377+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7/lib/abstract_controller/callbacks.rb:19:in `process_action'
2016-08-23T02:28:02.588378+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7/lib/action_controller/metal/rescue.rb:29:in `process_action'
2016-08-23T02:28:02.588379+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
2016-08-23T02:28:02.588379+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/notifications.rb:164:in `block in instrument'
2016-08-23T02:28:02.588380+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
2016-08-23T02:28:02.588380+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/notifications.rb:164:in `instrument'
2016-08-23T02:28:02.588381+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
2016-08-23T02:28:02.588382+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
2016-08-23T02:28:02.588382+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
2016-08-23T02:28:02.588383+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7/lib/abstract_controller/base.rb:137:in `process'
2016-08-23T02:28:02.588384+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionview-4.2.7/lib/action_view/rendering.rb:30:in `process'
2016-08-23T02:28:02.588384+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7/lib/action_controller/metal.rb:196:in `dispatch'
2016-08-23T02:28:02.588385+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
2016-08-23T02:28:02.588386+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7/lib/action_controller/metal.rb:237:in `block in action'
2016-08-23T02:28:02.588386+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
2016-08-23T02:28:02.588387+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7/lib/action_dispatch/routing/route_set.rb:43:in `serve'
2016-08-23T02:28:02.588387+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7/lib/action_dispatch/journey/router.rb:43:in `block in serve'
2016-08-23T02:28:02.588397+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7/lib/action_dispatch/journey/router.rb:30:in `each'
2016-08-23T02:28:02.588398+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7/lib/action_dispatch/journey/router.rb:30:in `serve'
2016-08-23T02:28:02.588399+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7/lib/action_dispatch/routing/route_set.rb:817:in `call'
2016-08-23T02:28:02.588400+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
2016-08-23T02:28:02.588400+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
2016-08-23T02:28:02.588401+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
2016-08-23T02:28:02.588402+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
2016-08-23T02:28:02.588402+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
2016-08-23T02:28:02.588403+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/warden-1.2.6/lib/warden/manager.rb:35:in `block in call'
2016-08-23T02:28:02.588404+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/warden-1.2.6/lib/warden/manager.rb:34:in `catch'
2016-08-23T02:28:02.588405+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/warden-1.2.6/lib/warden/manager.rb:34:in `call'
2016-08-23T02:28:02.588405+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
2016-08-23T02:28:02.588406+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
2016-08-23T02:28:02.588407+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
2016-08-23T02:28:02.588407+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:38:in `call'
2016-08-23T02:28:02.588408+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
2016-08-23T02:28:02.588409+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
2016-08-23T02:28:02.588409+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
2016-08-23T02:28:02.588410+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
2016-08-23T02:28:02.588410+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
2016-08-23T02:28:02.588411+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7/lib/action_dispatch/middleware/flash.rb:260:in `call'
2016-08-23T02:28:02.588411+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
2016-08-23T02:28:02.588412+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
2016-08-23T02:28:02.588413+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
2016-08-23T02:28:02.588413+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
2016-08-23T02:28:02.588414+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7/lib/action_dispatch/middleware/cookies.rb:560:in `call'
2016-08-23T02:28:02.588414+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
2016-08-23T02:28:02.588415+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/query_cache.rb:36:in `call'
2016-08-23T02:28:02.588415+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
2016-08-23T02:28:02.588416+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
2016-08-23T02:28:02.588417+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
2016-08-23T02:28:02.588417+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
2016-08-23T02:28:02.588418+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
2016-08-23T02:28:02.588418+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
2016-08-23T02:28:02.588419+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:81:in `run_callbacks'
2016-08-23T02:28:02.588419+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
2016-08-23T02:28:02.588420+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
2016-08-23T02:28:02.588424+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
2016-08-23T02:28:02.588425+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
2016-08-23T02:28:02.588425+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
2016-08-23T02:28:02.588426+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
2016-08-23T02:28:02.588427+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
2016-08-23T02:28:02.588427+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
2016-08-23T02:28:02.588428+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/railties-4.2.7/lib/rails/rack/logger.rb:38:in `call_app'
2016-08-23T02:28:02.588428+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/railties-4.2.7/lib/rails/rack/logger.rb:20:in `block in call'
2016-08-23T02:28:02.588429+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/tagged_logging.rb:68:in `block in tagged'
2016-08-23T02:28:02.588429+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/tagged_logging.rb:26:in `tagged'
2016-08-23T02:28:02.588430+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/tagged_logging.rb:68:in `tagged'
2016-08-23T02:28:02.588431+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/railties-4.2.7/lib/rails/rack/logger.rb:20:in `call'
2016-08-23T02:28:02.588431+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
2016-08-23T02:28:02.588432+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/request_store-1.3.1/lib/request_store/middleware.rb:9:in `call'
2016-08-23T02:28:02.588433+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
2016-08-23T02:28:02.588433+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7/lib/action_dispatch/middleware/request_id.rb:21:in `call'
2016-08-23T02:28:02.588434+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
2016-08-23T02:28:02.588436+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
2016-08-23T02:28:02.588436+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
2016-08-23T02:28:02.588437+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
2016-08-23T02:28:02.588438+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
2016-08-23T02:28:02.588438+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
2016-08-23T02:28:02.588439+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
2016-08-23T02:28:02.588440+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7/lib/action_dispatch/middleware/static.rb:120:in `call'
2016-08-23T02:28:02.588440+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
2016-08-23T02:28:02.588441+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
2016-08-23T02:28:02.588442+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
2016-08-23T02:28:02.588442+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/railties-4.2.7/lib/rails/engine.rb:518:in `call'
2016-08-23T02:28:02.588443+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/railties-4.2.7/lib/rails/application.rb:165:in `call'
2016-08-23T02:28:02.588443+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
2016-08-23T02:28:02.588444+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:562:in `process_client'
2016-08-23T02:28:02.588445+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:658:in `worker_loop'
2016-08-23T02:28:02.588445+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
2016-08-23T02:28:02.588446+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:519:in `maintain_worker_count'
2016-08-23T02:28:02.588446+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:283:in `join'
2016-08-23T02:28:02.588447+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/gems/unicorn-5.1.0/bin/unicorn:126:in `<top (required)>'
2016-08-23T02:28:02.588447+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/bin/unicorn:23:in `load'
2016-08-23T02:28:02.588448+00:00 app[web.1]:   vendor/bundle/ruby/2.3.0/bin/unicorn:23:in `<main>'
2016-08-23T02:28:02.588448+00:00 app[web.1]:
```

**Comment by masao** [comment]
以下2点の修正を行いました：
・住所が異なる出版社は同一とみなさないように修正。
・同一の出版社に名寄せされたときはユニークな出版社情報だけを書誌情報に紐づけるように修正。

**Comment by nabeta** [comment]
ありがとうございます。出版地も資料詳細画面に表示したほうがよいかなと思いますが、どうしましょう？

**Comment by masao** [comment]
あれ？ 出版地フィールドはすでに表示されていますよ： http://takaku-lib.herokuapp.com/manifestations/656
ここで話題にしているのは「出版地」ではなく、「出版者」（Agent）の住所のほうなので、出版地とは異なると思われます（なにがどう違うかはよく考えると微妙なものですが…）。

**Comment by yegusa** [comment]
別の出版者として登録され、エラーがでずに、書誌情報を登録できることを確認しました。
とりあえず、こちらのissue はクローズします。
バグ修正ですので、とくにマニュアルの修正は必要ないです（ #1191  ）

ただ、出版者の場所を登録していないので、区別できませんね。こちら別issueでしょうか。
出版地が複数ある場合は、どうするかという別issueも作っておきます。

![image](https://cloud.githubusercontent.com/assets/1328499/18813328/cb0d40fe-8331-11e6-98e4-42edace4110d.png)

![image](https://cloud.githubusercontent.com/assets/1328499/18813321/ae305a84-8331-11e6-8326-34bc7a34e565.png)

出版者その1
![image](https://cloud.githubusercontent.com/assets/1328499/18813329/e2660f42-8331-11e6-9c05-95872525536f.png)


出版者その2
![image](https://cloud.githubusercontent.com/assets/1328499/18813333/ed512cca-8331-11e6-9c6a-8461f2609312.png)

**Comment by nabeta** [comment]
この変更でテストが通らなくなっているので、reopenします。
https://travis-ci.org/next-l/enju_biblio/builds/155251085

**Comment by yegusa** [comment]
1つの出版者として、登録され、エラーもでずに登録できることを確認しましたので、クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/21291812/f3157454-c530-11e6-80f6-029cfd471444.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0 0a259aa)
  * enju_bookmark (0.2.0)
  * enju_circulation (0.2.0 7cdf4be)
  * enju_event (0.2.0)
  * enju_leaf (1.2.0 a25e1bf)
  * enju_library (0.2.0 b5d8f4d)
  * enju_loc (0.2.0 83ef039)
  * enju_manifestation_viewer (0.2.0 f1fddb6)
  * enju_message (0.2.0)
  * enju_ndl (0.2.0 da6beb7)
  * enju_nii (0.2.0 03c3dc4)
  * enju_oai (0.2.0 6e5cd6d)
  * enju_purchase_request (0.2.0)
  * enju_seed (0.2.0)
  * enju_subject (0.2.0)
