### ISSUE TITLE
enju_purchase_requestのテストがエラーになる

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1221]
手元でテストを走らせたところ、以下のエラーが出ます：

```
  1) OrdersController GET new When logged in as Administrator assigns the requested order as @order
     Failure/Error: assigns(:order).should_not be_valid

     NoMethodError:
       undefined method `valid?' for nil:NilClass
     # ./spec/controllers/orders_controller_spec.rb:110:in `block (4 levels) in <top (required)>'

  2) OrdersController GET new When logged in as Administrator should redirect to assigns the requested order as @order
     Failure/Error: assigns(:order).should_not be_valid

     NoMethodError:
       undefined method `valid?' for nil:NilClass
     # ./spec/controllers/orders_controller_spec.rb:116:in `block (4 levels) in <top (required)>'

  3) OrdersController GET new When logged in as Administrator assigns the requested order as @order
     Failure/Error: assigns(:order).should_not be_valid

     NoMethodError:
       undefined method `valid?' for nil:NilClass
     # ./spec/controllers/orders_controller_spec.rb:122:in `block (4 levels) in <top (required)>'

  4) OrdersController GET new When logged in as Librarian assigns the requested order as @order
     Failure/Error: assigns(:order).should_not be_valid

     NoMethodError:
       undefined method `valid?' for nil:NilClass
     # ./spec/controllers/orders_controller_spec.rb:134:in `block (4 levels) in <top (required)>'
```

**Comment by nabeta** [comment]
statesmanのバージョンが2.0に上がり、order_list_transitionsテーブルにmost_recentカラムを必要とするようになっているのですが、テストデータにこのカラムがありませんでした。テストデータを修正しました。

**Comment by masao** [comment]
修正を確認しました。クローズします。
