### ISSUE TITLE
rspec実行時にエラー

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1259]
手元でのenju_biblioのテストコードrspec実行時にRedis周りのエラーが出る：

```
bundler: failed to load command: rspec (/home/vagrant/.rbenv/versions/2.3.3/bin/rspec)
Redis::CannotConnectError: Error connecting to Redis on localhost:9736 (Errno::ECONNREFUSED)
  /home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:345:in `rescue in establish_connection'
  /home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:331:in `establish_connection'
  /home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:101:in `block in connect'
  /home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:293:in `with_reconnect'
  /home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:100:in `connect'
  /home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:364:in `ensure_connected'
  /home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:221:in `block in process'
  /home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:306:in `logging'
  /home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:220:in `process'
  /home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:120:in `call'
  /home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.3/lib/redis.rb:351:in `block in time'
  /home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.3/lib/redis.rb:58:in `block in synchronize'
  /home/vagrant/.rbenv/versions/2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
  /home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.3/lib/redis.rb:58:in `synchronize'
  /home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.3/lib/redis.rb:350:in `time'
  /home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-namespace-1.5.3/lib/redis/namespace.rb:435:in `call_with_namespace'
  /home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-namespace-1.5.3/lib/redis/namespace.rb:321:in `method_missing'
  /home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/resque-1.27.2/lib/resque/data_store.rb:100:in `redis_time_available?'
  /home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/resque-1.27.2/lib/resque/data_store.rb:15:in `initialize'
  /home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/resque-1.27.2/lib/resque.rb:125:in `new'
  /home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/resque-1.27.2/lib/resque.rb:125:in `redis='
  /home/vagrant/enju_biblio/spec/support/resque.rb:7:in `block in <top (required)>'
  /home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core.rb:98:in `configure'
  /home/vagrant/enju_biblio/spec/support/resque.rb:2:in `<top (required)>'
  /home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
  /home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
  /home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
  /home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
  /home/vagrant/enju_biblio/spec/rails_helper.rb:20:in `block in <top (required)>'
  /home/vagrant/enju_biblio/spec/rails_helper.rb:20:in `each'
  /home/vagrant/enju_biblio/spec/rails_helper.rb:20:in `<top (required)>'
  /home/vagrant/enju_biblio/spec/controllers/agent_import_files_controller_spec.rb:2:in `require'
  /home/vagrant/enju_biblio/spec/controllers/agent_import_files_controller_spec.rb:2:in `<top (required)>'
  /home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `load'
  /home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
  /home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `each'
  /home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
  /home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:100:in `setup'
  /home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
  /home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
  /home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
  /home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/exe/rspec:4:in `<top (required)>'
  /home/vagrant/.rbenv/versions/2.3.3/bin/rspec:22:in `load'
  /home/vagrant/.rbenv/versions/2.3.3/bin/rspec:22:in `<top (required)>'
[Coveralls] Outside the CI environment, not sending data.
```

**Comment by masao** [comment]
spec/support/resque.rb 内の
```ruby
 Resque.redis = "http://localhost:9736"
```
なる一行を除去して対応しました。

**Comment by nabeta** [comment]
enju_circulation, enju_event, enju_leafでも同様の問題があるようです。修正しておきます。

**Comment by nabeta** [comment]
> enju_circulation, enju_event, enju_leafでも同様の問題があるようです。

それぞれ修正し、テストが通ることを確認しました。

**Comment by masao** [comment]
enju_circulationとenju_eventは確認したのですが、enju_leafでは以下のようなエラーがでます：

```
$ bundle exec rspec
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.
bundler: failed to load command: rspec (/home/vagrant/.rbenv/versions/2.4.1/bin/rspec)
LoadError: cannot load such file -- globalize
  /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
  /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
  /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
  /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
  /home/vagrant/enju_leaf/spec/dummy/config/application.rb:9:in `<top (required)>'
  /home/vagrant/enju_leaf/spec/dummy/config/environment.rb:2:in `require'
  /home/vagrant/enju_leaf/spec/dummy/config/environment.rb:2:in `<top (required)>'
  /home/vagrant/enju_leaf/spec/rails_helper.rb:8:in `require'
  /home/vagrant/enju_leaf/spec/rails_helper.rb:8:in `<top (required)>'
  /home/vagrant/enju_leaf/spec/controllers/page_controller_spec.rb:1:in `require'
  /home/vagrant/enju_leaf/spec/controllers/page_controller_spec.rb:1:in `<top (required)>'
  /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `load'
  /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
  /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `each'
  /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
  /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:100:in `setup'
  /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
  /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
  /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
  /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/exe/rspec:4:in `<top (required)>'
  /home/vagrant/.rbenv/versions/2.4.1/bin/rspec:22:in `load'
  /home/vagrant/.rbenv/versions/2.4.1/bin/rspec:22:in `<top (required)>'
/home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/simplecov-0.12.0/lib/simplecov/configuration.rb:207: warning: constant ::Fixnum is deprecated
[Coveralls] Outside the CI environment, not sending data.
/home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/simplecov-0.12.0/lib/simplecov/configuration.rb:207: warning: constant ::Fixnum is deprecated
/home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/simplecov-0.12.0/lib/simplecov/source_file.rb:29: warning: constant ::Fixnum is deprecated
/home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/simplecov-0.12.0/lib/simplecov/source_file.rb:30: warning: constant ::Fixnum is deprecated
```

**Comment by nabeta** [comment]
enju_leafについて、手元の環境で同じエラーが出ることを確認しました。
現在は修正済みです。

**Comment by masao** [comment]
ひとまず同様のエラーは出なくなっているようなので、クローズします。
