### ISSUE TITLE
1.2.0->1.2.1更新の際にrake enju_leaf:upgrade実行時にエラー

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1274]
素の公式1.2.0仮想マシンにおいて、1.2.1へ更新しようとrake enju_leaf:upgradeコマンドを実行するとエラーが出ます：

```
rake enju_leaf:upgrade
rake aborted!
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "user_export_files" does not exist
LINE 5:                WHERE a.attrelid = '"user_export_files"'::reg...
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attrelid = '"user_export_files"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum
/home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `async_exec'
/home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `block in exec_no_cache'
/home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `exec_no_cache'
/home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/postgresql_adapter.rb:584:in `execute_and_clear'
/home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
/home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/postgresql_adapter.rb:733:in `column_definitions'
/home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/postgresql/schema_statements.rb:197:in `columns'
/home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/schema_cache.rb:43:in `columns'
/home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/attributes.rb:93:in `columns'
/home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/model_schema.rb:260:in `column_names'
/home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/relation/calculations.rb:232:in `aggregate_column'
/home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/relation/calculations.rb:258:in `execute_simple_calculation'
/home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/relation/calculations.rb:227:in `perform_calculation'
/home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/relation/calculations.rb:133:in `calculate'
/home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/relation/calculations.rb:48:in `count'
/home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/querying.rb:13:in `count'
/home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/statesman-1.3.1/lib/tasks/statesman.rake:12:in `block (2 levels) in <top (required)>'
/home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/enju_library-0.2.2/lib/tasks/enju_library_tasks.rake:18:in `block (2 levels) in <top (required)>'
/home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/enju_leaf-1.2.1/lib/tasks/enju_leaf_tasks.rake:24:in `block (2 levels) in <top (required)>'
PG::UndefinedTable: ERROR:  relation "user_export_files" does not exist
LINE 5:                WHERE a.attrelid = '"user_export_files"'::reg...
                                          ^
/home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `async_exec'
/home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `block in exec_no_cache'
/home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `exec_no_cache'
/home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/postgresql_adapter.rb:584:in `execute_and_clear'
/home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
/home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/postgresql_adapter.rb:733:in `column_definitions'
/home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/postgresql/schema_statements.rb:197:in `columns'
/home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/schema_cache.rb:43:in `columns'
/home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/attributes.rb:93:in `columns'
/home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/model_schema.rb:260:in `column_names'
/home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/relation/calculations.rb:232:in `aggregate_column'
/home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/relation/calculations.rb:258:in `execute_simple_calculation'
/home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/relation/calculations.rb:227:in `perform_calculation'
/home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/relation/calculations.rb:133:in `calculate'
/home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/relation/calculations.rb:48:in `count'
/home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/querying.rb:13:in `count'
/home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/statesman-1.3.1/lib/tasks/statesman.rake:12:in `block (2 levels) in <top (required)>'
/home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/enju_library-0.2.2/lib/tasks/enju_library_tasks.rake:18:in `block (2 levels) in <top (required)>'
/home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/enju_leaf-1.2.1/lib/tasks/enju_leaf_tasks.rake:24:in `block (2 levels) in <top (required)>'
Tasks: TOP => statesman:backfill_most_recent
(See full trace by running task with --trace)
```

**Comment by nabeta** [comment]
以下のコマンドを実行後、もう一度試してもらえますか？

```
$ rake railties:install:migrations
$ rake db:migrate RAILS_ENV=production
```

**Comment by masao** [comment]
上記のコマンド実行した後も、エラーに変更ありません。

**Comment by nabeta** [comment]
環境変数RAILS_ENVを設定する必要がありました。Wikiの手順も修正しました。

```
 $ rake enju_leaf:upgrade RAILS_ENV=production
```

**Comment by masao** [comment]
確認しました。問題が出なくなりましたのでクローズします。
