### ISSUE TITLE
paperclip 4.3.7 以降でUninitialized Constant Paperclip::Storage::S3::Awsエラーとなる

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1289]
- [x] markdown のマニュアル修正必要なし #1279 

Herokuでの1.1系から1.2系への移行ではまったので。

paperclipの現在の最新版は 5.1.0 だが、このバージョンをそのまま使うと、enju:upgrade スクリプト実行時に以下のようなエラーが出る：

```
NameError: uninitialized constant Paperclip::Storage::S3::Aws
/app/vendor/bundle/ruby/2.4.0/gems/paperclip-5.1.0/lib/paperclip/storage/s3.rb:125:in `extended'
/app/vendor/bundle/ruby/2.4.0/gems/paperclip-5.1.0/lib/paperclip/attachment.rb:428:in `extend'
/app/vendor/bundle/ruby/2.4.0/gems/paperclip-5.1.0/lib/paperclip/attachment.rb:428:in `initialize_storage'
/app/vendor/bundle/ruby/2.4.0/gems/paperclip-5.1.0/lib/paperclip/attachment.rb:90:in `initialize'
/app/vendor/bundle/ruby/2.4.0/gems/paperclip-5.1.0/lib/paperclip/has_attached_file.rb:47:in `new'
/app/vendor/bundle/ruby/2.4.0/gems/paperclip-5.1.0/lib/paperclip/has_attached_file.rb:47:in `block in define_instance_getter'
/app/vendor/bundle/ruby/2.4.0/gems/paperclip-5.1.0/lib/paperclip/has_attached_file.rb:66:in `block in define_setter'
/app/vendor/bundle/ruby/2.4.0/gems/enju_biblio-0.2.2/lib/tasks/carrier_type.rb:8:in `block in update_carrier_type'
/app/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/relation/batches.rb:51:in `block (2 levels) in find_each'
/app/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/relation/batches.rb:51:in `each'
/app/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/relation/batches.rb:51:in `block in find_each'
/app/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/relation/batches.rb:124:in `find_in_batches'
/app/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/relation/batches.rb:50:in `find_each'
/app/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/querying.rb:9:in `find_each'
/app/vendor/bundle/ruby/2.4.0/gems/enju_biblio-0.2.2/lib/tasks/carrier_type.rb:2:in `update_carrier_type'
/app/vendor/bundle/ruby/2.4.0/gems/enju_biblio-0.2.2/lib/tasks/enju_biblio_tasks.rake:33:in `block (2 levels) in <top (required)>'
/app/vendor/bundle/ruby/2.4.0/gems/enju_leaf-1.2.1/lib/tasks/enju_leaf_tasks.rake:25:in `block (2 levels) in <top (required)>'
/app/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:74:in `load'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:27:in `run'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/cli.rb:360:in `exec'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/cli.rb:20:in `dispatch'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/cli.rb:10:in `start'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/exe/bundle:35:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/exe/bundle:27:in `<top (required)>'
/app/bin/bundle:3:in `load'
/app/bin/bundle:3:in `<main>'
Tasks: TOP => enju_biblio:upgrade
(See full trace by running task with --trace)
```

https://github.com/thoughtbot/paperclip/issues/2388 を見ると、paperclip は 4.3.6 を指定するとよさそう。
以下のように個別バージョンを指定したところ、エラーとならずに成功した：

```ruby
gem "paperclip", "4.3.6"
```

**Comment by nabeta** [comment]
@masao これはもともとS3を使用するように設定していたときに出たエラーでしょうか？

**Comment by masao** [comment]
はい、Herokuでの運用ですので、S3設定がはいっていた状態です。

**Comment by nabeta** [comment]
4.3系を使用するように指定しました。

**Comment by yegusa** [comment]
こちらの確認は @masao よろしく。

**Comment by masao** [comment]
確認も困難で、環境が得られないため、ひとまずクローズします。
なにか問題が再現されるようなら、再度オープンしましょう。
