### ISSUE TITLE
新規インストール時に bundle exec foreman startにて foreman 実行ができない

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1290]
https://github.com/next-l/enju_leaf/wiki/Install インストール手順に従って、新規インストールを行った際に、最後の段階でforemanでの起動がエラーとなってしまう。

```
$ bundle exec foreman start
bundler: failed to load command: foreman (/home/vagrant/.rbenv/versions/2.4.1/bin/foreman)
Gem::Exception: can't find executable foreman for gem foreman. foreman is not currently included in the bundle, perhaps you meant to add it to your Gemfile?
  /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/rubygems_integration.rb:432:in `block in replace_bin_path'
  /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/rubygems_integration.rb:452:in `block in replace_bin_path'
  /home/vagrant/.rbenv/versions/2.4.1/bin/foreman:22:in `<top (required)>'
```

**Comment by nabeta** [comment]
以下のコマンドを実行してください。

```
$ gem install foreman
```

インストール手順は修正済みです。
https://github.com/next-l/enju_leaf/wiki/Install#railsのインストール

**Comment by masao** [comment]
確認しました。ひとまずクローズします。
