### ISSUE TITLE
[Heroku] 1.2.2への更新手順 (routes.rb)

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1351]
手元のHeroku環境（ https://takaku-lib.herokuapp.com/ ）を更新していて、ウィキの更新手順（ https://github.com/next-l/enju_leaf/wiki/Update ）に従うとエラーがでるようなので、報告しておきます。
エラー内容の抜粋は以下の通りです：

```
...
-----> Preparing app for Rails asset pipeline
       Running: rake assets:precompile
       rake aborted!
       ArgumentError: Invalid route name, already in use: 'edit_user_registration'
       You may have defined two routes with the same name using the `:as` option, or you may be overriding a route already defined by a resource with the same naming. For the latter, you can restrict the routes created with `resources` as explained here:
       http://guides.rubyonrails.org/routing.html#restricting-the-routes-created
```

特に、ウィキの更新手順のなかで：
> config/routes.rb に以下の行があることを確認します。

という記述の箇所で、指定された行が見当たらなかったので、コピペで追加したのですが、指定された記述が見つからなかった場合の指示は何になるでしょうか？

**Comment by nabeta** [comment]
反応が遅くなってすみません。現在の config/routes.rb の中身を見せていただけますか？

**Comment by masao** [comment]
現在の config/routes.rb は以下の通りです：
https://gist.github.com/masao/0703f22716020f506ce5e33515845b30

**Comment by nabeta** [comment]
見つからなかった場合は、以下の内容をそのままペーストするので正しいです。

```
  as :user do
    get 'users/edit' => 'devise/registrations#edit', as: 'edit_user_registration'
    put 'users' => 'devise/registrations#update', as: 'user_registration'
  end
```

Wikiの記述も修正しました。
https://github.com/next-l/enju_leaf/wiki/Update

**Comment by masao** [comment]
うーん、そのままペーストするとエラーになります。。。

```
       Running: rake assets:precompile
       rake aborted!
       ArgumentError: Invalid route name, already in use: 'edit_user_registration'
       You may have defined two routes with the same name using the `:as` option, or you may be overriding a route already defined by a resource with the same naming. For the latter, you can restrict the routes created with `resources` as explained here:
       http://guides.rubyonrails.org/routing.html#restricting-the-routes-created
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/routing/route_set.rb:549:in `add_route'
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/routing/mapper.rb:1563:in `add_route'
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/routing/mapper.rb:1538:in `decomposed_match'
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/routing/mapper.rb:1519:in `block in match'
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/routing/mapper.rb:1509:in `each'
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/routing/mapper.rb:1509:in `match'
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/routing/mapper.rb:691:in `map_method'
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/routing/mapper.rb:652:in `get'
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/config/routes.rb:9:in `block (2 levels) in <top (required)>'
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/vendor/bundle/ruby/2.5.0/gems/devise-4.4.1/lib/devise/rails/routes.rb:370:in `block in devise_scope'
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/routing/mapper.rb:942:in `block in constraints'
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/routing/mapper.rb:818:in `scope'
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/routing/mapper.rb:942:in `constraints'
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/vendor/bundle/ruby/2.5.0/gems/devise-4.4.1/lib/devise/rails/routes.rb:369:in `devise_scope'
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/config/routes.rb:8:in `block in <top (required)>'
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/routing/route_set.rb:432:in `instance_exec'
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/routing/route_set.rb:432:in `eval_block'
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/routing/route_set.rb:410:in `draw'
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/config/routes.rb:1:in `<top (required)>'
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `block in load'
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application/routes_reloader.rb:40:in `each'
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application/routes_reloader.rb:40:in `load_paths'
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application/routes_reloader.rb:16:in `reload!'
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application/routes_reloader.rb:26:in `block in updater'
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/file_update_checker.rb:75:in `execute'
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application/routes_reloader.rb:27:in `updater'
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `instance_exec'
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `run'
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:55:in `block in run_initializers'
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:54:in `run_initializers'
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application.rb:352:in `initialize!'
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/config/environment.rb:5:in `<top (required)>'
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application.rb:328:in `require_environment!'
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application.rb:457:in `block in run_tasks_blocks'
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
       /tmp/build_dcf165ff56ab6da2913f6ecb3db321a9/masao-takaku-library-6cef58c/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
       Tasks: TOP => environment
       (See full trace by running task with --trace)
 !
 !     Precompiling assets failed.
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed
Build finished
```

**Comment by nabeta** [comment]
@masao devise_for よりも前の行に記入するとどうでしょうか。

**Comment by masao** [comment]
device_for よりも前の行に書くと、エラーが出なくなりました。

**Comment by yegusa** [comment]
ドキュメントを直す。
確認は難しいので、とりあえず、クローズすることに。
Enju WS 2018-06-10 の議論より。

**Comment by nabeta** [comment]
ドキュメントの以下の部分を直しました。
https://github.com/next-l/enju_leaf/wiki/Update-to-1.2

```ruby
# devise_forの前に以下の3行を追加
authenticate :user, lambda {|u| u.role.try(:name) == 'Administrator' } do
  mount Resque::Server.new, at: "/resque", as: :resque
end

devise_for :users, skip: [:registration]
```
