### ISSUE TITLE
アップデートしたら動きません

### ISSUE THREAD

**Issue by yano-do** [next-l/enju_leaf#1358]
アップデートしたら動きませんでした。
ログを見ていただきたく存じます。
よろしくお願いいたします。
```
Feb 24 04:57:56 vagrant systemd[1]: Stopped target enju_leaf-web.target.
Feb 24 04:57:56 vagrant systemd[1]: Stopping enju_leaf-web.target.
Feb 24 04:57:56 vagrant systemd[1]: Started enju_leaf-web@5100.service.
Feb 24 04:57:56 vagrant systemd[1]: Stopped target enju_leaf-resque.target.
Feb 24 04:57:56 vagrant systemd[1]: Stopping enju_leaf-resque.target.
Feb 24 04:57:56 vagrant systemd[1]: Stopping enju_leaf-resque@5000.service...
Feb 24 04:57:56 vagrant systemd[1]: Stopped target enju_leaf.target.
Feb 24 04:57:56 vagrant systemd[1]: Stopping enju_leaf.target.
Feb 24 04:57:56 vagrant systemd[1]: Reached target enju_leaf.target.
Feb 24 04:57:56 vagrant systemd[1]: Reached target enju_leaf-web.target.
Feb 24 04:57:57 vagrant enju_leaf-web@5100.service[17927]: /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/unicorn-5.4.0/lib/unicorn/configurator.rb:84:in `read': No such file or directory @ rb_sysopen - config/unicorn.rb (Errno::ENOENT)
Feb 24 04:57:57 vagrant enju_leaf-web@5100.service[17927]: #011from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/unicorn-5.4.0/lib/unicorn/configurator.rb:84:in `reload'
Feb 24 04:57:57 vagrant enju_leaf-web@5100.service[17927]: #011from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/unicorn-5.4.0/lib/unicorn/configurator.rb:77:in `initialize'
Feb 24 04:57:57 vagrant enju_leaf-web@5100.service[17927]: #011from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/unicorn-5.4.0/lib/unicorn/http_server.rb:77:in `new'
Feb 24 04:57:57 vagrant enju_leaf-web@5100.service[17927]: #011from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/unicorn-5.4.0/lib/unicorn/http_server.rb:77:in `initialize'
Feb 24 04:57:57 vagrant enju_leaf-web@5100.service[17927]: #011from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/unicorn-5.4.0/bin/unicorn:126:in `new'
Feb 24 04:57:57 vagrant enju_leaf-web@5100.service[17927]: #011from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/unicorn-5.4.0/bin/unicorn:126:in `<top (required)>'
Feb 24 04:57:57 vagrant enju_leaf-web@5100.service[17927]: #011from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/bin/unicorn:23:in `load'
Feb 24 04:57:57 vagrant enju_leaf-web@5100.service[17927]: #011from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/bin/unicorn:23:in `<main>'
Feb 24 04:57:57 vagrant systemd[1]: enju_leaf-web@5100.service: Main process exited, code=exited, status=1/FAILURE
Feb 24 04:57:57 vagrant systemd[1]: enju_leaf-web@5100.service: Unit entered failed state.
Feb 24 04:57:57 vagrant systemd[1]: enju_leaf-web@5100.service: Failed with result 'exit-code'.
Feb 24 04:57:58 vagrant systemd[1]: enju_leaf-web@5100.service: Service hold-off time over, scheduling restart.
Feb 24 04:57:58 vagrant systemd[1]: Stopped enju_leaf-web@5100.service.
Feb 24 04:57:58 vagrant systemd[1]: Started enju_leaf-web@5100.service.
Feb 24 04:57:59 vagrant enju_leaf-web@5100.service[17935]: /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/unicorn-5.4.0/lib/unicorn/configurator.rb:84:in `read': No such file or directory @ rb_sysopen - config/unicorn.rb (Errno::ENOENT)
Feb 24 04:57:59 vagrant enju_leaf-web@5100.service[17935]: #011from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/unicorn-5.4.0/lib/unicorn/configurator.rb:84:in `reload'
Feb 24 04:57:59 vagrant enju_leaf-web@5100.service[17935]: #011from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/unicorn-5.4.0/lib/unicorn/configurator.rb:77:in `initialize'
Feb 24 04:57:59 vagrant enju_leaf-web@5100.service[17935]: #011from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/unicorn-5.4.0/lib/unicorn/http_server.rb:77:in `new'
Feb 24 04:57:59 vagrant enju_leaf-web@5100.service[17935]: #011from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/unicorn-5.4.0/lib/unicorn/http_server.rb:77:in `initialize'
Feb 24 04:57:59 vagrant enju_leaf-web@5100.service[17935]: #011from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/unicorn-5.4.0/bin/unicorn:126:in `new'
Feb 24 04:57:59 vagrant enju_leaf-web@5100.service[17935]: #011from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/unicorn-5.4.0/bin/unicorn:126:in `<top (required)>'
Feb 24 04:57:59 vagrant enju_leaf-web@5100.service[17935]: #011from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/bin/unicorn:23:in `load'
Feb 24 04:57:59 vagrant enju_leaf-web@5100.service[17935]: #011from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/bin/unicorn:23:in `<main>'
Feb 24 04:57:59 vagrant systemd[1]: enju_leaf-web@5100.service: Main process exited, code=exited, status=1/FAILURE
Feb 24 04:57:59 vagrant systemd[1]: enju_leaf-web@5100.service: Unit entered failed state.
Feb 24 04:57:59 vagrant systemd[1]: enju_leaf-web@5100.service: Failed with result 'exit-code'.
Feb 24 04:57:59 vagrant systemd[1]: enju_leaf-web@5100.service: Service hold-off time over, scheduling restart.
Feb 24 04:57:59 vagrant systemd[1]: Stopped enju_leaf-web@5100.service.
Feb 24 04:57:59 vagrant systemd[1]: Started enju_leaf-web@5100.service.
Feb 24 04:57:59 vagrant systemd[1]: Stopped enju_leaf-resque@5000.service.
Feb 24 04:57:59 vagrant systemd[1]: Started enju_leaf-resque@5000.service.
Feb 24 04:57:59 vagrant systemd[1]: Reached target enju_leaf-resque.target.
Feb 24 04:58:01 vagrant enju_leaf-web@5100.service[17942]: /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/unicorn-5.4.0/lib/unicorn/configurator.rb:84:in `read': No such file or directory @ rb_sysopen - config/unicorn.rb (Errno::ENOENT)
Feb 24 04:58:01 vagrant enju_leaf-web@5100.service[17942]: #011from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/unicorn-5.4.0/lib/unicorn/configurator.rb:84:in `reload'
Feb 24 04:58:01 vagrant enju_leaf-web@5100.service[17942]: #011from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/unicorn-5.4.0/lib/unicorn/configurator.rb:77:in `initialize'
Feb 24 04:58:01 vagrant enju_leaf-web@5100.service[17942]: #011from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/unicorn-5.4.0/lib/unicorn/http_server.rb:77:in `new'
Feb 24 04:58:01 vagrant enju_leaf-web@5100.service[17942]: #011from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/unicorn-5.4.0/lib/unicorn/http_server.rb:77:in `initialize'
Feb 24 04:58:01 vagrant enju_leaf-web@5100.service[17942]: #011from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/unicorn-5.4.0/bin/unicorn:126:in `new'
Feb 24 04:58:01 vagrant enju_leaf-web@5100.service[17942]: #011from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/unicorn-5.4.0/bin/unicorn:126:in `<top (required)>'
Feb 24 04:58:01 vagrant enju_leaf-web@5100.service[17942]: #011from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/bin/unicorn:23:in `load'
Feb 24 04:58:01 vagrant enju_leaf-web@5100.service[17942]: #011from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/bin/unicorn:23:in `<main>'
Feb 24 04:58:01 vagrant systemd[1]: enju_leaf-web@5100.service: Main process exited, code=exited, status=1/FAILURE
Feb 24 04:58:01 vagrant systemd[1]: enju_leaf-web@5100.service: Unit entered failed state.
Feb 24 04:58:01 vagrant systemd[1]: enju_leaf-web@5100.service: Failed with result 'exit-code'.
Feb 24 04:58:01 vagrant systemd[1]: enju_leaf-web@5100.service: Service hold-off time over, scheduling restart.
Feb 24 04:58:01 vagrant systemd[1]: Stopped enju_leaf-web@5100.service.
Feb 24 04:58:01 vagrant systemd[1]: Started enju_leaf-web@5100.service.
Feb 24 04:58:03 vagrant enju_leaf-web@5100.service[17957]: /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/unicorn-5.4.0/lib/unicorn/configurator.rb:84:in `read': No such file or directory @ rb_sysopen - config/unicorn.rb (Errno::ENOENT)
Feb 24 04:58:03 vagrant enju_leaf-web@5100.service[17957]: #011from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/unicorn-5.4.0/lib/unicorn/configurator.rb:84:in `reload'
Feb 24 04:58:03 vagrant enju_leaf-web@5100.service[17957]: #011from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/unicorn-5.4.0/lib/unicorn/configurator.rb:77:in `initialize'
Feb 24 04:58:03 vagrant enju_leaf-web@5100.service[17957]: #011from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/unicorn-5.4.0/lib/unicorn/http_server.rb:77:in `new'
Feb 24 04:58:03 vagrant enju_leaf-web@5100.service[17957]: #011from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/unicorn-5.4.0/lib/unicorn/http_server.rb:77:in `initialize'
Feb 24 04:58:03 vagrant enju_leaf-web@5100.service[17957]: #011from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/unicorn-5.4.0/bin/unicorn:126:in `new'
Feb 24 04:58:03 vagrant enju_leaf-web@5100.service[17957]: #011from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/unicorn-5.4.0/bin/unicorn:126:in `<top (required)>'
Feb 24 04:58:03 vagrant enju_leaf-web@5100.service[17957]: #011from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/bin/unicorn:23:in `load'
Feb 24 04:58:03 vagrant enju_leaf-web@5100.service[17957]: #011from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/bin/unicorn:23:in `<main>'
Feb 24 04:58:03 vagrant systemd[1]: enju_leaf-web@5100.service: Main process exited, code=exited, status=1/FAILURE
Feb 24 04:58:03 vagrant systemd[1]: enju_leaf-web@5100.service: Unit entered failed state.
Feb 24 04:58:03 vagrant systemd[1]: enju_leaf-web@5100.service: Failed with result 'exit-code'.
Feb 24 04:58:03 vagrant systemd[1]: enju_leaf-web@5100.service: Service hold-off time over, scheduling restart.
Feb 24 04:58:03 vagrant systemd[1]: Stopped enju_leaf-web@5100.service.
Feb 24 04:58:03 vagrant systemd[1]: Started enju_leaf-web@5100.service.
Feb 24 04:58:06 vagrant enju_leaf-web@5100.service[17964]: /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/unicorn-5.4.0/lib/unicorn/configurator.rb:84:in `read': No such file or directory @ rb_sysopen - config/unicorn.rb (Errno::ENOENT)
Feb 24 04:58:06 vagrant enju_leaf-web@5100.service[17964]: #011from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/unicorn-5.4.0/lib/unicorn/configurator.rb:84:in `reload'
Feb 24 04:58:06 vagrant enju_leaf-web@5100.service[17964]: #011from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/unicorn-5.4.0/lib/unicorn/configurator.rb:77:in `initialize'
Feb 24 04:58:06 vagrant enju_leaf-web@5100.service[17964]: #011from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/unicorn-5.4.0/lib/unicorn/http_server.rb:77:in `new'
Feb 24 04:58:06 vagrant enju_leaf-web@5100.service[17964]: #011from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/unicorn-5.4.0/lib/unicorn/http_server.rb:77:in `initialize'
Feb 24 04:58:06 vagrant enju_leaf-web@5100.service[17964]: #011from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/unicorn-5.4.0/bin/unicorn:126:in `new'
Feb 24 04:58:06 vagrant enju_leaf-web@5100.service[17964]: #011from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/unicorn-5.4.0/bin/unicorn:126:in `<top (required)>'
Feb 24 04:58:06 vagrant enju_leaf-web@5100.service[17964]: #011from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/bin/unicorn:23:in `load'
Feb 24 04:58:06 vagrant enju_leaf-web@5100.service[17964]: #011from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/bin/unicorn:23:in `<main>'
Feb 24 04:58:06 vagrant systemd[1]: enju_leaf-web@5100.service: Main process exited, code=exited, status=1/FAILURE
Feb 24 04:58:06 vagrant systemd[1]: enju_leaf-web@5100.service: Unit entered failed state.
Feb 24 04:58:06 vagrant systemd[1]: enju_leaf-web@5100.service: Failed with result 'exit-code'.
Feb 24 04:58:06 vagrant systemd[1]: enju_leaf-web@5100.service: Service hold-off time over, scheduling restart.
Feb 24 04:58:06 vagrant systemd[1]: Stopped enju_leaf-web@5100.service.
Feb 24 04:58:06 vagrant systemd[1]: enju_leaf-web@5100.service: Start request repeated too quickly.
Feb 24 04:58:06 vagrant systemd[1]: Failed to start enju_leaf-web@5100.service.
Feb 24 04:58:13 vagrant enju_leaf-resque@5000.service[17948]: The PGconn, PGresult, and PGError constants are deprecated, and will be
Feb 24 04:58:13 vagrant enju_leaf-resque@5000.service[17948]: removed as of version 1.0.
Feb 24 04:58:13 vagrant enju_leaf-resque@5000.service[17948]: You should use PG::Connection, PG::Result, and PG::Error instead, respectively.
Feb 24 04:58:13 vagrant enju_leaf-resque@5000.service[17948]: Called from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
```

**Comment by nabeta** [comment]
```
No such file or directory @ rb_sysopen - config/unicorn.rb (Errno::ENOENT
```

というエラーが出ているので、 config/unicorn.rb というファイルがないようです。
バックアップから書き戻すか、以下の内容のファイルを config/unicorn.rb という名前で作成して、Enjuを再起動してください。
https://gist.githubusercontent.com/nabeta/755b64fb930633d48767/raw

**Comment by yano-do** [comment]
unicorn.rb を作成して再起動したら正常に動きました。
ありがとうございました。
