### ISSUE TITLE
enju_leaf:quick_install でDBエラーが出る

### ISSUE THREAD

**Issue by nakamura-akifumi** [next-l/enju_leaf#1372]
Mac OS X でインストール手順通り進めていたつもりですが、
enju_leaf:quick_install でエラーが発生して進めることが出来ません。
PostgreSQLは、brew を使っています。
postgresql: stable 10.3 (bottled), HEAD
です。

```
        rake  enju_leaf:setup
The PGconn, PGresult, and PGError constants are deprecated, and will be
removed as of version 1.0.

You should use PG::Connection, PG::Result, and PG::Error instead, respectively.

Called from /Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
rake aborted!
ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column "increment_by" does not exist
LINE 1: ...oups_id_seq"', (SELECT COALESCE(MAX("id")+(SELECT increment_...
                                                             ^
:               SELECT setval('"public"."user_groups_id_seq"', (SELECT COALESCE(MAX("id")+(SELECT increment_by FROM "public"."user_groups_id_seq"), (SELECT min_value FROM "public"."user_groups_id_seq")) FROM "user_groups"), false)
/Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `async_exec'
/Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `block in exec_no_cache'
/Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `exec_no_cache'
/Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:584:in `execute_and_clear'
/Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql/database_statements.rb:50:in `select_value'
/Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql/schema_statements.rb:338:in `reset_pk_sequence!'
/Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/fixtures.rb:540:in `block (3 levels) in create_fixtures'
/Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/fixtures.rb:524:in `each'
/Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/fixtures.rb:524:in `block (2 levels) in create_fixtures'
/Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/fixtures.rb:523:in `block in create_fixtures'
/Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql/referential_integrity.rb:17:in `disable_referential_integrity'
/Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/fixtures.rb:508:in `create_fixtures'
/Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/enju_leaf-1.2.2/lib/tasks/enju_leaf_tasks.rake:8:in `block (3 levels) in <top (required)>'
/Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/enju_leaf-1.2.2/lib/tasks/enju_leaf_tasks.rake:7:in `each'
/Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/enju_leaf-1.2.2/lib/tasks/enju_leaf_tasks.rake:7:in `block (2 levels) in <top (required)>'
/Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'

Caused by:
PG::UndefinedColumn: ERROR:  column "increment_by" does not exist
LINE 1: ...oups_id_seq"', (SELECT COALESCE(MAX("id")+(SELECT increment_...
                                                             ^
/Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `async_exec'
/Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `block in exec_no_cache'
/Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `exec_no_cache'
/Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:584:in `execute_and_clear'
/Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql/database_statements.rb:50:in `select_value'
/Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql/schema_statements.rb:338:in `reset_pk_sequence!'
/Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/fixtures.rb:540:in `block (3 levels) in create_fixtures'
/Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/fixtures.rb:524:in `each'
/Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/fixtures.rb:524:in `block (2 levels) in create_fixtures'
/Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/fixtures.rb:523:in `block in create_fixtures'
/Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql/referential_integrity.rb:17:in `disable_referential_integrity'
/Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/fixtures.rb:508:in `create_fixtures'
/Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/enju_leaf-1.2.2/lib/tasks/enju_leaf_tasks.rake:8:in `block (3 levels) in <top (required)>'
/Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/enju_leaf-1.2.2/lib/tasks/enju_leaf_tasks.rake:7:in `each'
/Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/enju_leaf-1.2.2/lib/tasks/enju_leaf_tasks.rake:7:in `block (2 levels) in <top (required)>'
/Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => enju_leaf:setup
(See full trace by running task with --trace)
        rake  enju_circulation:setup
The PGconn, PGresult, and PGError constants are deprecated, and will be
removed as of version 1.0.

You should use PG::Connection, PG::Result, and PG::Error instead, respectively.

Called from /Users/gm3752/app/your_enju/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
rake aborted!
ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column "increment_by" does not exist
LINE 1: ...ypes_id_seq"', (SELECT COALESCE(MAX("id")+(SELECT increment_...

```

**Comment by nakamura-akifumi** [comment]
Rails4.2.10ではPostgreSQL10.xに対応していないようです。
https://help.heroku.com/WKJ027JH/rails-error-after-upgrading-to-postgres-10

**Comment by nakamura-akifumi** [comment]
postgresql 10 をアンインストールし、postgresql 9.6で再インストールしたところ、問題なく出来ました。
9.6は以下のコマンドでインストールしました。

```
brew install postgresql@9.6
```

**Comment by masao** [comment]
ひとまずドキュメントを書いておくことにしましょう。

**Comment by nabeta** [comment]
WikiにPostgreSQLの対応バージョンが9.4〜9.6であること、1.2系がPostgreSQL 10.x非対応であることを記述しました。
https://github.com/next-l/enju_leaf/wiki/Install#必要なもの--requirement

**Comment by masao** [comment]
記述を確認しました。ひとまずクローズします。
