### ISSUE TITLE
rspec実行時に undefined method `users'  が発生する

### ISSUE THREAD

**Issue by nakamura-akifumi** [next-l/enju_leaf#1388]
rspec動作時のエラーについて教えてください。
先日ワークショップでrspecの設定をしていただきましたが、テストを実行すると以下のエラーが発生します。

      undefined method `users' for #

不足しているかと思うのですが、なにか心当たりありますでしょうか？

```
MAC-0043:enju_t84_self_checkout gm3752$ bundle exec rspec spec/controllers/id_card_import_files_controller_spec.rb 
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.
[Simple Form] Simple Form is not configured in the application and will use the default values. Use `rails generate simple_form:install` to generate the Simple Form configuration.
The PGconn, PGresult, and PGError constants are deprecated, and will be
removed as of version 1.0.

You should use PG::Connection, PG::Result, and PG::Error instead, respectively.

Called from /Users/gm3752/app/enju_t84_self_checkout/.bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
F

Failures:

  1) IdCardImportFilesController GET index When logged in as Administrator returns a success status codea
     Failure/Error: @user = users(:admin)
     
     NoMethodError:
       undefined method `users' for #<RSpec::ExampleGroups::IdCardImportFilesController::GETIndex::WhenLoggedInAsAdministrator:0x007f8376d20d88>
     # ./.bundle/ruby/2.3.0/gems/actionpack-4.2.10/lib/action_dispatch/testing/assertions/routing.rb:171:in `method_missing'
     # ./spec/support/controller_macros.rb:26:in `block in login_fixture_admin'

Finished in 0.02413 seconds (files took 5.58 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/controllers/id_card_import_files_controller_spec.rb:8 # IdCardImportFilesController GET index When logged in as Administrator returns a success status codea

[Coveralls] Outside the Travis environment, not sending data.
```

**Comment by nabeta** [comment]
@nakamura-akifumi フィクスチャは読み込んでいますか？ 以下の行になります。
https://github.com/next-l/enju_circulation/blob/master/spec/controllers/checked_items_controller_spec.rb#L4

**Comment by nabeta** [comment]
こちらは現状でCIが通っており、closeします。まだ不具合が出ているようでしたら別途お知らせください。
