### ISSUE TITLE
vagrant ですっぴんのOSから開発版1.3.1 をdevelopment環境でインストールしようとしたができない

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1421]
```sh
$ cd vagrantwork1108-1
$ vagrant init bento/ubuntu-16.04
$ vi Vagrantfile     

　　ポートフォーワーディングの設定をする

config.vm.network "forwarded_port", guest: 80, host: 8083  これの冒頭の#を消す
config.vm.network "forwarded_port", guest: 22, host: 2223   これを追加


　　メモリの設定

  config.vm.provider "virtualbox" do |vb|  これの冒頭の#を消す
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
    vb.memory = "2048"   1024 を2048に変える 
  end     これの冒頭の#を消す

$ vagrant up
$ vagrant ssh
$ sudo apt-get update
$ sudo apt-get install ruby ruby-dev
$ sudo apt-get install imagemagick libicu-dev zlib1g-dev unzip \
 openjdk-8-jre-headless git libxslt1-dev build-essential nodejs redis-server
$ sudo apt-get install postgresql libpq-dev
$ ruby -v
$ sudo gem install rails -v=5.1.6
$ sudo gem install foreman whenever
$ rails _5.1.6_ new your_enju -d postgresql --skip-bundle --skip-turbolinks \
 -m https://gist.github.com/nabeta/04a59bff6620a85e8ebb323bb31f5ec6.txt 
$ cd your_enju
$ bundle -j4 --path vendor/bundle
# homebrewのバージョンが0.9以降でnokogiriのインストールがエラーになる場合、http://nokogiri.org/tutorials/installing_nokogiri.html を参照し、手動でlibiconvをインストールしておく必要がある。wgetが使えない場合は、curl -Oに置き換えて行う。
$ bundle install
$ sudo su postgres -c 'createuser vagrant --interactive' # -p yourpassword
Shall the new role be a superuser? (y/n) n
Shall the new role be allowed to create databases? (y/n) y
Shall the new role be allowed to create more new roles? (y/n) y

$ vi config/database.yml
・・・
省略
・・・

development:
  <<: *default
  database: your_enju_development
  username: vagrant **# この行を追加**
  password: <%= ENV['YOUR_ENJU_DATABASE_PASSWORD'] %> **#この行を追加**

$ bundle exec rake db:create:all
Created database 'your_enju_development'
Created database 'your_enju_test'
FATAL:  Peer authentication failed for user "your_enju"
Couldn't create database for {"adapter"=>"postgresql", "encoding"=>"unicode", "pool"=>5, "database"=>"your_enju_production", "username"=>"your_enju", "password"=>nil}
rake aborted!
PG::ConnectionBad: FATAL:  Peer authentication failed for user "your_enju"
/home/vagrant/your_enju/vendor/bundle/ruby/2.3.0/gems/pg-1.1.3/lib/pg.rb:56:in `initialize'
/home/vagrant/your_enju/vendor/bundle/ruby/2.3.0/gems/pg-1.1.3/lib/pg.rb:56:in `new'
/home/vagrant/your_enju/vendor/bundle/ruby/2.3.0/gems/pg-1.1.3/lib/pg.rb:56:in `connect'
/home/vagrant/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/postgresql_adapter.rb:697:in `connect'
/home/vagrant/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/postgresql_adapter.rb:221:in `initialize'
/home/vagrant/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/postgresql_adapter.rb:38:in `new'
/home/vagrant/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/postgresql_adapter.rb:38:in `postgresql_connection'
/home/vagrant/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:759:in `new_connection'
/home/vagrant/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:803:in `checkout_new_connection'
/home/vagrant/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:782:in `try_to_checkout_new_connection'
/home/vagrant/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:743:in `acquire_connection'
/home/vagrant/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:500:in `checkout'
/home/vagrant/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:374:in `connection'
/home/vagrant/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `retrieve_connection'
/home/vagrant/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.6/lib/active_record/connection_handling.rb:116:in `retrieve_connection'
/home/vagrant/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.6/lib/active_record/connection_handling.rb:88:in `connection'
/home/vagrant/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.6/lib/active_record/tasks/postgresql_database_tasks.rb:10:in `connection'
/home/vagrant/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.6/lib/active_record/tasks/postgresql_database_tasks.rb:19:in `create'
/home/vagrant/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.6/lib/active_record/tasks/database_tasks.rb:117:in `create'
/home/vagrant/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.6/lib/active_record/tasks/database_tasks.rb:129:in `block in create_all'
/home/vagrant/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.6/lib/active_record/tasks/database_tasks.rb:314:in `block in each_local_configuration'
/home/vagrant/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.6/lib/active_record/tasks/database_tasks.rb:310:in `each_value'
/home/vagrant/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.6/lib/active_record/tasks/database_tasks.rb:310:in `each_local_configuration'
/home/vagrant/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.6/lib/active_record/tasks/database_tasks.rb:129:in `create_all'
/home/vagrant/your_enju/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.6/lib/active_record/railties/databases.rake:21:in `block (3 levels) in <top (required)>'
/home/vagrant/your_enju/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:create:all
(See full trace by running task with --trace)
vagrant@vagrant:~/your_enju$ 
```

**Comment by yegusa** [comment]
1.3.1の確認がしたいので、解決方法を教えてください。

**Comment by yegusa** [comment]
自己解決しました。のでクローズします。

```yml
production:
  <<: *default
  database: your_enju_production
#  username: your_enju # この行の冒頭に#を入れました
#  password: <%= ENV['YOUR_ENJU_DATABASE_PASSWORD'] %> # この行の冒頭に#を入れました
```
