### ISSUE TITLE
所蔵一覧ページでNoMethodErrorが発生する

### ISSUE THREAD

**Issue by upsilon** [next-l/enju_leaf#1462]
https://github.com/next-l/enju_leaf/wiki/Install の手順に従ってリリース版のインストールを行うと、所蔵一覧 (`/items?manifestation_id=:id`) で以下のエラーが発生します。

```
F, [2019-06-05T00:40:08.450403 #6] FATAL -- : [972e69b8-0685-425b-aee4-8e12170cfa85] NoMethodError (undefined method `get_inventory_file' for #<ItemsController:0x000055a49a535518>):
F, [2019-06-05T00:40:08.450478 #6] FATAL -- : [972e69b8-0685-425b-aee4-8e12170cfa85]
F, [2019-06-05T00:40:08.450566 #6] FATAL -- : [972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:413:in `block in make_lambda'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:197:in `block (2 levels) in halting'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/abstract_controller/callbacks.rb:12:in `block (2 levels) in <module:Callbacks>'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:198:in `block in halting'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:507:in `block in invoke_before'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:507:in `each'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:507:in `invoke_before'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:130:in `run_callbacks'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/abstract_controller/callbacks.rb:19:in `process_action'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_controller/metal/rescue.rb:20:in `process_action'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/notifications.rb:166:in `block in instrument'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/notifications.rb:166:in `instrument'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/activerecord-5.1.7/lib/active_record/railties/controller_runtime.rb:22:in `process_action'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/abstract_controller/base.rb:124:in `process'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/actionview-5.1.7/lib/action_view/rendering.rb:30:in `process'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_controller/metal.rb:189:in `dispatch'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_controller/metal.rb:253:in `dispatch'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_dispatch/routing/route_set.rb:31:in `serve'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_dispatch/journey/router.rb:50:in `block in serve'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_dispatch/journey/router.rb:33:in `each'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_dispatch/journey/router.rb:33:in `serve'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_dispatch/routing/route_set.rb:844:in `call'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/fix_microsoft_links-0.1.6/lib/fix_microsoft_links.rb:18:in `call'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/warden-1.2.8/lib/warden/manager.rb:36:in `block in call'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/warden-1.2.8/lib/warden/manager.rb:34:in `catch'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/warden-1.2.8/lib/warden/manager.rb:34:in `call'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/etag.rb:25:in `call'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/conditional_get.rb:25:in `call'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/head.rb:12:in `call'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:232:in `context'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:226:in `call'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/cookies.rb:613:in `call'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:97:in `run_callbacks'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/callbacks.rb:24:in `call'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/railties-5.1.7/lib/rails/rack/logger.rb:36:in `call_app'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `block in call'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `block in tagged'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:26:in `tagged'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `tagged'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `call'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/request_store-1.4.1/lib/request_store/middleware.rb:19:in `call'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/request_id.rb:25:in `call'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/method_override.rb:22:in `call'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/runtime.rb:22:in `call'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/executor.rb:12:in `call'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/static.rb:125:in `call'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/sendfile.rb:111:in `call'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/railties-5.1.7/lib/rails/engine.rb:522:in `call'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/puma-3.12.1/lib/puma/configuration.rb:227:in `call'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/puma-3.12.1/lib/puma/server.rb:660:in `handle_request'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/puma-3.12.1/lib/puma/server.rb:474:in `process_client'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/puma-3.12.1/lib/puma/server.rb:334:in `block in run'
[972e69b8-0685-425b-aee4-8e12170cfa85] vendor/bundle/ruby/2.6.0/gems/puma-3.12.1/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```

インストール後に `app/controllers/application_controller.rb` に以下の行を追加することで、所蔵一覧については表示できる状態になります。
```rb
  include EnjuInventory::Controller
```
ただし、inventories テーブル等が作成されていないため蔵書点検 (`/inventory_files`) などのページは依然としてエラーのままです。

**Comment by nabeta** [comment]
お知らせありがとうございます。ドキュメントが追いついていないので、Gemfile側でenju_inventoryを無効とし、
https://gist.github.com/nabeta/6c56f0edf5cc1c80d9c655c2660a9c59

いったん``app/controllers/application_controller.rb`` の変更を元に戻していただけますでしょうか。

**Comment by upsilon** [comment]
enju_inventory を無効にした状態で所蔵一覧が正常に表示できることを確認しました。ありがとうございます🙇
