### ISSUE TITLE
資料の出版者と識別子を一度に変更するとHTTP 409エラーが発生

### ISSUE THREAD

**Issue by upsilon** [next-l/enju_leaf#1463]
資料編集 (`/manifestations/:id/edit`) で「出版者」と「識別子」を一度に変更すると HTTP 409 (Conflict) エラーが発生します

- rails: 5.1.7
- enju_leaf: 1.3.2
- enju_biblio: 0.3.2

```
I, [2019-06-06T03:50:32.375813 #6]  INFO -- : [f34bcdeb-98c2-490a-8ed0-cf210e17c620] Completed 409 Conflict in 18136ms (ActiveRecord: 1616.0ms)
F, [2019-06-06T03:50:32.382532 #6] FATAL -- : [f34bcdeb-98c2-490a-8ed0-cf210e17c620]
F, [2019-06-06T03:50:32.382623 #6] FATAL -- : [f34bcdeb-98c2-490a-8ed0-cf210e17c620] ActiveRecord::StaleObjectError (Attempted to touch a stale object: Manifestation.):
F, [2019-06-06T03:50:32.382680 #6] FATAL -- : [f34bcdeb-98c2-490a-8ed0-cf210e17c620]
F, [2019-06-06T03:50:32.382815 #6] FATAL -- : [f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activerecord-5.1.7/lib/active_record/locking/optimistic.rb:95:in `_update_row'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activerecord-5.1.7/lib/active_record/persistence.rb:542:in `_touch_row'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activerecord-5.1.7/lib/active_record/locking/optimistic.rb:73:in `_touch_row'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activerecord-5.1.7/lib/active_record/persistence.rb:513:in `touch'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activerecord-5.1.7/lib/active_record/callbacks.rb:330:in `block in touch'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:131:in `run_callbacks'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:827:in `_run_touch_callbacks'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activerecord-5.1.7/lib/active_record/callbacks.rb:330:in `touch'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activerecord-5.1.7/lib/active_record/transactions.rb:317:in `block in touch'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activerecord-5.1.7/lib/active_record/transactions.rb:384:in `block in with_transaction_returning_status'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract/database_statements.rb:233:in `transaction'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activerecord-5.1.7/lib/active_record/transactions.rb:210:in `transaction'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activerecord-5.1.7/lib/active_record/transactions.rb:381:in `with_transaction_returning_status'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activerecord-5.1.7/lib/active_record/transactions.rb:317:in `touch'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activerecord-5.1.7/lib/active_record/touch_later.rb:37:in `touch'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activerecord-5.1.7/lib/active_record/no_touching.rb:53:in `touch'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activerecord-5.1.7/lib/active_record/touch_later.rb:49:in `touch_deferred_attributes'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:413:in `block in make_lambda'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:197:in `block (2 levels) in halting'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:601:in `block (2 levels) in default_terminator'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:600:in `catch'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:600:in `block in default_terminator'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:198:in `block in halting'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:507:in `block in invoke_before'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:507:in `each'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:507:in `invoke_before'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:130:in `run_callbacks'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:827:in `_run_before_commit_without_transaction_enrollment_callbacks'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activerecord-5.1.7/lib/active_record/transactions.rb:332:in `before_committed!'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract/transaction.rb:79:in `each'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract/transaction.rb:79:in `before_commit_records'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract/transaction.rb:172:in `block in commit_transaction'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] /usr/local/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract/transaction.rb:168:in `commit_transaction'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract/transaction.rb:207:in `block in within_new_transaction'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] /usr/local/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activerecord-5.1.7/lib/active_record/transactions.rb:210:in `transaction'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/enju_biblio-0.3.2/app/controllers/manifestations_controller.rb:432:in `update'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/abstract_controller/base.rb:186:in `process_action'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_controller/metal/rendering.rb:30:in `process_action'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:131:in `run_callbacks'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/abstract_controller/callbacks.rb:19:in `process_action'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_controller/metal/rescue.rb:20:in `process_action'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/notifications.rb:166:in `block in instrument'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/notifications.rb:166:in `instrument'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activerecord-5.1.7/lib/active_record/railties/controller_runtime.rb:22:in `process_action'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/abstract_controller/base.rb:124:in `process'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/actionview-5.1.7/lib/action_view/rendering.rb:30:in `process'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_controller/metal.rb:189:in `dispatch'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_controller/metal.rb:253:in `dispatch'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_dispatch/routing/route_set.rb:31:in `serve'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_dispatch/journey/router.rb:50:in `block in serve'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_dispatch/journey/router.rb:33:in `each'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_dispatch/journey/router.rb:33:in `serve'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_dispatch/routing/route_set.rb:844:in `call'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/fix_microsoft_links-0.1.6/lib/fix_microsoft_links.rb:18:in `call'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/warden-1.2.8/lib/warden/manager.rb:36:in `block in call'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/warden-1.2.8/lib/warden/manager.rb:34:in `catch'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/warden-1.2.8/lib/warden/manager.rb:34:in `call'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/etag.rb:25:in `call'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/conditional_get.rb:38:in `call'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/head.rb:12:in `call'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:232:in `context'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:226:in `call'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/cookies.rb:613:in `call'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:97:in `run_callbacks'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/callbacks.rb:24:in `call'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/railties-5.1.7/lib/rails/rack/logger.rb:36:in `call_app'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `block in call'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `block in tagged'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:26:in `tagged'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `tagged'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `call'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/request_store-1.4.1/lib/request_store/middleware.rb:19:in `call'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/request_id.rb:25:in `call'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/method_override.rb:22:in `call'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/runtime.rb:22:in `call'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/executor.rb:12:in `call'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/static.rb:125:in `call'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/sendfile.rb:111:in `call'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/railties-5.1.7/lib/rails/engine.rb:522:in `call'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/puma-3.12.1/lib/puma/configuration.rb:227:in `call'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/puma-3.12.1/lib/puma/server.rb:660:in `handle_request'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/puma-3.12.1/lib/puma/server.rb:474:in `process_client'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/puma-3.12.1/lib/puma/server.rb:334:in `block in run'
[f34bcdeb-98c2-490a-8ed0-cf210e17c620] vendor/bundle/ruby/2.6.0/gems/puma-3.12.1/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```

**Comment by nabeta** [comment]
@upsilon 遅くなりましたが、上記の問題の修正をenju_biblio-0.3.6としてリリースしました。以下の手順で更新します。

```sh
$ bundle update enju_biblio
```

2.x系にも取り込み済みです。

**Comment by masao** [comment]
挙動を確認しました。
一応、同様の操作をしたところではエラーなく動作しているようです。ひとまずクローズします。
![enju_issue1463](https://user-images.githubusercontent.com/38825/74598134-2ea0a400-50af-11ea-9029-40d5ec376f91.png)
