### ISSUE TITLE
include Statesman::Adapters::ActiveRecordQueriesでのエラー

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#1493]
statesmanを使用しているモジュールのテストで、以下のエラーが出る。

```
An error occurred while loading ./spec/models/agent_import_file_spec.rb.
Failure/Error: include Statesman::Adapters::ActiveRecordQueries

NoMethodError:
  undefined method `transition_class' for #<Class:0x000055a993382858>
  Did you mean?  translates
# ./app/models/agent_import_file.rb:2:in `include'
# ./app/models/agent_import_file.rb:2:in `<class:AgentImportFile>'
# ./app/models/agent_import_file.rb:1:in `<top (required)>'
# ./spec/models/agent_import_file_spec.rb:3:in `<top (required)>'
```

**Comment by nabeta** [comment]
これはstatesman-4.1.3で互換性のない変更が導入されたためで、4.1.4で修正されている。enju_leaf-1.3系はこちらを使用する。
https://github.com/gocardless/statesman/releases/tag/v4.1.4

変更後のものは5.0としてリリースされている。2.x系はこちらを使用する。
https://github.com/gocardless/statesman/releases/tag/v5.0.0

**Comment by nabeta** [comment]
各モジュールとも現時点では修正済みなのでcloseする。
