### ISSUE TITLE
画面遷移の不具合（VirtualBox版）

### ISSUE THREAD

**Issue by miyatatk** [next-l/enju_leaf#1510]
Next-L Enjuのコンセプトの壮大さに共感し、自宅の蔵書管理システムを作るため、まずはVirtualBox版をインストールして使っています。

さて、書誌情報と所蔵情報を登録し、資料の検索結果一覧画面（/manifestations）で資料名のリンク（/manifestations/xxx）をクリックすると、本来は資料の個別ページが表示されるはずですが、エラーメッセージ（We're sorry, but something went wrong. If you are the application owner check the logs for more information.）が表示されます。

しかし、ログアウトして（Guestの権限で）URLをクリックすると、正しく個別ページが表示されます。所蔵情報の個別ページ（/items/xxx）でも同じ現象が発生します。

回避方法があればご教示ください。よろしくお願いいたします。

**Comment by nabeta** [comment]
@miyatatk お知らせありがとうございます。
手元の環境でVirtualBoxの仮想マシンを動かして試したのですが、再現できません。
``/home/enju/logs/production.log``に出ているエラーを教えていただけますでしょうか。

**Comment by miyatatk** [comment]
@nabeta お返事ありがとうございます。ログレベルを `config.log_level = :error` に設定した場合、ログファイルは以下のようになります。

**システム起動**
```
E, [2020-05-10T10:41:17.855903 #789] ERROR -- : [__GUID_1__]   Couldn't find template for digesting: manifestations/show_tag
E, [2020-05-10T10:42:14.176279 #789] ERROR -- : [__GUID_2__]   Couldn't find template for digesting: manifestations/show_tag
```
**ここで 資料の表示 (/manifestations/xxx) へのリンクをクリック**
```
E, [2020-05-10T10:43:45.197428 #789] ERROR -- : [__GUID_3__]   Couldn't find template for digesting: manifestations/tag_list
E, [2020-05-10T10:43:45.258371 #789] ERROR -- : [__GUID_3__]   Couldn't find template for digesting: manifestations/question_list
F, [2020-05-10T10:43:45.417118 #789] FATAL -- : [__GUID_3__]   
F, [2020-05-10T10:43:45.417185 #789] FATAL -- : [__GUID_3__] ActionView::Template::Error (undefined method `memo' for #<Manifestation:0x00007f4828f79820>):
F, [2020-05-10T10:43:45.417297 #789] FATAL -- : [__GUID_3__]     103:         </tr>
[__GUID_3__]     104:         <tr>
[__GUID_3__]     105:           <td><%= t('activerecord.attributes.manifestation.note') -%>:</td>
[__GUID_3__]     106:           <td>
[__GUID_3__]     107:             <%= raw simple_format(h(manifestation.note)) -%>
[__GUID_3__]     108:           </td>
[__GUID_3__]     109:         </tr>
F, [2020-05-10T10:43:45.417322 #789] FATAL -- : [__GUID_3__]   
F, [2020-05-10T10:43:45.417368 #789] FATAL -- : [__GUID_3__] vendor/bundle/ruby/2.5.0/gems/activemodel-5.2.4.2/lib/active_model/attribute_methods.rb:430:in `method_missing'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/enju_biblio-0.3.9/app/views/manifestations/_show_detail_librarian.html.erb:106:in `block in _vendor_bundle_ruby_______gems_enju_biblio_______app_views_manifestations__show_detail_librarian_html_erb___1268335781481044825_69973951070520'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/helpers/cache_helper.rb:253:in `write_fragment_for'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/helpers/cache_helper.rb:243:in `fragment_for'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/helpers/cache_helper.rb:169:in `cache'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/enju_biblio-0.3.9/app/views/manifestations/_show_detail_librarian.html.erb:4:in `_vendor_bundle_ruby_______gems_enju_biblio_______app_views_manifestations__show_detail_librarian_html_erb___1268335781481044825_69973951070520'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/template.rb:159:in `block in render'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/notifications.rb:170:in `instrument'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/template.rb:354:in `instrument_render_template'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/template.rb:157:in `render'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/renderer/partial_renderer.rb:344:in `block in render_partial'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/renderer/abstract_renderer.rb:44:in `block in instrument'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/notifications.rb:168:in `block in instrument'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/notifications.rb:168:in `instrument'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/renderer/abstract_renderer.rb:43:in `instrument'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/renderer/partial_renderer.rb:333:in `render_partial'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/renderer/partial_renderer.rb:312:in `render'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/renderer/renderer.rb:49:in `render_partial'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/helpers/rendering_helper.rb:36:in `render'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/enju_biblio-0.3.9/app/views/manifestations/show.html.erb:11:in `_vendor_bundle_ruby_______gems_enju_biblio_______app_views_manifestations_show_html_erb___786184230760016934_69973950912380'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/template.rb:159:in `block in render'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/notifications.rb:170:in `instrument'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/template.rb:354:in `instrument_render_template'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/template.rb:157:in `render'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/renderer/abstract_renderer.rb:44:in `block in instrument'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/notifications.rb:168:in `block in instrument'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/notifications.rb:168:in `instrument'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/renderer/abstract_renderer.rb:43:in `instrument'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/renderer/template_renderer.rb:16:in `render'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/renderer/renderer.rb:44:in `render_template'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/renderer/renderer.rb:25:in `render'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/rendering.rb:103:in `_render_template'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal/streaming.rb:219:in `_render_template'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/rendering.rb:84:in `render_to_body'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal/renderers.rb:142:in `render_to_body'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/abstract_controller/rendering.rb:25:in `render'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal/rendering.rb:36:in `render'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal/instrumentation.rb:46:in `block (2 levels) in render'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/core_ext/benchmark.rb:14:in `block in ms'
[__GUID_3__] /usr/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/core_ext/benchmark.rb:14:in `ms'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal/instrumentation.rb:46:in `block in render'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/railties/controller_runtime.rb:36:in `cleanup_view_runtime'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/sunspot_rails-2.5.0/lib/sunspot/rails/railties/controller_runtime.rb:15:in `cleanup_view_runtime'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal/instrumentation.rb:45:in `render'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal/implicit_render.rb:35:in `default_render'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal/basic_implicit_render.rb:6:in `block in send_action'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal/basic_implicit_render.rb:6:in `tap'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/abstract_controller/base.rb:194:in `process_action'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal/rendering.rb:30:in `process_action'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:132:in `run_callbacks'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/abstract_controller/callbacks.rb:41:in `process_action'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal/rescue.rb:22:in `process_action'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/notifications.rb:168:in `block in instrument'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/notifications.rb:168:in `instrument'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/abstract_controller/base.rb:134:in `process'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/rendering.rb:32:in `process'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal.rb:191:in `dispatch'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal.rb:252:in `dispatch'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/routing/route_set.rb:34:in `serve'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/journey/router.rb:52:in `block in serve'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/journey/router.rb:35:in `each'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/journey/router.rb:35:in `serve'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/routing/route_set.rb:840:in `call'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/fix_microsoft_links-0.1.6/lib/fix_microsoft_links.rb:18:in `call'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/warden-1.2.8/lib/warden/manager.rb:36:in `block in call'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/warden-1.2.8/lib/warden/manager.rb:34:in `catch'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/warden-1.2.8/lib/warden/manager.rb:34:in `call'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/tempfile_reaper.rb:15:in `call'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/etag.rb:27:in `call'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/conditional_get.rb:27:in `call'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/head.rb:12:in `call'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/session/abstract/id.rb:266:in `context'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/session/abstract/id.rb:260:in `call'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/cookies.rb:670:in `call'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:98:in `run_callbacks'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.2/lib/rails/rack/logger.rb:38:in `call_app'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.2/lib/rails/rack/logger.rb:26:in `block in call'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/tagged_logging.rb:71:in `block in tagged'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/tagged_logging.rb:28:in `tagged'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/tagged_logging.rb:71:in `tagged'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.2/lib/rails/rack/logger.rb:26:in `call'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/request_id.rb:27:in `call'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/method_override.rb:24:in `call'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/runtime.rb:22:in `call'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/executor.rb:14:in `call'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/sendfile.rb:110:in `call'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:524:in `call'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/puma-3.12.4/lib/puma/configuration.rb:227:in `call'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/puma-3.12.4/lib/puma/server.rb:675:in `handle_request'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/puma-3.12.4/lib/puma/server.rb:476:in `process_client'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/puma-3.12.4/lib/puma/server.rb:334:in `block in run'
[__GUID_3__] vendor/bundle/ruby/2.5.0/gems/puma-3.12.4/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```
また、ここでログアウトして（Guestの権限で）URLをクリックすると、正しく「資料の表示」画面が表示され、ログファイルは以下のようになります。
```
E, [2020-05-10T11:51:56.334673 #789] ERROR -- : [__GUID_4__]   Couldn't find template for digesting: manifestations/tag_list
E, [2020-05-10T11:51:56.376623 #789] ERROR -- : [__GUID_4__]   Couldn't find template for digesting: manifestations/question_list
```
よろしくお願いいたします。

**Comment by miyatatk** [comment]
なお、このエラーは[インストールマニュアル](https://next-l.github.io/manual/1.3/enju_install_vm_8.html#section8-2)に従って、 `bundle update` を行ってから発生するようになったと記憶しています。

よって、怖いので（笑）ソースコード版では `bundle update` を行わないようにしています。

**Comment by nabeta** [comment]
Gemfileの``enju_biblio``の行を、以下のように変更して、``bundle update``を実行していただけますでしょうか。これは仮想マシン作成時のバージョンのものです。

```
gem 'enju_biblio', '0.3.5'
```

**Comment by miyatatk** [comment]
@nabeta お返事ありがとうございます。もともと Gemfile に `enju_biblio` の記載がないため、
```
gem 'enju_biblio', '0.3.5'
```
の行を追記し、 `bundle update` を行いました。これにより、0.3.9 から 0.3.5 にバージョンダウンしました。再起動したところ、上記の不具合は解消しました。ご指導ありがとうございました。

なお、現在でも以下のエラーログは残っています。
```
E, [2020-05-10T13:29:13.404300 #771] ERROR -- : [__GUID_1__]   Couldn't find template for digesting: manifestations/tag_list
E, [2020-05-10T13:29:13.448179 #771] ERROR -- : [__GUID_1__]   Couldn't find template for digesting: manifestations/question_list
```

**Comment by nabeta** [comment]
@miyatatk 古いissueへの回答で申し訳ありません。根本的な原因として、`manifestations`テーブルに`memo`カラムがないようなので、Gemfileを以下のように編集後、

```ruby
gem 'enju_leaf', '~> 1.3.6'
gem 'enju_biblio'
```

以下のコマンドを実行してください。

```sh
$ bundle install
$ bundle exec rake enju_biblio_engine:install:migrations 
$ bundle exec rake db:migrate RAILS_ENV=production
```

**Comment by nabeta** [comment]
古いイシューのため、クローズします。
