### ISSUE TITLE
画像ファイルの一覧が表示されない（VirtualBox版）

### ISSUE THREAD

**Issue by miyatatk** [next-l/enju_leaf#1513]
VirtualBox版での不具合です。

**図書館の管理** → **システムの設定** → **資料** → **画像ファイル** と辿ると、**画像ファイルの一覧** (/picture_files) という画面が表示されます。ソースコード版では問題なく表示されています。

しかし、VirtualBox版ではこの画面が表示されず、以下のエラーメッセージが出ます。
```
We're sorry, but something went wrong.
If you are the application owner check the logs for more information.
```
その際のログ `log/production.log` は以下のとおりです。
```
F, [2020-05-12T00:53:18.414456 #2316] FATAL -- : [__GUID_1__]   
F, [2020-05-12T00:53:18.424315 #2316] FATAL -- : [__GUID_1__] NameError (undefined local variable or method `get_event' for #<PictureFilesController:0x00007f7e48c7ccc0>
Did you mean?  get_agent):
F, [2020-05-12T00:53:18.424365 #2316] FATAL -- : [__GUID_1__]   
F, [2020-05-12T00:53:18.424403 #2316] FATAL -- : [__GUID_1__] vendor/bundle/ruby/2.5.0/gems/enju_biblio-0.3.5/app/controllers/picture_files_controller.rb:188:in `get_attachable'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:426:in `block in make_lambda'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:179:in `block (2 levels) in halting_and_conditional'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:180:in `block in halting_and_conditional'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:513:in `block in invoke_before'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:513:in `each'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:513:in `invoke_before'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:131:in `run_callbacks'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/abstract_controller/callbacks.rb:41:in `process_action'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal/rescue.rb:22:in `process_action'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/notifications.rb:168:in `block in instrument'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/notifications.rb:168:in `instrument'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/abstract_controller/base.rb:134:in `process'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/rendering.rb:32:in `process'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal.rb:191:in `dispatch'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal.rb:252:in `dispatch'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/routing/route_set.rb:34:in `serve'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/journey/router.rb:52:in `block in serve'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/journey/router.rb:35:in `each'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/journey/router.rb:35:in `serve'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/routing/route_set.rb:840:in `call'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/fix_microsoft_links-0.1.6/lib/fix_microsoft_links.rb:18:in `call'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/warden-1.2.8/lib/warden/manager.rb:36:in `block in call'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/warden-1.2.8/lib/warden/manager.rb:34:in `catch'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/warden-1.2.8/lib/warden/manager.rb:34:in `call'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/tempfile_reaper.rb:15:in `call'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/etag.rb:27:in `call'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/conditional_get.rb:27:in `call'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/head.rb:12:in `call'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/session/abstract/id.rb:266:in `context'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/session/abstract/id.rb:260:in `call'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/cookies.rb:670:in `call'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:98:in `run_callbacks'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.2/lib/rails/rack/logger.rb:38:in `call_app'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.2/lib/rails/rack/logger.rb:26:in `block in call'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/tagged_logging.rb:71:in `block in tagged'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/tagged_logging.rb:28:in `tagged'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/tagged_logging.rb:71:in `tagged'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.2/lib/rails/rack/logger.rb:26:in `call'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/request_id.rb:27:in `call'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/method_override.rb:24:in `call'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/runtime.rb:22:in `call'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/executor.rb:14:in `call'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/sendfile.rb:110:in `call'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:524:in `call'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/puma-3.12.4/lib/puma/configuration.rb:227:in `call'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/puma-3.12.4/lib/puma/server.rb:675:in `handle_request'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/puma-3.12.4/lib/puma/server.rb:476:in `process_client'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/puma-3.12.4/lib/puma/server.rb:334:in `block in run'
[__GUID_1__] vendor/bundle/ruby/2.5.0/gems/puma-3.12.4/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```
回避方法がお分かりになりましたらご教示ください。よろしくお願いいたします。

**Comment by nabeta** [comment]
@miyatatk 古いissueへの回答で申し訳ありません。仮想マシンにログイン後、以下のコマンドを実行して、アプリケーションを再起動してください。

```sh
$ cd enju
$ bundle update enju_biblio
```

なお、1.4.0より、アプリケーションの配布はDockerのみで行う予定であり、VirtualBoxの仮想マシンのリリースは行わない予定です。

**Comment by nabeta** [comment]
古いイシューのため、クローズします。
