### ISSUE TITLE
2.0系インストールエラー

### ISSUE THREAD

**Issue by miyatatk** [next-l/enju_leaf#1527]
@nabeta お世話になっております。2.0系を試してみようと思い、インストールマニュアルに従って進みました。

「Enju Leaf本体のインストール」を無事終了し、[PostgreSQLの設定](https://github.com/next-l/enju_leaf/wiki/Install#postgresql%E3%81%AE%E8%A8%AD%E5%AE%9A)の終わりの「データベースを作成します。」の操作を行ったところ、下記のようなSyntax Errorが出て中断してしまいました。

原因がお分かりになりましたらご教示ください。
```
$ cd ~/enju_leaf_20
$ bundle exec rake db:create:all
rake aborted!
SyntaxError: ~/enju_leaf_20/vendor/bundle/ruby/2.5.0/bundler/gems/enju_inventory-ba7c7332b30b/lib/tasks/enju_inventory_tasks.rake:62: syntax error, unexpected >>, expecting keyword_end
>>>>>>> aa9f7a5... add missing_...
^~
~/enju_leaf_20/vendor/bundle/ruby/2.5.0/bundler/gems/enju_inventory-ba7c7332b30b/lib/tasks/enju_inventory_tasks.rake:62: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
...>> aa9f7a5... add missing_since to Item
...                  ^~~~~~~~~~~~~
~/enju_leaf_20/vendor/bundle/ruby/2.5.0/bundler/gems/enju_inventory-ba7c7332b30b/lib/tasks/enju_inventory_tasks.rake:64: syntax error, unexpected keyword_end, expecting end-of-input
~/enju_leaf_20/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
~/enju_leaf_20/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
~/enju_leaf_20/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:285:in `block in load'
~/enju_leaf_20/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
~/enju_leaf_20/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:285:in `load'
~/enju_leaf_20/vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.4/lib/rails/engine.rb:656:in `block in run_tasks_blocks'
~/enju_leaf_20/vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.4/lib/rails/engine.rb:656:in `each'
~/enju_leaf_20/vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.4/lib/rails/engine.rb:656:in `run_tasks_blocks'
~/enju_leaf_20/vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.4/lib/rails/application.rb:514:in `block in run_tasks_blocks'
~/enju_leaf_20/vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.4/lib/rails/engine/railties.rb:15:in `each'
~/enju_leaf_20/vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.4/lib/rails/engine/railties.rb:15:in `each'
~/enju_leaf_20/vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.4/lib/rails/application.rb:514:in `run_tasks_blocks'
~/enju_leaf_20/vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.4/lib/rails/engine.rb:459:in `load_tasks'
~/enju_leaf_20/Rakefile:6:in `<top (required)>'
~/enju_leaf_20/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by nabeta** [comment]
お知らせありがとうございます。この部分は修正しましたが、しばらく2.x系は手を入れていないので、最近の環境で動作できるかどうか確認してみます。

**Comment by miyatatk** [comment]
@nabeta お世話になっております。修正ありがとうございます。しかし、まだエラーしますね。

2.x系は動いていないのですか。急ぎませんので、ご対応よろしくお願いいたします。

```
$ cd ~/enju_leaf_20 
$ bundle exec rake db:create:all
[Simple Form] Simple Form is not configured in the application and will use the default values. Use `rails generate simple_form:install` to generate the Simple Form configuration.
Created database 'enju_leaf_20_development'
Created database 'enju_leaf_20_test'
FATAL:  ユーザ "enju_leaf_20" で対向(peer)認証に失敗しました
Couldn't create 'enju_leaf_20_production' database. Please check your configuration.
rake aborted!
PG::ConnectionBad: FATAL:  ユーザ "enju_leaf_20" で対向(peer)認証に失敗しました
~/enju_leaf_20/vendor/bundle/ruby/2.5.0/gems/pg-1.2.3/lib/pg.rb:58:in `initialize'
~/enju_leaf_20/vendor/bundle/ruby/2.5.0/gems/pg-1.2.3/lib/pg.rb:58:in `new'
~/enju_leaf_20/vendor/bundle/ruby/2.5.0/gems/pg-1.2.3/lib/pg.rb:58:in `connect'
~/enju_leaf_20/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/postgresql_adapter.rb:692:in `connect'
~/enju_leaf_20/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/postgresql_adapter.rb:223:in `initialize'
~/enju_leaf_20/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `new'
~/enju_leaf_20/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `postgresql_connection'
~/enju_leaf_20/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:830:in `new_connection'
~/enju_leaf_20/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:874:in `checkout_new_connection'
~/enju_leaf_20/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:853:in `try_to_checkout_new_connection'
~/enju_leaf_20/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:814:in `acquire_connection'
~/enju_leaf_20/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:538:in `checkout'
~/enju_leaf_20/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:382:in `connection'
~/enju_leaf_20/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:1033:in `retrieve_connection'
~/enju_leaf_20/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/connection_handling.rb:118:in `retrieve_connection'
~/enju_leaf_20/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/connection_handling.rb:90:in `connection'
~/enju_leaf_20/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/tasks/postgresql_database_tasks.rb:12:in `connection'
~/enju_leaf_20/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/tasks/postgresql_database_tasks.rb:21:in `create'
~/enju_leaf_20/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/tasks/database_tasks.rb:119:in `create'
~/enju_leaf_20/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/tasks/database_tasks.rb:131:in `block in create_all'
~/enju_leaf_20/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/tasks/database_tasks.rb:325:in `block in each_local_configuration'
~/enju_leaf_20/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/tasks/database_tasks.rb:321:in `each_value'
~/enju_leaf_20/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/tasks/database_tasks.rb:321:in `each_local_configuration'
~/enju_leaf_20/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/tasks/database_tasks.rb:131:in `create_all'
~/enju_leaf_20/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/railties/databases.rake:23:in `block (3 levels) in <top (required)>'
~/enju_leaf_20/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:create:all
(See full trace by running task with --trace)
```

**Comment by miyatatk** [comment]
@nabeta ご対応ありがとうございます。無事インストールできました。しかし起動してみると、

We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

というエラーが出てEnjuが表示されません。

**Comment by nabeta** [comment]
2.0系の開発とリリースは仕切り直しとするため、クローズします。
