### ISSUE TITLE
uninitialized constant UsersController

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1593]
1.4系にて、ログインメニューが動作しない。

![image](https://user-images.githubusercontent.com/38825/156870564-2a3b4763-a05c-49d4-a996-483975ea7b18.png)

**Comment by masao** [comment]
```
[actionpack (6.1.4.6) lib/action_dispatch/http/request.rb:96:in `rescue in controller_class_for'](http://localhost:3000/users/sign_in#)
[actionpack (6.1.4.6) lib/action_dispatch/http/request.rb:92:in `controller_class_for'](http://localhost:3000/users/sign_in#)
[actionpack (6.1.4.6) lib/action_dispatch/http/request.rb:85:in `controller_class'](http://localhost:3000/users/sign_in#)
[actionpack (6.1.4.6) lib/action_dispatch/routing/route_set.rb:44:in `controller'](http://localhost:3000/users/sign_in#)
[actionpack (6.1.4.6) lib/action_dispatch/routing/route_set.rb:31:in `serve'](http://localhost:3000/users/sign_in#)
[actionpack (6.1.4.6) lib/action_dispatch/journey/router.rb:50:in `block in serve'](http://localhost:3000/users/sign_in#)
[actionpack (6.1.4.6) lib/action_dispatch/journey/router.rb:32:in `each'](http://localhost:3000/users/sign_in#)
[actionpack (6.1.4.6) lib/action_dispatch/journey/router.rb:32:in `serve'](http://localhost:3000/users/sign_in#)
[actionpack (6.1.4.6) lib/action_dispatch/routing/route_set.rb:842:in `call'](http://localhost:3000/users/sign_in#)
[warden (1.2.9) lib/warden/manager.rb:36:in `block in call'](http://localhost:3000/users/sign_in#)
[warden (1.2.9) lib/warden/manager.rb:34:in `catch'](http://localhost:3000/users/sign_in#)
[warden (1.2.9) lib/warden/manager.rb:34:in `call'](http://localhost:3000/users/sign_in#)
[rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'](http://localhost:3000/users/sign_in#)
[rack (2.2.3) lib/rack/etag.rb:27:in `call'](http://localhost:3000/users/sign_in#)
[rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'](http://localhost:3000/users/sign_in#)
[rack (2.2.3) lib/rack/head.rb:12:in `call'](http://localhost:3000/users/sign_in#)
[actionpack (6.1.4.6) lib/action_dispatch/http/permissions_policy.rb:22:in `call'](http://localhost:3000/users/sign_in#)
[actionpack (6.1.4.6) lib/action_dispatch/http/content_security_policy.rb:18:in `call'](http://localhost:3000/users/sign_in#)
[rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'](http://localhost:3000/users/sign_in#)
[rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'](http://localhost:3000/users/sign_in#)
[actionpack (6.1.4.6) lib/action_dispatch/middleware/cookies.rb:689:in `call'](http://localhost:3000/users/sign_in#)
[activerecord (6.1.4.6) lib/active_record/migration.rb:601:in `call'](http://localhost:3000/users/sign_in#)
[actionpack (6.1.4.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'](http://localhost:3000/users/sign_in#)
[activesupport (6.1.4.6) lib/active_support/callbacks.rb:98:in `run_callbacks'](http://localhost:3000/users/sign_in#)
[actionpack (6.1.4.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'](http://localhost:3000/users/sign_in#)
[actionpack (6.1.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'](http://localhost:3000/users/sign_in#)
[actionpack (6.1.4.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'](http://localhost:3000/users/sign_in#)
[actionpack (6.1.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'](http://localhost:3000/users/sign_in#)
[web-console (4.2.0) lib/web_console/middleware.rb:132:in `call_app'](http://localhost:3000/users/sign_in#)
[web-console (4.2.0) lib/web_console/middleware.rb:19:in `block in call'](http://localhost:3000/users/sign_in#)
[web-console (4.2.0) lib/web_console/middleware.rb:17:in `catch'](http://localhost:3000/users/sign_in#)
[web-console (4.2.0) lib/web_console/middleware.rb:17:in `call'](http://localhost:3000/users/sign_in#)
[actionpack (6.1.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'](http://localhost:3000/users/sign_in#)
[railties (6.1.4.6) lib/rails/rack/logger.rb:37:in `call_app'](http://localhost:3000/users/sign_in#)
[railties (6.1.4.6) lib/rails/rack/logger.rb:26:in `block in call'](http://localhost:3000/users/sign_in#)
[activesupport (6.1.4.6) lib/active_support/tagged_logging.rb:99:in `block in tagged'](http://localhost:3000/users/sign_in#)
[activesupport (6.1.4.6) lib/active_support/tagged_logging.rb:37:in `tagged'](http://localhost:3000/users/sign_in#)
[activesupport (6.1.4.6) lib/active_support/tagged_logging.rb:99:in `tagged'](http://localhost:3000/users/sign_in#)
[railties (6.1.4.6) lib/rails/rack/logger.rb:26:in `call'](http://localhost:3000/users/sign_in#)
[sprockets-rails (3.4.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'](http://localhost:3000/users/sign_in#)
[actionpack (6.1.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'](http://localhost:3000/users/sign_in#)
[request_store (1.5.1) lib/request_store/middleware.rb:19:in `call'](http://localhost:3000/users/sign_in#)
[actionpack (6.1.4.6) lib/action_dispatch/middleware/request_id.rb:26:in `call'](http://localhost:3000/users/sign_in#)
[rack (2.2.3) lib/rack/method_override.rb:24:in `call'](http://localhost:3000/users/sign_in#)
[rack (2.2.3) lib/rack/runtime.rb:22:in `call'](http://localhost:3000/users/sign_in#)
[activesupport (6.1.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'](http://localhost:3000/users/sign_in#)
[actionpack (6.1.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'](http://localhost:3000/users/sign_in#)
[actionpack (6.1.4.6) lib/action_dispatch/middleware/static.rb:24:in `call'](http://localhost:3000/users/sign_in#)
[rack (2.2.3) lib/rack/sendfile.rb:110:in `call'](http://localhost:3000/users/sign_in#)
[actionpack (6.1.4.6) lib/action_dispatch/middleware/host_authorization.rb:119:in `call'](http://localhost:3000/users/sign_in#)
[rack-mini-profiler (2.3.4) lib/mini_profiler/profiler.rb:393:in `call'](http://localhost:3000/users/sign_in#)
[railties (6.1.4.6) lib/rails/engine.rb:539:in `call'](http://localhost:3000/users/sign_in#)
[puma (5.6.2) lib/puma/configuration.rb:252:in `call'](http://localhost:3000/users/sign_in#)
[puma (5.6.2) lib/puma/request.rb:77:in `block in handle_request'](http://localhost:3000/users/sign_in#)
[puma (5.6.2) lib/puma/thread_pool.rb:340:in `with_force_shutdown'](http://localhost:3000/users/sign_in#)
[puma (5.6.2) lib/puma/request.rb:76:in `handle_request'](http://localhost:3000/users/sign_in#)
[puma (5.6.2) lib/puma/server.rb:441:in `process_client'](http://localhost:3000/users/sign_in#)
[puma (5.6.2) lib/puma/thread_pool.rb:147:in `block in spawn_thread'](http://localhost:3000/users/sign_in#)
```

**Comment by masao** [comment]
修正を確認しました。クローズします。
