### ISSUE TITLE
インポート完了時にメッセージが来ない

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1691]
TSVファイルを使って、利用者のインポートを完了しても、メッセージが届きません。

**Comment by masao** [comment]
インポートは無事に完了しています。
![image](https://user-images.githubusercontent.com/38825/174467165-fb6b9f09-30fa-4b2f-b1e7-c9529f85e947.png)

**Comment by masao** [comment]
Resqueのエラーです：

```
Worker
[14e1fe0e7729:1](http://localhost:8080/resque/workers/14e1fe0e7729:1:*) on ENJU_LEAF at [6 minutes ago](http://localhost:8080/resque/failed#)Retried [about 9 hours ago](http://localhost:8080/resque/failed#)Class
[UserImportFileJob ](http://localhost:8080/resque/failed/?class=ActiveJob::QueueAdapters::ResqueAdapter::JobWrapper)[(via ActiveJob)](http://edgeguides.rubyonrails.org/active_job_basics.html)
Arguments
---
job_class: UserImportFileJob
job_id: 39be2a2b-cc74-475d-96db-f29adc08e678
provider_job_id: 
queue_name: enju_leaf
priority: 
arguments:
- _aj_globalid: gid://enju-leaf/UserImportFile/1
executions: 0
exception_executions: {}
locale: ja
timezone: Asia/Tokyo
enqueued_at: '2022-06-19T05:18:57Z'
Exception
Statesman::TransitionFailedError
Error
[Cannot transition from 'completed' to 'failed'](http://localhost:8080/resque/failed#)
/usr/local/bundle/gems/statesman-9.0.1/lib/statesman/machine.rb:301:in `validate_transition'
/usr/local/bundle/gems/statesman-9.0.1/lib/statesman/machine.rb:233:in `transition_to!'
/enju/app/models/user_import_file.rb:45:in `transition_to!'
/enju/app/models/user_import_file.rb:132:in `rescue in import'
/enju/app/models/user_import_file.rb:49:in `import'
/enju/app/models/concerns/import_file.rb:14:in `import_start'
/enju/app/jobs/user_import_file_job.rb:5:in `perform'
/usr/local/bundle/gems/activejob-6.1.6/lib/active_job/execution.rb:48:in `block in perform_now'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/usr/local/bundle/gems/i18n-1.10.0/lib/i18n.rb:328:in `with_locale'
/usr/local/bundle/gems/activejob-6.1.6/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:126:in `instance_exec'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
/usr/local/bundle/gems/activejob-6.1.6/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:126:in `instance_exec'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/usr/local/bundle/gems/activejob-6.1.6/lib/active_job/instrumentation.rb:21:in `block in instrument'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/notifications.rb:203:in `block in instrument'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/notifications.rb:203:in `instrument'
/usr/local/bundle/gems/activejob-6.1.6/lib/active_job/instrumentation.rb:31:in `instrument'
/usr/local/bundle/gems/activejob-6.1.6/lib/active_job/instrumentation.rb:14:in `block (2 levels) in <module:Instrumentation>'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:126:in `instance_exec'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/usr/local/bundle/gems/activejob-6.1.6/lib/active_job/logging.rb:22:in `block in tag_logger'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/tagged_logging.rb:99:in `block in tagged'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/tagged_logging.rb:37:in `tagged'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/tagged_logging.rb:99:in `tagged'
/usr/local/bundle/gems/activejob-6.1.6/lib/active_job/logging.rb:22:in `tag_logger'
/usr/local/bundle/gems/activejob-6.1.6/lib/active_job/logging.rb:15:in `block (2 levels) in <module:Logging>'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:126:in `instance_exec'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:137:in `run_callbacks'
/usr/local/bundle/gems/activejob-6.1.6/lib/active_job/execution.rb:47:in `perform_now'
/usr/local/bundle/gems/activejob-6.1.6/lib/active_job/execution.rb:25:in `block in execute'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/usr/local/bundle/gems/activejob-6.1.6/lib/active_job/railtie.rb:47:in `block (4 levels) in <class:Railtie>'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/execution_wrapper.rb:91:in `wrap'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/reloader.rb:72:in `block in wrap'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/execution_wrapper.rb:91:in `wrap'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/reloader.rb:71:in `wrap'
/usr/local/bundle/gems/activejob-6.1.6/lib/active_job/railtie.rb:46:in `block (3 levels) in <class:Railtie>'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:126:in `instance_exec'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:137:in `run_callbacks'
/usr/local/bundle/gems/activejob-6.1.6/lib/active_job/execution.rb:23:in `execute'
/usr/local/bundle/gems/activejob-6.1.6/lib/active_job/queue_adapters/resque_adapter.rb:47:in `perform'
```

**Comment by nabeta** [comment]
メッセージ送付のところでエラーになっているようです。手元の環境でも再現しましたので、調べます。

**Comment by nabeta** [comment]
@masao 以下のPRで修正しました。
https://github.com/next-l/enju_leaf/pull/1711

最新のmainブランチをpullしたあと、 https://github.com/next-l/enju_leaf/issues/1692#issuecomment-1207354734 https://github.com/next-l/enju_leaf/issues/1692#issuecomment-1207354827 を設定して、もう一度試していただけますか。

**Comment by masao** [comment]
無事にインポート完了時にメッセージが来ることを確認しました。
![image](https://user-images.githubusercontent.com/38825/185778776-450036b1-9012-4dc2-9493-a42a50ee310a.png)
