### ISSUE TITLE
書誌と所蔵のエクスポートに失敗

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1692]
Resque上では [undefined method `email' for nil:NilClass] とエラーが出ています。

```
[14e1fe0e7729:1](http://localhost:8080/resque/workers/14e1fe0e7729:1:*) on ENJU_LEAF at [8 minutes ago](http://localhost:8080/resque/failed#)[Retry](http://localhost:8080/resque/failed/requeue/1) or [Remove](http://localhost:8080/resque/failed/remove/1)Class
[ResourceExportFileJob ](http://localhost:8080/resque/failed/?class=ActiveJob::QueueAdapters::ResqueAdapter::JobWrapper)[(via ActiveJob)](http://edgeguides.rubyonrails.org/active_job_basics.html)
Arguments
---
job_class: ResourceExportFileJob
job_id: a694cc2f-c710-4359-a3de-0174cc22b8e0
provider_job_id: 
queue_name: enju_leaf
priority: 
arguments:
- _aj_globalid: gid://enju-leaf/ResourceExportFile/4
executions: 0
exception_executions: {}
locale: ja
timezone: Asia/Tokyo
enqueued_at: '2022-06-19T05:22:26Z'
Exception
NoMethodError
Error
[undefined method `email' for nil:NilClass](http://localhost:8080/resque/failed#)
/enju/app/mailers/resource_export_mailer.rb:13:in `failed'
/usr/local/bundle/gems/actionpack-6.1.6/lib/abstract_controller/base.rb:228:in `process_action'
/usr/local/bundle/gems/actionpack-6.1.6/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/usr/local/bundle/gems/actiontext-6.1.6/lib/action_text/rendering.rb:20:in `with_renderer'
/usr/local/bundle/gems/actiontext-6.1.6/lib/action_text/engine.rb:59:in `block (4 levels) in <class:Engine>'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:126:in `instance_exec'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:137:in `run_callbacks'
/usr/local/bundle/gems/actionpack-6.1.6/lib/abstract_controller/callbacks.rb:41:in `process_action'
/usr/local/bundle/gems/actionpack-6.1.6/lib/abstract_controller/base.rb:165:in `process'
/usr/local/bundle/gems/actionmailer-6.1.6/lib/action_mailer/rescuable.rb:25:in `block in process'
/usr/local/bundle/gems/actionmailer-6.1.6/lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
/usr/local/bundle/gems/actionmailer-6.1.6/lib/action_mailer/rescuable.rb:24:in `process'
/usr/local/bundle/gems/actionview-6.1.6/lib/action_view/rendering.rb:39:in `process'
/usr/local/bundle/gems/actionmailer-6.1.6/lib/action_mailer/base.rb:615:in `block in process'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/notifications.rb:203:in `block in instrument'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/notifications.rb:203:in `instrument'
/usr/local/bundle/gems/actionmailer-6.1.6/lib/action_mailer/base.rb:614:in `process'
/usr/local/bundle/gems/actionmailer-6.1.6/lib/action_mailer/message_delivery.rb:128:in `block in processed_mailer'
/usr/local/bundle/gems/actionmailer-6.1.6/lib/action_mailer/message_delivery.rb:127:in `tap'
/usr/local/bundle/gems/actionmailer-6.1.6/lib/action_mailer/message_delivery.rb:127:in `processed_mailer'
/usr/local/bundle/gems/actionmailer-6.1.6/lib/action_mailer/message_delivery.rb:30:in `__getobj__'
/usr/local/lib/ruby/2.7.0/delegate.rb:80:in `method_missing'
/enju/app/models/concerns/export_file.rb:14:in `send_message'
/enju/app/models/resource_export_file.rb:48:in `rescue in export!'
/enju/app/models/resource_export_file.rb:33:in `export!'
/enju/app/jobs/resource_export_file_job.rb:5:in `perform'
/usr/local/bundle/gems/activejob-6.1.6/lib/active_job/execution.rb:48:in `block in perform_now'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/usr/local/bundle/gems/i18n-1.10.0/lib/i18n.rb:328:in `with_locale'
/usr/local/bundle/gems/activejob-6.1.6/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:126:in `instance_exec'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
/usr/local/bundle/gems/activejob-6.1.6/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:126:in `instance_exec'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/usr/local/bundle/gems/activejob-6.1.6/lib/active_job/instrumentation.rb:21:in `block in instrument'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/notifications.rb:203:in `block in instrument'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/notifications.rb:203:in `instrument'
/usr/local/bundle/gems/activejob-6.1.6/lib/active_job/instrumentation.rb:31:in `instrument'
/usr/local/bundle/gems/activejob-6.1.6/lib/active_job/instrumentation.rb:14:in `block (2 levels) in <module:Instrumentation>'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:126:in `instance_exec'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/usr/local/bundle/gems/activejob-6.1.6/lib/active_job/logging.rb:22:in `block in tag_logger'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/tagged_logging.rb:99:in `block in tagged'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/tagged_logging.rb:37:in `tagged'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/tagged_logging.rb:99:in `tagged'
/usr/local/bundle/gems/activejob-6.1.6/lib/active_job/logging.rb:22:in `tag_logger'
/usr/local/bundle/gems/activejob-6.1.6/lib/active_job/logging.rb:15:in `block (2 levels) in <module:Logging>'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:126:in `instance_exec'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:137:in `run_callbacks'
/usr/local/bundle/gems/activejob-6.1.6/lib/active_job/execution.rb:47:in `perform_now'
/usr/local/bundle/gems/activejob-6.1.6/lib/active_job/execution.rb:25:in `block in execute'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/usr/local/bundle/gems/activejob-6.1.6/lib/active_job/railtie.rb:47:in `block (4 levels) in <class:Railtie>'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/execution_wrapper.rb:91:in `wrap'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/reloader.rb:72:in `block in wrap'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/execution_wrapper.rb:91:in `wrap'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/reloader.rb:71:in `wrap'
/usr/local/bundle/gems/activejob-6.1.6/lib/active_job/railtie.rb:46:in `block (3 levels) in <class:Railtie>'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:126:in `instance_exec'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:137:in `run_callbacks'
/usr/local/bundle/gems/activejob-6.1.6/lib/active_job/execution.rb:23:in `execute'
/usr/local/bundle/gems/activejob-6.1.6/lib/active_job/queue_adapters/resque_adapter.rb:47:in `perform'
```

**Comment by nabeta** [comment]
@masao なんらかの問題で、初期データがきちんと設定されていないようです。コンソールで以下のコマンドを実行してください。

```sh
docker compose run --rm web rails c
```

```ruby
library_group = LibraryGroup.first
library_group.update(user: User.find_by(username: 'system')
```

以下のコマンドでメールアドレスが出力できていれば、正しく設定されています。

```ruby
library_group.user.email
```

**Comment by nabeta** [comment]
あわせて、`.env`に以下を設定してください。

```
ENJU_LEAF_ACTION_MAILER_DELIVERY_METHOD=test
```

**Comment by masao** [comment]
ありがとうございます。エクスポートできるようになりましたので、クローズします
