### ISSUE TITLE
redhat系へのインストールにおいて、dbの構築が上手く動作しない

### ISSUE THREAD

**Issue by jippless3024** [next-l/enju_leaf#1710]
https://github.com/next-l/enju_leaf/wiki/Install
上記のインストール手順を参考にCentOSの環境へのインストールを試みております。

$ bundle exec rake db:create:all
$ bundle exec rake enju_leaf:setup
Enju Leaf本体のインストールにおける上記の手順において上手く動作しておりません。
表示については後述しますが、.envとconfig/database.ymlにそれぞれ初期で記載されているenju_leaf_productionが重複していること、そのためかどうかは不明ですがrolesテーブルが作成されていないのでしょうか？enju_leaf_production、enju_leaf_test共にデータベースは作成されているのですが、テーブルは作成されておりません。
こちらにつきまして、当方の対応すべき個所がお分かりになりますでしょうか？もしくは回避策等はございますでしょうか？
お手数をおかけいたしますが、ご確認いただけたら幸いです。

```
$ bundle exec rake db:create:all
Created database 'enju_leaf_production'
Created database 'enju_leaf_test'
Database 'enju_leaf_production' already exists
```

```
$ bundle exec rake enju_leaf:setup --trace
** Invoke enju_leaf:setup (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute enju_leaf:setup
** Invoke enju_seed:setup (first_time)
** Invoke environment
** Execute enju_seed:setup
rake aborted!
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  リレーション"roles"は存在しません
LINE 8:  WHERE a.attrelid = '"roles"'::regclass
                            ^
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rack-mini-profiler-2.3.4/lib/patches/db/pg.rb:110:in `exec'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rack-mini-profiler-2.3.4/lib/patches/db/pg.rb:110:in `async_exec'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:19:in `block (2 levels) in query'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:18:in `block in query'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/abstract_adapter.rb:696:in `block (2 levels) in log'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/abstract_adapter.rb:695:in `block in log'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/abstract_adapter.rb:687:in `log'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:17:in `query'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/postgresql_adapter.rb:820:in `column_definitions'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:116:in `columns'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/schema_cache.rb:112:in `block in columns'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/schema_cache.rb:111:in `fetch'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/schema_cache.rb:111:in `columns'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/schema_cache.rb:120:in `block in columns_hash'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/schema_cache.rb:119:in `fetch'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/schema_cache.rb:119:in `columns_hash'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-6.1.6.1/lib/active_record/model_schema.rb:553:in `load_schema!'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-6.1.6.1/lib/active_record/attributes.rb:250:in `load_schema!'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-6.1.6.1/lib/active_record/model_schema.rb:539:in `block in load_schema'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-6.1.6.1/lib/active_record/model_schema.rb:536:in `synchronize'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-6.1.6.1/lib/active_record/model_schema.rb:536:in `load_schema'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-6.1.6.1/lib/active_record/model_schema.rb:397:in `columns'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-6.1.6.1/lib/active_record/model_schema.rb:466:in `column_names'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-6.1.6.1/lib/active_record/timestamp.rb:64:in `timestamp_attributes_for_create_in_model'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-6.1.6.1/lib/active_record/timestamp.rb:74:in `all_timestamp_attributes_in_model'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-6.1.6.1/lib/active_record/fixture_set/model_metadata.rb:24:in `timestamp_column_names'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-6.1.6.1/lib/active_record/fixture_set/table_row.rb:79:in `fill_timestamps'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-6.1.6.1/lib/active_record/fixture_set/table_row.rb:61:in `fill_row_model_attributes'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-6.1.6.1/lib/active_record/fixture_set/table_row.rb:43:in `initialize'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-6.1.6.1/lib/active_record/fixture_set/table_rows.rb:36:in `new'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-6.1.6.1/lib/active_record/fixture_set/table_rows.rb:36:in `block in build_table_rows_from'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-6.1.6.1/lib/active_record/fixture_set/table_rows.rb:35:in `each'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-6.1.6.1/lib/active_record/fixture_set/table_rows.rb:35:in `map'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-6.1.6.1/lib/active_record/fixture_set/table_rows.rb:35:in `build_table_rows_from'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-6.1.6.1/lib/active_record/fixture_set/table_rows.rb:18:in `initialize'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-6.1.6.1/lib/active_record/fixtures.rb:688:in `new'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-6.1.6.1/lib/active_record/fixtures.rb:688:in `table_rows'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-6.1.6.1/lib/active_record/fixtures.rb:633:in `block (2 levels) in insert'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-6.1.6.1/lib/active_record/fixtures.rb:632:in `each'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-6.1.6.1/lib/active_record/fixtures.rb:632:in `block in insert'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-6.1.6.1/lib/active_record/fixtures.rb:629:in `each'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-6.1.6.1/lib/active_record/fixtures.rb:629:in `insert'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-6.1.6.1/lib/active_record/fixtures.rb:615:in `read_and_insert'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-6.1.6.1/lib/active_record/fixtures.rb:567:in `create_fixtures'
/var/www/src/enju_leaf/lib/tasks/enju_seed_tasks.rake:5:in `block (3 levels) in <main>'
/var/www/src/enju_leaf/lib/tasks/enju_seed_tasks.rake:4:in `each'
/var/www/src/enju_leaf/lib/tasks/enju_seed_tasks.rake:4:in `block (2 levels) in <main>'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/var/www/src/enju_leaf/lib/tasks/enju_leaf_tasks.rake:11:in `block (2 levels) in <main>'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
.rbenv/versions/2.7.6/bin/rake:23:in `load'
.rbenv/versions/2.7.6/bin/rake:23:in `<top (required)>'
.rbenv/versions/2.7.6/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `load'
.rbenv/versions/2.7.6/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `kernel_load'
.rbenv/versions/2.7.6/lib/ruby/2.7.0/bundler/cli/exec.rb:28:in `run'
.rbenv/versions/2.7.6/lib/ruby/2.7.0/bundler/cli.rb:476:in `exec'
.rbenv/versions/2.7.6/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
.rbenv/versions/2.7.6/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
.rbenv/versions/2.7.6/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
.rbenv/versions/2.7.6/lib/ruby/2.7.0/bundler/cli.rb:30:in `dispatch'
.rbenv/versions/2.7.6/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
.rbenv/versions/2.7.6/lib/ruby/2.7.0/bundler/cli.rb:24:in `start'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:46:in `block in <top (required)>'
.rbenv/versions/2.7.6/lib/ruby/2.7.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'
.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:34:in `<top (required)>'
.rbenv/versions/2.7.6/bin/bundle:23:in `load'
.rbenv/versions/2.7.6/bin/bundle:23:in `<main>'

Caused by:
PG::UndefinedTable: ERROR:  リレーション"roles"は存在しません
LINE 8:  WHERE a.attrelid = '"roles"'::regclass
                            ^

Tasks: TOP => enju_seed:setup
```

**Comment by nabeta** [comment]
@jippless3024  `.env`の中の`RAILS_ENV=`はどのようになっていますでしょうか。

**Comment by jippless3024** [comment]
@nabeta 
RAILS_ENVはgit cloneした状態から変更しておらず、productionです。

念のため、.envの中身を全て下記に記載します。変更箇所はdb環境に合わせてPOSTGRES_HOST、POSTGRES_PASSWORDのみだったはずです。

`
RAILS_ENV=production
RAILS_LOG_TO_STDOUT=true

POSTGRES_USER=enju_leaf
POSTGRES_HOST=localhost
POSTGRES_PASSWORD=*****
DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/e
nju_leaf_${RAILS_ENV}

REDIS_URL=redis://redis/enju-leaf-${RAILS_ENV}

SOLR_URL=http://solr:8983/solr/enju_leaf_${RAILS_ENV}

ENJU_LEAF_BASE_URL=http://localhost:8080
ENJU_LEAF_DEFAULT_LOCALE=ja
ENJU_LEAF_TIME_ZONE=Asia/Tokyo
ENJU_LEAF_STORAGE_BUCKET=enju-leaf
ENJU_LEAF_STORAGE_ENDPOINT=http://minio:9000
ENJU_LEAF_ACTION_MAILER_DELIVERY_METHOD=test
# ENJU_LEAF_RESOURCESYNC_BASE_URL=http://localhost:8080

no_proxy=localhost,webpacker,minio,solr
NO_PROXY=${no_proxy}

UID=1000
GID=1000
`

**Comment by nabeta** [comment]
@jippless3024 すみません、ドキュメントに不備がありました。以下の項目を追記・修正しましたので、もう一度試していただけますでしょうか。

Solrのインストールと起動:

```
$ cd ~/
$ wget https://archive.apache.org/dist/lucene/solr/6.6.6/solr-6.6.6.tgz
$ tar zxvf solr-6.6.6.tgz
$ cd solr-6.6.6
$ bin/solr start
```

`.env`の編集（PostgreSQLとSolrがlocalhostで動作していることを前提としています）:

```
# ユーザ名、ホスト名、パスワードを適宜変更
POSTGRES_USER=vagrant
POSTGRES_HOST=localhost
POSTGRES_PASSWORD=password
DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/enju_leaf_${RAILS_ENV}

# ホスト名を変更
SOLR_URL=http://localhost:8983/solr/enju_leaf_${RAILS_ENV}
```

PostgreSQLのデータベースの作成:

```
$ bundle exec rake db:create:all
$ bundle exec rake db:migrate
```

Solrのコアの作成:

```
$ ~/solr-6.6.6/bin/solr create -c enju_leaf_production -d solr/configsets/sunspot/conf/
```

**Comment by jippless3024** [comment]
@nabeta
インストール手順につきまして、ご教示いただきました内容でインストールスクリプトの正常終了を確認いたしました。
ありがとうございます。

その後、アプリケーションの起動手順を実施したところ

rbenv sudo bundle exec rails s -e production
```
=> Booting Puma
=> Rails 6.1.6.1 application starting in production
=> Run `bin/rails server --help` for more startup options
W, [2022-08-07T19:25:09.291535 #3913]  WARN -- : Creating scope :in_list. Overwriting existing method Shelf.in_list.
W, [2022-08-07T19:25:09.299350 #3913]  WARN -- : Creating scope :on_shelf. Overwriting existing method Item.on_shelf.
W, [2022-08-07T19:25:09.299569 #3913]  WARN -- : Creating scope :available. Overwriting existing method Item.available.
W, [2022-08-07T19:25:09.305310 #3913]  WARN -- : Creating scope :accepted_between. Overwriting existing method Item.accepted_between.
W, [2022-08-07T19:25:09.307196 #3913]  WARN -- : Creating scope :in_list. Overwriting existing method ItemCustomProperty.in_list.
W, [2022-08-07T19:25:09.423822 #3913]  WARN -- : Creating scope :in_list. Overwriting existing method ManifestationCustomProperty.in_list.
Puma starting in single mode...
* Puma version: 5.6.4 (ruby 2.7.6-p219) ("Birdie's Version")
*  Min threads: 5
*  Max threads: 5

*  Environment: production
*          PID: 3913
* Listening on http://0.0.0.0:3000
Use Ctrl-C to stop
```
と表示され、上手く行ったかと思いましたが、
ブラウザにてアクセス時、ブラウザにて「We're sorry, but something went wrong.if you are the application owner check the logs for more information.」と表示され、コンソールには下記が表示されております。こちらがenju由来なのか、その他環境由来なのか切り分けできず、お手数をおかけしますがこちらもご確認いただけると助かります。
```
I, [2022-08-07T19:25:25.669352 #3913]  INFO -- : [a58b8777-d1eb-43b5-a8a1-4d6576266b2e] Started GET "/" for 192.168.13.2 at 2022-08-07 19:25:25 +0900
I, [2022-08-07T19:25:25.670339 #3913]  INFO -- : [a58b8777-d1eb-43b5-a8a1-4d6576266b2e] Processing by PageController#index as HTML
I, [2022-08-07T19:25:25.757478 #3913]  INFO -- : [a58b8777-d1eb-43b5-a8a1-4d6576266b2e]   Rendered page/index.html.erb within layouts/application (Duration: 12.6ms | Allocations: 4524)
I, [2022-08-07T19:25:25.759381 #3913]  INFO -- : [a58b8777-d1eb-43b5-a8a1-4d6576266b2e]   Rendered layout layouts/application.html.erb (Duration: 14.6ms | Allocations: 6011)
I, [2022-08-07T19:25:25.759649 #3913]  INFO -- : [a58b8777-d1eb-43b5-a8a1-4d6576266b2e] Completed 500 Internal Server Error in 89ms (ActiveRecord: 18.3ms | Allocations: 31954)
F, [2022-08-07T19:25:25.760346 #3913] FATAL -- : [a58b8777-d1eb-43b5-a8a1-4d6576266b2e]
[a58b8777-d1eb-43b5-a8a1-4d6576266b2e] ActionView::Template::Error (The asset "application.css" is not present in the asset pipeline.
):
[a58b8777-d1eb-43b5-a8a1-4d6576266b2e]     1: <%= stylesheet_link_tag 'application' %>
[a58b8777-d1eb-43b5-a8a1-4d6576266b2e]     2: <%= stylesheet_link_tag 'print', media: :print %>
[a58b8777-d1eb-43b5-a8a1-4d6576266b2e]     3: <%= javascript_include_tag 'application' %>
[a58b8777-d1eb-43b5-a8a1-4d6576266b2e]     4: <%= csrf_meta_tag %>
[a58b8777-d1eb-43b5-a8a1-4d6576266b2e]
[a58b8777-d1eb-43b5-a8a1-4d6576266b2e] app/views/page/_include.html.erb:1
[a58b8777-d1eb-43b5-a8a1-4d6576266b2e] app/views/layouts/application.html.erb:5
```

**Comment by jippless3024** [comment]
また、これはまた別の話となりますが、
rbenv sudo bundle exec rails s
でrailsを起動した場合、Environmentがdevelopmentとして起動します。
.envにてRAILS_ENV=productionを指定しているので、productionとして起動するものと思っていたのですが、この動作は正常なのでしょうか？
rubyやrailsの知識が無く、調べても確信できるような情報が無かったため、初歩的な内容になるかもしれませんが、こちらにつきましてもお手数をおかけいたしますがご確認いただけますでしょうか？

**Comment by nabeta** [comment]
> ブラウザにてアクセス時、ブラウザにて「We're sorry, but something went wrong.if you are the application owner check the logs for more information.」と表示され、コンソールには下記が表示されております。

すみません、production環境の場合は以下のコマンドが必要でした。こちらを実行した後、アプリケーションを再起動してください。

```
# development環境の場合は不要
$ bundle exec rake assets:precompile
```

**Comment by nabeta** [comment]
> .envにてRAILS_ENV=productionを指定しているので、productionとして起動するものと思っていたのですが、この動作は正常なのでしょうか？

たしかに、`.env`のRAILS_ENVを参照しませんね。以下のコマンドで、環境を指定して起動していただけますか。

```
$ bundle exec rails s -e production
```

あと、非同期処理用サーバの起動コマンドも修正しています。

```
$ bundle exec rake environment resque:work
```

**Comment by nabeta** [comment]
同様に、コンソールの起動は以下になります。

```
$ bundle exec rails c -e production
```

**Comment by jippless3024** [comment]
> bundle exec rake assets:precompile

こちらを実行後、「We're sorry, but something went wrong.if you are the application owner check the logs for more information.」の表示は無くなり、トップページやログインが可能になりました。
しかし、動作的には正常に動作しているように感じますが、今度はスタイルシートや画像等に関しての表示が正常でないように見えます。
![image](https://user-images.githubusercontent.com/93677046/183289799-7965391d-ed10-4583-86d1-c06449e95c79.png)

> 非同期処理用サーバの起動コマンドも修正しています。

非同期処理用サーバの起動につきまして、ようにすぐに入力に戻るのですが、こちらで問題ありませんか？
webサーバーは起動中常時ログ等を表示し続けているのですが、こちらは非同期処理ということでこのようになっているんですかね？
```
[u@u enju_leaf]$rbenv sudo bundle exec rake environment resque:work
set QUEUE env var, e.g. $ QUEUE=critical,high rake resque:work
[u@u enju_leaf]$
```

重ね重ね申し訳ありませんが上記につきましてもご確認いただけませんでしょうか

**Comment by nabeta** [comment]
@jippless3024 以下のコマンドを実行して、アプリケーションを再起動していただけますか。

```
$ bundle exec rake assets:precompile
```

**Comment by jippless3024** [comment]
@nabeta
https://github.com/next-l/enju_leaf/issues/1710#issuecomment-1207377893
に対し、
https://github.com/next-l/enju_leaf/issues/1710#issuecomment-1207380637
を実施したところ、
https://github.com/next-l/enju_leaf/issues/1710#issuecomment-1207394344
の状態となっております。
念のため、再度実施した結果を記載いたします。
rbenv sudo bundle exec rake assets:precompile
```
Type application/netcdf is already registered as a variant of application/netcdf.
yarn install v1.22.19
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 0.07s.
```
そのうえで、再起動しましたが、
https://github.com/next-l/enju_leaf/issues/1710#issuecomment-1207394344
と同様な状態となっております。
bundle等はそのままだとpermission deniedになってしまうため、下記のプラグインで対処しているのですが、それが原因となっている様子はありますでしょうか？権限周りのようであれば、別途対処を検討してみようと思います
https://github.com/dcarley/rbenv-sudo

**Comment by nabeta** [comment]
> bundle等はそのままだとpermission deniedになってしまうため

@jippless3024 Ruby本体はどのようにインストールしていますでしょうか。なお、rbenvでのインストールをおすすめしています。

**Comment by nabeta** [comment]
あと、Webブラウザにアクセスする際のURLは、 http://localhost:3000/ でしょうか。その場合、以下の行を `.env` に追加していただけますか。

```
RAILS_SERVE_STATIC_FILES=true
```

**Comment by jippless3024** [comment]
@nabeta 
rbenvでのインストールをしていたのですが、permission deniedとなっておりました。権限等の都合だと思うのですが、こちらは別途対策を実施したら回避できているようなので問題ないようです。

ブラウザでのアクセスは、Lan内の別端末からであったため、http://ローカルip:3000で行っていたため、頂いた通りにRAILS_SERVE_STATIC_FILESを追加することでスタイルシート等読み込まれ、動作デモと同様の表示になることを確認いたしました。
ありがとうございました！

最後に、https://github.com/next-l/enju_leaf/issues/1710#issuecomment-1207394344の後者につきまして、非同期処理用サーバが正常に動作しているか確認いただけますでしょうか？
Install手順的に、非同期処理用サーバのほうもWebサーバと同じような表示となるのが正しいのでしょうか？

**Comment by nabeta** [comment]
@jippless3024 よかったです！

> 非同期処理用サーバが正常に動作しているか確認いただけますでしょうか？

 http://localhost:3000/resque/workers にアクセスして、"1 Workers"という表示が出ていれば、非同期処理サーバが起動しています。
