### ISSUE TITLE
起動時に uninitialized constant Mail::TestMailer エラー

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1771]
1.4系最新版のEnjuで、Solr再索引時に以下のエラーが発生してとまるようです。

```
$ docker compose run --rm web rake sunspot:reindex
WARN[0000] The "http_proxy" variable is not set. Defaulting to a blank string.
WARN[0000] The "http_proxy" variable is not set. Defaulting to a blank string.
WARN[0000] The "ENJU_LEAF_BIND_ADDRESS" variable is not set. Defaulting to a blank string.
WARN[0000] The "ENJU_LEAF_BIND_ADDRESS" variable is not set. Defaulting to a blank string.
WARN[0000] The "CANTALOUPE_BASE_URI" variable is not set. Defaulting to a blank string.
WARN[0000] The "http_proxy" variable is not set. Defaulting to a blank string.
WARN[0000] The "http_proxy" variable is not set. Defaulting to a blank string.
WARN[0000] The "http_proxy" variable is not set. Defaulting to a blank string.
WARN[0000] The "http_proxy" variable is not set. Defaulting to a blank string.
WARN[0000] The "http_proxy" variable is not set. Defaulting to a blank string.
WARN[0000] The "http_proxy" variable is not set. Defaulting to a blank string.
[+] Running 3/0
 ⠿ Container enju_leaf-solr-1      Running                                                                         0.0s
 ⠿ Container enju_leaf-redis-1     Running                                                                         0.0s
 ⠿ Container enju_leaf-postgres-1  Running                                                                         0.0s
rake aborted!
NameError: uninitialized constant Mail::TestMailer
/usr/local/bundle/gems/actionmailer-6.1.7/lib/action_mailer/delivery_methods.rb:42:in `<module:ClassMethods>'
/usr/local/bundle/gems/actionmailer-6.1.7/lib/action_mailer/delivery_methods.rb:40:in `<module:DeliveryMethods>'
/usr/local/bundle/gems/actionmailer-6.1.7/lib/action_mailer/delivery_methods.rb:8:in `<module:ActionMailer>'
/usr/local/bundle/gems/actionmailer-6.1.7/lib/action_mailer/delivery_methods.rb:5:in `<main>'
/usr/local/bundle/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
/usr/local/bundle/gems/actionmailer-6.1.7/lib/action_mailer/base.rb:438:in `<class:Base>'
/usr/local/bundle/gems/actionmailer-6.1.7/lib/action_mailer/base.rb:437:in `<module:ActionMailer>'
/usr/local/bundle/gems/actionmailer-6.1.7/lib/action_mailer/base.rb:12:in `<main>'
/usr/local/bundle/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
/enju/app/mailers/application_mailer.rb:1:in `<main>'
/usr/local/bundle/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:30:in `require'
/enju/app/mailers/agent_import_mailer.rb:1:in `<main>'
/usr/local/bundle/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:30:in `require'
/usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:135:in `const_get'
/usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:135:in `cget'
/usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:169:in `block in actual_eager_load_dir'
/usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:40:in `block in ls'
/usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:25:in `each'
/usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:25:in `ls'
/usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:164:in `actual_eager_load_dir'
/usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:17:in `block (2 levels) in eager_load'
/usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:16:in `each'
/usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:16:in `block in eager_load'
/usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:10:in `synchronize'
/usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:10:in `eager_load'
/usr/local/bundle/gems/railties-6.1.7/lib/rails/autoloaders.rb:30:in `each'
/usr/local/bundle/gems/railties-6.1.7/lib/rails/application.rb:517:in `eager_load!'
/usr/local/bundle/gems/sunspot_rails-2.6.0/lib/sunspot/rails/tasks.rb:33:in `block (3 levels) in <main>'
/usr/local/bundle/gems/sunspot_rails-2.6.0/lib/sunspot/rails/tasks.rb:70:in `with_session'
/usr/local/bundle/gems/sunspot_rails-2.6.0/lib/sunspot/rails/tasks.rb:19:in `block (2 levels) in <main>'
/usr/local/bundle/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
Tasks: TOP => sunspot:reindex
(See full trace by running task with --trace)
```

**Comment by masao** [comment]
reindex以外で、docker compose upでもほぼすべて失敗するようなので、Issueのタイトルを変更します。

**Comment by nabeta** [comment]
@masao こちらではエラーを確認できないのですが、1.4ブランチでしょうか。また、buildし直すとどうでしょうか。

```
$ docker compose build
```

**Comment by masao** [comment]
1.4系ではなく master ブランチになっているのに気づいてなかったです。ブランチ切り替えで解決したのでクローズします
