### ISSUE TITLE
ActiveStorageへの移行テストを行う

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#1778]
以下のアップロードファイルが移行できるかテストする。

- [x] Manifestation （資料の添付ファイル）
- [x] PictureFile  （画像ファイル）
- [x] LibraryGroup （ロゴ）
- [x] ResourceImportFile （資料インポートファイル）
- [x] ResourceExportFile （資料エクスポートファイル）
- [x] EventImportFile （催し物インポートファイル）
- [x] EventExportFile （催し物エクスポートファイル）
- [x] UserImportFile （ユーザインポートファイル）
- [x] UserExportFile （ユーザエクポートファイル）
- [x] AgentImportFile （著者インポートファイル）(利用マニュアルなし・誰も使ってないので移行チェックはしなくてよい)
- [x] InventoryFile （蔵書点検ファイル）(利用マニュアルなし・誰も使ってないので移行チェックはしなくてよい)
- [x] CarrierType （資料種別アイコンファイル）

一覧は以下のコマンドで調べている。

```
$ grep has_attached_file app/models/ -r
```

**Comment by nabeta** [comment]
以下の手順で、1.5系へのアップグレードと添付ファイルの移行を行う。

```
cd enju_leaf
git pull
git checkout main
git pull
docker compose run --rm web rake db:migrate # ActiveStorage用のテーブルを作成
docker compose run --rm web rake migrate_attachments # ファイルを移行
```

**Comment by masao** [comment]
上記のコマンドだとエラーになりますね：

```
rake aborted!
Don't know how to build task 'migrate_attachments' (See the list of available tasks with `rake --tasks`)
/usr/local/bundle/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by masao** [comment]
以下のコマンドを実行すると：
```
docker compose run --rm web rake enju_leaf:migrate_attachments
```

以下のエラーになります：
```
rake aborted!
TypeError: no implicit conversion of Paperclip::Attachment into String
/enju/lib/tasks/attachment.rb:30:in `initialize'
/enju/lib/tasks/attachment.rb:30:in `open'
/enju/lib/tasks/attachment.rb:30:in `block in migrate_attachment'
/usr/local/bundle/gems/activerecord-6.1.7.1/lib/active_record/relation/batches.rb:71:in `block (2 levels) in find_each'
/usr/local/bundle/gems/activerecord-6.1.7.1/lib/active_record/relation/batches.rb:71:in `each'
/usr/local/bundle/gems/activerecord-6.1.7.1/lib/active_record/relation/batches.rb:71:in `block in find_each'
/usr/local/bundle/gems/activerecord-6.1.7.1/lib/active_record/relation/batches.rb:138:in `block in find_in_batches'
/usr/local/bundle/gems/activerecord-6.1.7.1/lib/active_record/relation/batches.rb:245:in `block in in_batches'
/usr/local/bundle/gems/activerecord-6.1.7.1/lib/active_record/relation/batches.rb:229:in `loop'
/usr/local/bundle/gems/activerecord-6.1.7.1/lib/active_record/relation/batches.rb:229:in `in_batches'
/usr/local/bundle/gems/activerecord-6.1.7.1/lib/active_record/relation/batches.rb:137:in `find_in_batches'
/usr/local/bundle/gems/activerecord-6.1.7.1/lib/active_record/relation/batches.rb:70:in `find_each'
/enju/lib/tasks/attachment.rb:28:in `migrate_attachment'
/enju/lib/tasks/enju_leaf_tasks.rake:85:in `block (2 levels) in <main>'
/usr/local/bundle/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
Tasks: TOP => enju_leaf:migrate_attachments
(See full trace by running task with --trace)
```
```

**Comment by nabeta** [comment]
@masao git pull して再実行してください。

**Comment by masao** [comment]
別のエラーになりました：

```
rake aborted!
NoMethodError: undefined method `attachment' for #<LibraryGroup id: 1, name: "enju_library", display_name: "en: Enju Library\r\nja: えんじゅ図書館", short_name: "enju", my_networks: "0.0.0.0/0\r\n::/0", old_login_banner: nil, note: "", country_id: 1, position: nil, created_at: "2023-01-22 14:13:41.333971000 +0900", updated_at: "2023-01-22 14:16:32.039157000 +0900", admin_networks: "0.0.0.0/0\r\n::/0", allow_bookmark_external_url: false, url: "http://localhost:8080", settings: {"max_number_of_results"=>500, "family_name_first"=>true, "skip_mobile_agents"=>"ipad"}, html_snippet: nil, book_jacket_source: "google", max_number_of_results: 1000, family_name_first: true, screenshot_generator: nil, pub_year_facet_range_interval: 10, user_id: 1, csv_charset_conversion: false, header_logo_file_name: "logo.png", header_logo_content_type: "image/png", header_logo_file_size: 1377, header_logo_updated_at: "2023-01-22 14:16:31.984542000 +0900", header_logo_meta: "BAh7BzoNb3JpZ2luYWx7CDoKd2lkdGhpAaQ6C2hlaWdodGlBOg...", login_banner: "オープンソース図書館システム Next-L Enju です。このメッセ ージは管理者としてログインした...", footer_banner: "[Next-L Enju Leaf __VERSION__](https://github.com/...">
Did you mean?  attachment_changes
/usr/local/bundle/gems/activemodel-6.1.7.1/lib/active_model/attribute_methods.rb:469:in `method_missing'
/enju/lib/tasks/attachment.rb:62:in `block in migrate_attachment'
/usr/local/bundle/gems/activerecord-6.1.7.1/lib/active_record/relation/batches.rb:71:in `block (2 levels) in find_each'
/usr/local/bundle/gems/activerecord-6.1.7.1/lib/active_record/relation/batches.rb:71:in `each'
/usr/local/bundle/gems/activerecord-6.1.7.1/lib/active_record/relation/batches.rb:71:in `block in find_each'
/usr/local/bundle/gems/activerecord-6.1.7.1/lib/active_record/relation/batches.rb:138:in `block in find_in_batches'
/usr/local/bundle/gems/activerecord-6.1.7.1/lib/active_record/relation/batches.rb:245:in `block in in_batches'
/usr/local/bundle/gems/activerecord-6.1.7.1/lib/active_record/relation/batches.rb:229:in `loop'
/usr/local/bundle/gems/activerecord-6.1.7.1/lib/active_record/relation/batches.rb:229:in `in_batches'
/usr/local/bundle/gems/activerecord-6.1.7.1/lib/active_record/relation/batches.rb:137:in `find_in_batches'
/usr/local/bundle/gems/activerecord-6.1.7.1/lib/active_record/relation/batches.rb:70:in `find_each'
/enju/lib/tasks/attachment.rb:61:in `migrate_attachment'
/enju/lib/tasks/enju_leaf_tasks.rake:85:in `block (2 levels) in <main>'
/usr/local/bundle/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
Tasks: TOP => enju_leaf:migrate_attachments
(See full trace by running task with --trace)
```

**Comment by masao** [comment]
```
rake aborted!
NoMethodError: undefined method `attahcment_file_name' for #<Manifestation id: 11, original_title: "Test Thesis", title_alternative: "", title_transcription: "Test Thesis", classification_number: nil, manifestation_identifier: nil, date_of_publication: nil, date_copyrighted: nil, created_at: "2023-01-22 14:21:46.812213000 +0900", updated_at: "2023-01-22 14:22:25.902192000 +0900", access_address: "", language_id: 77, carrier_type_id: 1, start_page: nil, end_page: nil, height: nil, width: nil, depth: nil, price: nil, fulltext: nil, volume_number_string: "", issue_number_string: "", serial_number_string: nil, edition: nil, note: "", repository_content: false, lock_version: 1, required_role_id: 1, required_score: 0, frequency_id: 1, subscription_master: false, attachment_file_name: "klis-thesis.pdf", attachment_content_type: "application/pdf", attachment_file_size: 1263068, attachment_updated_at: "2023-01-22 14:22:25.874870000 +0900", nii_type_id: nil, title_alternative_transcription: nil, description: "", abstract: "", available_at: nil, valid_until: nil, date_submitted: nil, date_accepted: nil, date_captured: nil, pub_date: nil, edition_string: "", volume_number: nil, issue_number: nil, serial_number: nil, content_type_id: 1, year_of_publication: nil, attachment_meta: "BAh7BjoNb3JpZ2luYWx7AA==\n", month_of_publication: nil, fulltext_content: nil, serial: false, statement_of_responsibility: "", publication_place: "", extent: "", dimensions: "", memo: "">
Did you mean?  attachment_file_name
               attachment_file_name=
               attachment_file_name?
               attachment_file_size
/usr/local/bundle/gems/activemodel-6.1.7.1/lib/active_model/attribute_methods.rb:469:in `method_missing'
/enju/lib/tasks/attachment.rb:79:in `block in migrate_attachment'
/usr/local/bundle/gems/activerecord-6.1.7.1/lib/active_record/relation/batches.rb:71:in `block (2 levels) in find_each'
/usr/local/bundle/gems/activerecord-6.1.7.1/lib/active_record/relation/batches.rb:71:in `each'
/usr/local/bundle/gems/activerecord-6.1.7.1/lib/active_record/relation/batches.rb:71:in `block in find_each'
/usr/local/bundle/gems/activerecord-6.1.7.1/lib/active_record/relation/batches.rb:138:in `block in find_in_batches'
/usr/local/bundle/gems/activerecord-6.1.7.1/lib/active_record/relation/batches.rb:245:in `block in in_batches'
/usr/local/bundle/gems/activerecord-6.1.7.1/lib/active_record/relation/batches.rb:229:in `loop'
/usr/local/bundle/gems/activerecord-6.1.7.1/lib/active_record/relation/batches.rb:229:in `in_batches'
/usr/local/bundle/gems/activerecord-6.1.7.1/lib/active_record/relation/batches.rb:137:in `find_in_batches'
/usr/local/bundle/gems/activerecord-6.1.7.1/lib/active_record/relation/batches.rb:70:in `find_each'
/enju/lib/tasks/attachment.rb:72:in `migrate_attachment'
/enju/lib/tasks/enju_leaf_tasks.rake:85:in `block (2 levels) in <main>'
/usr/local/bundle/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
Tasks: TOP => enju_leaf:migrate_attachments
(See full trace by running task with --trace)
```

**Comment by masao** [comment]
まだ・・・：

```
rake aborted!
ArgumentError: missing keyword: :filename
/usr/local/bundle/gems/activestorage-6.1.7.1/app/models/active_storage/blob.rb:97:in `build_after_unfurling'
/usr/local/bundle/gems/activestorage-6.1.7.1/lib/active_storage/attached/changes/create_one.rb:65:in `find_or_build_blob'
/usr/local/bundle/gems/activestorage-6.1.7.1/lib/active_storage/attached/changes/create_one.rb:20:in `blob'
/usr/local/bundle/gems/activestorage-6.1.7.1/lib/active_storage/attached/changes/create_one.rb:12:in `initialize'
/usr/local/bundle/gems/activestorage-6.1.7.1/lib/active_storage/attached/model.rb:65:in `new'
/usr/local/bundle/gems/activestorage-6.1.7.1/lib/active_storage/attached/model.rb:65:in `attachment='
/usr/local/bundle/gems/activestorage-6.1.7.1/lib/active_storage/attached/one.rb:32:in `public_send'
/usr/local/bundle/gems/activestorage-6.1.7.1/lib/active_storage/attached/one.rb:32:in `attach'
/enju/lib/tasks/attachment.rb:118:in `block in migrate_attachment'
/usr/local/bundle/gems/activerecord-6.1.7.1/lib/active_record/relation/batches.rb:71:in `block (2 levels) in find_each'
/usr/local/bundle/gems/activerecord-6.1.7.1/lib/active_record/relation/batches.rb:71:in `each'
/usr/local/bundle/gems/activerecord-6.1.7.1/lib/active_record/relation/batches.rb:71:in `block in find_each'
/usr/local/bundle/gems/activerecord-6.1.7.1/lib/active_record/relation/batches.rb:138:in `block in find_in_batches'
/usr/local/bundle/gems/activerecord-6.1.7.1/lib/active_record/relation/batches.rb:245:in `block in in_batches'
/usr/local/bundle/gems/activerecord-6.1.7.1/lib/active_record/relation/batches.rb:229:in `loop'
/usr/local/bundle/gems/activerecord-6.1.7.1/lib/active_record/relation/batches.rb:229:in `in_batches'
/usr/local/bundle/gems/activerecord-6.1.7.1/lib/active_record/relation/batches.rb:137:in `find_in_batches'
/usr/local/bundle/gems/activerecord-6.1.7.1/lib/active_record/relation/batches.rb:70:in `find_each'
/enju/lib/tasks/attachment.rb:117:in `migrate_attachment'
/enju/lib/tasks/enju_leaf_tasks.rake:85:in `block (2 levels) in <main>'
/usr/local/bundle/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
Tasks: TOP => enju_leaf:migrate_attachments
(See full trace by running task with --trace)
```

**Comment by masao** [comment]
立ち上げると:

```
[82c229a1-6931-47b6-a30f-ce6880727b7c] ActionView::Template::Error (wrong number of arguments (given 0, expected 1)):
[82c229a1-6931-47b6-a30f-ce6880727b7c]     2:   <div id="header_left">
[82c229a1-6931-47b6-a30f-ce6880727b7c]     3:     <div id="library_system_name">
[82c229a1-6931-47b6-a30f-ce6880727b7c]     4:       <h1 class="resource_title">
[82c229a1-6931-47b6-a30f-ce6880727b7c]     5:         <%= link_to image_tag(@library_group.header_logo.representation,
[82c229a1-6931-47b6-a30f-ce6880727b7c]     6:             style: 'margin-left: 20px; vertical-align: middle',
[82c229a1-6931-47b6-a30f-ce6880727b7c]     7:             alt: LibraryGroup.system_name(@locale),
[82c229a1-6931-47b6-a30f-ce6880727b7c]     8:             width: @library_group.header_logo.representation(resize_to_limit: [300, nil]).metadata['width'],
[82c229a1-6931-47b6-a30f-ce6880727b7c]
[82c229a1-6931-47b6-a30f-ce6880727b7c] app/views/page/_header.html.erb:5
[82c229a1-6931-47b6-a30f-ce6880727b7c] app/views/layouts/application.html.erb:22
```

**Comment by masao** [comment]
全体に治ったようなので、クローズします！
