### ISSUE TITLE
所蔵の新規作成時にエラー

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#497]
github 1.1ブランチの最先端でのエラーです。

所蔵の新規作成をしようと「登録する」ボタンを押したところ、Railsエラーで：

```
ActiveRecord::RecordNotFound in ItemsController#create
Couldn't find Manifestation without an ID
```

というエラーが出ます。
サーバ側のコンソールには、以下のエラーメッセージが出ています：
```
Unpermitted parameters: item_has_use_restriction_attributes
WARNING: Can't mass-assign protected attributes for Item: call_number, item_identifier, circulation_status_id, checkout_type_id, shelf_id, include_supplements, note, url, price, acquired_at, bookstore_id, budget_type_id, lock_version, manifestation_id, library_id, required_role_id, binding_item_identifier, binding_call_number, binded_at
```

**Comment by nabeta** [comment]
Gemfile に以下の行が入っている場合、削除して bundle update を実行した後、もう一度試してください。

```ruby
gem "protected_attributes"
```

**Comment by masao** [comment]
上記の行を削除後にbundle updateしてからサーバ起動すると以下のエラーがでます：
```
/home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `require': cannot load such file -- protected_attributes (LoadError)
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `block in require'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:232:in `load_dependency'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `require'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/enju_library-0.1.0.pre39/lib/enju_library/engine.rb:4:in `<top (required)>'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `require'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `block in require'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:232:in `load_dependency'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `require'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/enju_library-0.1.0.pre39/lib/enju_library.rb:1:in `<top (required)>'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `require'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `block in require'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:232:in `load_dependency'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `require'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/bundler/gems/enju_leaf-b1c46468d4c8/lib/enju_leaf/engine.rb:2:in `<top (required)>'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/bundler/gems/enju_leaf-b1c46468d4c8/lib/enju_leaf.rb:1:in `require'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/bundler/gems/enju_leaf-b1c46468d4c8/lib/enju_leaf.rb:1:in `<top (required)>'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/bundler-1.7.9/lib/bundler/runtime.rb:76:in `require'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/bundler-1.7.9/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/bundler-1.7.9/lib/bundler/runtime.rb:72:in `each'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/bundler-1.7.9/lib/bundler/runtime.rb:72:in `block in require'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/bundler-1.7.9/lib/bundler/runtime.rb:61:in `each'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/bundler-1.7.9/lib/bundler/runtime.rb:61:in `require'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/bundler-1.7.9/lib/bundler.rb:134:in `require'
        from /home/vagrant/enju/config/application.rb:7:in `<top (required)>'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:79:in `require'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:79:in `block in server'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:76:in `tap'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:76:in `server'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/railties-4.1.7/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

**Comment by nabeta** [comment]
その他のモジュールも、githubを参照するようになっていますか？ 以下の例を参考にしてください。
https://gist.github.com/nabeta/6319160

**Comment by masao** [comment]
enju_library, enju_seed, enju_manifestation_viewer がRiubygemsリリース版を見ていたようなので、その設定を追加したところ、以下のエラーに変わりました。

```
/home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activerecord-4.1.7/lib/active_record/dynamic_matchers.rb:26:in `method_missing': undefined method `attr_accessible' for User (call 'User.connection' to establish a connection):Class (NoMethodError)
        from /home/vagrant/enju/app/models/user.rb:10:in `<class:User>'
        from /home/vagrant/enju/app/models/user.rb:1:in `<top (required)>'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:443:in `load'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:443:in `block in load_file'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:633:in `new_constants_in'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:442:in `load_file'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:342:in `require_or_load'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:480:in `load_missing_constant'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:180:in `const_missing'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.1.7/lib/active_support/inflector/methods.rb:238:in `const_get'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.1.7/lib/active_support/inflector/methods.rb:238:in `block in constantize'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.1.7/lib/active_support/inflector/methods.rb:236:in `each'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.1.7/lib/active_support/inflector/methods.rb:236:in `inject'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.1.7/lib/active_support/inflector/methods.rb:236:in `constantize'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:552:in `get'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:583:in `constantize'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/devise-3.4.1/lib/devise.rb:302:in `get'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/devise-3.4.1/lib/devise/mapping.rb:80:in `to'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/devise-3.4.1/lib/devise/mapping.rb:75:in `modules'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/devise-3.4.1/lib/devise/mapping.rb:92:in `routes'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/devise-3.4.1/lib/devise/mapping.rb:159:in `default_used_route'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/devise-3.4.1/lib/devise/mapping.rb:69:in `initialize'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/devise-3.4.1/lib/devise.rb:336:in `new'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/devise-3.4.1/lib/devise.rb:336:in `add_mapping'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/devise-3.4.1/lib/devise/rails/routes.rb:224:in `block in devise_for'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/devise-3.4.1/lib/devise/rails/routes.rb:223:in `each'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/devise-3.4.1/lib/devise/rails/routes.rb:223:in `devise_for'
        from /home/vagrant/enju/config/routes.rb:2:in `block in <top (required)>'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/actionpack-4.1.7/lib/action_dispatch/routing/route_set.rb:337:in `instance_exec'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/actionpack-4.1.7/lib/action_dispatch/routing/route_set.rb:337:in `eval_block'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/actionpack-4.1.7/lib/action_dispatch/routing/route_set.rb:315:in `draw'
        from /home/vagrant/enju/config/routes.rb:1:in `<top (required)>'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:241:in `load'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:241:in `block in load'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:232:in `load_dependency'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:241:in `load'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/railties-4.1.7/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/railties-4.1.7/lib/rails/application/routes_reloader.rb:40:in `each'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/railties-4.1.7/lib/rails/application/routes_reloader.rb:40:in `load_paths'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/railties-4.1.7/lib/rails/application/routes_reloader.rb:16:in `reload!'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/railties-4.1.7/lib/rails/application/routes_reloader.rb:26:in `block in updater'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.1.7/lib/active_support/file_update_checker.rb:75:in `call'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.1.7/lib/active_support/file_update_checker.rb:75:in `execute'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/railties-4.1.7/lib/rails/application/routes_reloader.rb:27:in `updater'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/railties-4.1.7/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/railties-4.1.7/lib/rails/application/finisher.rb:71:in `block in <module:Finisher>'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/railties-4.1.7/lib/rails/initializable.rb:30:in `instance_exec'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/railties-4.1.7/lib/rails/initializable.rb:30:in `run'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/railties-4.1.7/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/2.2.0/tsort.rb:345:in `each'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/2.2.0/tsort.rb:345:in `call'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/railties-4.1.7/lib/rails/initializable.rb:54:in `run_initializers'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/railties-4.1.7/lib/rails/application.rb:300:in `initialize!'
        from /home/vagrant/enju/config/environment.rb:5:in `<top (required)>'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `require'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `block in require'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:232:in `load_dependency'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `require'
        from /home/vagrant/enju/config.ru:3:in `block in <main>'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
        from /home/vagrant/enju/config.ru:in `new'
        from /home/vagrant/enju/config.ru:in `<main>'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:49:in `eval'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:49:in `new_from_string'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:40:in `parse_file'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/server.rb:277:in `build_app_and_options_from_config'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/server.rb:199:in `app'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/railties-4.1.7/lib/rails/commands/server.rb:50:in `app'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/server.rb:314:in `wrapped_app'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/railties-4.1.7/lib/rails/commands/server.rb:130:in `log_to_stdout'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/railties-4.1.7/lib/rails/commands/server.rb:67:in `start'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:81:in `block in server'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:76:in `tap'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:76:in `server'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
        from /home/vagrant/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/railties-4.1.7/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

**Comment by nabeta** [comment]
app/models/user.rb に attr_accessible を含む行（おそらく以下のようになっているはずです）がありましたら、削除してください。

```ruby
attr_accessible :username
attr_accessible :email, :password, :password_confirmation, :remember_me
```

**Comment by masao** [comment]
以下の一行をコメントアウトしたら問題なく起動できるようになりました。
```ruby
  attr_accessible :username
```

**Comment by masao** [comment]
ひとまず、もともとのエラーであった、所蔵の新規作成ができるようになったことを確認したので、クローズします。
