### ISSUE TITLE
エクスポートしたファイルのAmazon S3へのリンクが正しくない

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#513]
Amazon S3を使用しているにもかかわらず、リンク先がローカルのURLになっている。

**Comment by nabeta** [comment]
改めてみたら、そもそもS3上にエクスポートするように作っていませんでしたね。

**Comment by yegusa** [comment]
開発中。

**Comment by yegusa** [comment]
コードとしては、書き終わったつもりなので、あとはテストが必要。 by @nabeta

**Comment by yegusa** [comment]
現在、
* @nabeta が、Amazon S3 のテスト環境を作成中
* @masao がAmazon S3 の設定の仕方のドキュメント作成中

**Comment by masao** [comment]
添付ファイルでテストしてみましたが NameError (uninitialized constant Paperclip::Storage::S3::AWS) が出ます。

```
2015-04-25T08:17:36.880879+00:00 app[web.1]:
2015-04-25T08:17:36.880881+00:00 app[web.1]: NameError (uninitialized constant Paperclip::Storage::S3::AWS):
2015-04-25T08:17:36.880883+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/paperclip-4.2.1/lib/paperclip/storage/s3.rb:301:in `rescue in exists?'
2015-04-25T08:17:36.880884+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/paperclip-4.2.1/lib/paperclip/storage/s3.rb:296:in `exists?'
2015-04-25T08:17:36.880889+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/paperclip-4.2.1/lib/paperclip/attachment.rb:557:in `block in queue_all_for_delete'
2015-04-25T08:17:36.880890+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/paperclip-4.2.1/lib/paperclip/attachment.rb:556:in `map'
2015-04-25T08:17:36.880891+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/paperclip-4.2.1/lib/paperclip/attachment.rb:556:in `queue_all_for_delete'
2015-04-25T08:17:36.880893+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/paperclip-4.2.1/lib/paperclip/attachment.rb:250:in `clear'
2015-04-25T08:17:36.880894+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/paperclip-4.2.1/lib/paperclip/attachment.rb:102:in `assign'
2015-04-25T08:17:36.880895+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/paperclip-4.2.1/lib/paperclip/has_attached_file.rb:66:in `block in define_setter'
2015-04-25T08:17:36.880896+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.0/lib/active_record/attribute_assignment.rb:54:in `public_send'
2015-04-25T08:17:36.880897+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.0/lib/active_record/attribute_assignment.rb:54:in `_assign_attribute'
2015-04-25T08:17:36.880899+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.0/lib/active_record/attribute_assignment.rb:41:in `block in assign_attributes'
2015-04-25T08:17:36.880900+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.0/lib/action_controller/metal/strong_parameters.rb:183:in `each_pair'
2015-04-25T08:17:36.880901+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.0/lib/action_controller/metal/strong_parameters.rb:183:in `each_pair'
2015-04-25T08:17:36.880902+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.0/lib/active_record/attribute_assignment.rb:35:in `assign_attributes'
2015-04-25T08:17:36.880903+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.0/lib/active_record/persistence.rb:249:in `block in update'
2015-04-25T08:17:36.880905+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.0/lib/active_record/transactions.rb:347:in `block in with_transaction_returning_status'
2015-04-25T08:17:36.880906+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
2015-04-25T08:17:36.880908+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
2015-04-25T08:17:36.804939+00:00 app[web.1]: Processing by ManifestationsController#update as HTML
2015-04-25T08:17:36.880909+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
2015-04-25T08:17:36.880910+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.0/lib/active_record/transactions.rb:220:in `transaction'
2015-04-25T08:17:36.880911+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.0/lib/active_record/transactions.rb:344:in `with_transaction_returning_status'
...
```

**Comment by masao** [comment]
paperclip側が thoughtbot/paperclip#1764 にあるようにaws-sdkパッケージの更新に未対応のために起きているようです。

**Comment by nabeta** [comment]
以下の行をGemfileに追加してください。

```ruby
gem 'aws-sdk', '~> 1.64'
```

**Comment by nabeta** [comment]
開発用サーバでS3を使用するようにしました。書誌のエクスポートの50番以降でS3を使用しています。リンク先がS3になっていることを確認してください。
http://dev.next-l.jp/resource_export_files

**Comment by yegusa** [comment]
開発サーバーで、以下、3つのエクスポート（利用者、書誌、催し物）を実行してみて、
amazon s3のリンク先になっていることを確認しました。
エクスポートについては、開発サーバーでamazon s3にできるようになっていることを
確認しましたので、クローズします。（添付ファイル等については、別issueを立てます）

http://dev.next-l.jp/user_export_files
![image](https://cloud.githubusercontent.com/assets/1328499/7488262/d64803b0-f402-11e4-82d5-502362fd270e.png)

http://dev.next-l.jp/resource_export_files
![image](https://cloud.githubusercontent.com/assets/1328499/7488272/ec624246-f402-11e4-96a6-adb3d85bdd50.png)

http://dev.next-l.jp/event_export_files
![image](https://cloud.githubusercontent.com/assets/1328499/7488280/0429f77a-f403-11e4-8d23-af2cb0d20e7f.png)
