### ISSUE TITLE
rc17への更新でエラー： uninitialized constant ApplicationController::Setting

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#552]
rc17リリース後にbundle updateしたあと起動すると、標記エラーにてRailsエラーとなります。

エラーメッセージは以下の通りです：
```
ActionController::RoutingError (uninitialized constant ApplicationController::Setting):
  app/controllers/application_controller.rb:11:in `block in <class:ApplicationController>'
  app/controllers/application_controller.rb:9:in `<class:ApplicationController>'
  app/controllers/application_controller.rb:1:in `<top (required)>'
```

環境は以下の通り：

```
$ bundle list
Gems included by the bundle:
  * actionmailer (4.1.8)
  * actionpack (4.1.8)
  * actionview (4.1.8)
  * activemodel (4.1.8)
  * activerecord (4.1.8)
  * activesupport (4.1.8)
  * acts_as_list (0.6.0)
  * addressable (2.3.7)
  * arel (5.0.1.20140414130214)
  * attribute_normalizer (1.2.0)
  * awesome_nested_set (3.0.2)
  * aws-sdk (2.0.28)
  * aws-sdk-core (2.0.28)
  * aws-sdk-resources (2.0.28)
  * bcrypt (3.1.10)
  * builder (3.2.2)
  * bundler (1.7.12)
  * cancancan (1.10.1)
  * charlock_holmes (0.7.3)
  * chronic (0.10.2)
  * climate_control (0.0.3)
  * cocaine (0.5.5)
  * coffee-rails (4.0.1)
  * coffee-script (2.3.0)
  * coffee-script-source (1.9.1)
  * dalli (2.7.2)
  * devise (3.4.1)
  * devise-encryptable (0.2.0)
  * dotenv (1.0.2)
  * dynamic_form (1.1.4)
  * enju_biblio (0.1.0.pre65 3c5a0af)
  * enju_circulation (0.1.0.pre42 af48377)
  * enju_event (0.1.17.pre25 8f4b852)
  * enju_flower (0.1.0.pre21)
  * enju_leaf (1.1.0.rc18 4439d65)
  * enju_library (0.1.0.pre40 630db7a)
  * enju_loc (0.1.0.pre4 00758d8)
  * enju_manifestation_viewer (0.1.0.pre17 9d2e8bf)
  * enju_message (0.1.14.pre22 b442766)
  * enju_ndl (0.1.0.pre35 75b7dc4)
  * enju_nii (0.1.0.pre12 130ef30)
  * enju_seed (0.1.1.pre13 dc220d2)
  * enju_subject (0.1.0.pre29 121cf9a)
  * erubis (2.7.0)
  * exception_notification (4.0.1)
  * exception_notification-rake (0.1.2)
  * execjs (2.3.0)
  * faraday (0.9.1)
  * foreigner (1.7.2)
  * foreman (0.77.0)
  * friendly_id (5.1.0)
  * geocoder (1.2.7)
  * highline (1.6.21)
  * hike (1.2.3)
  * i18n (0.7.0)
  * jbuilder (2.2.8)
  * jc-validates_timeliness (3.1.1)
  * jmespath (1.0.2)
  * jquery-rails (3.1.2)
  * jquery-ui-rails (4.2.1)
  * json (1.8.2)
  * kaminari (0.16.3)
  * library_stdnums (1.4.1)
  * lisbn (0.2.1)
  * mail (2.6.3)
  * marc (1.0.0)
  * mime-types (2.4.3)
  * mini_portile (0.6.2)
  * minitest (5.5.1)
  * mobylette (3.5)
  * mono_logger (1.1.0)
  * multi_json (1.10.1)
  * multi_xml (0.5.5)
  * multipart-post (2.0.0)
  * nested_form (0.3.2)
  * nokogiri (1.6.6.2)
  * nori (2.4.0)
  * options (2.3.2)
  * orm_adapter (0.5.0)
  * paper_trail (3.0.6)
  * paperclip (4.2.1)
  * paperclip-meta (1.1.0)
  * pg (0.18.1)
  * pr_geohash (1.0.0)
  * progress_bar (1.0.3)
  * rack (1.5.2)
  * rack-protection (1.5.3)
  * rack-test (0.6.3)
  * rails (4.1.8)
  * rails_autolink (1.1.6)
  * railties (4.1.8)
  * rake (10.4.2)
  * rdoc (4.2.0)
  * redcarpet (3.2.2)
  * redis (3.2.1)
  * redis-actionpack (4.0.0)
  * redis-activesupport (4.0.0)
  * redis-namespace (1.5.1)
  * redis-rack (1.5.0)
  * redis-rails (4.0.0)
  * redis-store (1.1.4)
  * responders (1.1.2)
  * resque (1.25.2)
  * resque-scheduler (4.0.0)
  * resque_mailer (2.2.7)
  * ri_cal (0.8.8)
  * rsolr (1.0.11)
  * rufus-scheduler (3.0.9)
  * sass (3.2.19)
  * sass-rails (4.0.5)
  * scrub_rb (1.0.1)
  * sdoc (0.4.1)
  * settingslogic (2.0.9)
  * simple_form (3.1.0)
  * sinatra (1.4.5)
  * sitemap_generator (5.0.5)
  * spring (1.3.3)
  * sprockets (2.12.3)
  * sprockets-rails (2.2.4)
  * sqlite3 (1.3.10)
  * statesman (1.1.0)
  * sunspot (2.1.1)
  * sunspot_rails (2.1.1)
  * sunspot_solr (2.1.1)
  * thor (0.19.1)
  * thread_safe (0.3.4)
  * tilt (1.4.1)
  * timeliness (0.3.7)
  * turbolinks (2.5.3)
  * tzinfo (1.2.2)
  * uglifier (2.7.0)
  * unf (0.1.4)
  * unf_ext (0.0.6)
  * vegas (0.1.11)
  * warden (1.2.3)
  * whenever (0.9.4)
```

**Comment by nabeta** [comment]
#516 の作業による不具合です。修正したので、現時点でもう一度bundle updateを試してください。
https://github.com/next-l/enju_leaf/commit/62645c9c541770bee5df1f3694c1fd328b5aafdd

**Comment by masao** [comment]
更新して確認しました。クローズします。
