### ISSUE TITLE
「検索」ボタンをクリックしたらWe're sorry となります

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#600]
rc18にあげて、以下を実行し、

1. Github最新に全てのモジュールを上げる。
2. https://github.com/next-l/enju_leaf/wiki/Update にある手順を実行する

  $ bundle update
  $ rake railties:install:migrations
  $ rake db:migrate RAILS_ENV=production
  $ rake enju_leaf:upgrade RAILS_ENV=production

「検索」ボタンをクリックしたらWe're sorry となります

<pre>
vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre65)
  * enju_circulation (0.1.0.pre43 528200b)
  * enju_event (0.1.17.pre24)
  * enju_flower (0.1.0.pre21 264a590)
  * enju_leaf (1.1.0.rc18 611cafa)
  * enju_library (0.1.0.pre40 4adbe7e)
  * enju_loc (0.1.0.pre4 52be501)
  * enju_manifestation_viewer (0.1.0.pre17)
  * enju_message (0.1.14.pre22)
  * enju_ndl (0.1.0.pre35 7b1388e)
  * enju_subject (0.1.0.pre29 1ab4640)

</pre>

/log/production.log の該当部分のエラー（上半分）です
<pre>
> I, [2015-04-25T08:15:02.173520 #2367]  INFO -- : Started GET "/manifestations?utf8=%E2%9C%93&query=&commit=%E6%A4%9C%E7%B4%A2" for 127.0.0.1 at 2015-04-25 08:15:02 +0000
> I, [2015-04-25T08:15:02.176243 #2367]  INFO -- : Processing by ManifestationsController#index as HTML
> I, [2015-04-25T08:15:02.176449 #2367]  INFO -- :   Parameters: {"utf8"=>"?", "query"=>"", "commit"=>"罎膣□}
> D, [2015-04-25T08:15:02.181216 #2367] DEBUG -- :   ESC[1mESC[36mUser Load (0.7ms)ESC[0m  ESC[1mSELECT  "users".* FROM "users" WHERE "users"."id" = ?  ORDER BY "users"."id" ASC LIMIT 1ESC[0m  [["id", 2]]
> D, [2015-04-25T08:15:02.193486 #2367] DEBUG -- :   ESC[1mESC[35mLibraryGroup Load (5.5ms)ESC[0m  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-04-25T08:15:02.194931 #2367] DEBUG -- : Cache read: available_languages
> D, [2015-04-25T08:15:02.196303 #2367] DEBUG -- : Cache fetch_hit: available_languages
> D, [2015-04-25T08:15:02.244431 #2367] DEBUG -- :   ESC[1mESC[36mRole Load (0.7ms)ESC[0m  ESC[1mSELECT  "roles".* FROM "roles" INNER JOIN "user_has_roles" ON "roles"."id" = "user_has_roles"."role_id" WHERE "user_has_roles"."user_id" = ?  ORDER BY roles.position LIMIT 1ESC[0m  [["user_id", 2]]
> D, [2015-04-25T08:15:02.246752 #2367] DEBUG -- :   ESC[1mESC[35mCACHE (0.1ms)ESC[0m  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-04-25T08:15:02.248494 #2367] DEBUG -- :   ESC[1mESC[36mCACHE (0.0ms)ESC[0m  ESC[1mSELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1ESC[0m  [["id", 1]]
> D, [2015-04-25T08:15:02.250301 #2367] DEBUG -- :   ESC[1mESC[35mCACHE (0.1ms)ESC[0m  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-04-25T08:15:02.252319 #2367] DEBUG -- :   ESC[1mESC[36mCACHE (0.0ms)ESC[0m  ESC[1mSELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1ESC[0m  [["id", 1]]
> D, [2015-04-25T08:15:02.254023 #2367] DEBUG -- :   ESC[1mESC[35mCACHE (0.0ms)ESC[0m  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-04-25T08:15:02.261119 #2367] DEBUG -- :   ESC[1mESC[36mCACHE (0.1ms)ESC[0m  ESC[1mSELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1ESC[0m  [["id", 1]]
> D, [2015-04-25T08:15:02.263894 #2367] DEBUG -- :   ESC[1mESC[35mCACHE (0.0ms)ESC[0m  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-04-25T08:15:02.265384 #2367] DEBUG -- :   ESC[1mESC[36mCACHE (0.1ms)ESC[0m  ESC[1mSELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1ESC[0m  [["id", 1]]
> D, [2015-04-25T08:15:02.286214 #2367] DEBUG -- : Cache read: library_all
> D, [2015-04-25T08:15:02.287592 #2367] DEBUG -- : Cache fetch_hit: library_all
> D, [2015-04-25T08:15:02.301987 #2367] DEBUG -- :   ESC[1mESC[32mSOLR Request (9.9ms)ESC[0m  [ path=ESC[1mESC[1mselectESC[0m parameters={fq: ESC[1mESC[1m["type:Manifestation"]ESC[0m, start: ESC[1mESC[1m0ESC[0m, rows: ESC[1mESC[1m30ESC[0m, q: ESC[1mESC[1m"*:*"ESC[0m} ]
> D, [2015-04-25T08:15:02.307576 #2367] DEBUG -- :   ESC[1mESC[35mSubject Load (0.9ms)ESC[0m  SELECT  "subjects".* FROM "subjects" WHERE "subjects"."term" IS NULL  ORDER BY "subjects"."id" ASC LIMIT 1
> D, [2015-04-25T08:15:02.326730 #2367] DEBUG -- :   ESC[1mESC[32mSOLR Request (16.2ms)ESC[0m  [ path=ESC[1mESC[1mselectESC[0m parameters={fq: ESC[1mESC[1m["type:Manifestation", "resource_master_b:true", "required_role_id_i:[* TO 4]"]ESC[0m, sort: ESC[1mESC[1m"created_at_d desc, created_at_d desc"ESC[0m, start: ESC[1mESC[1m0ESC[0m, rows: ESC[1mESC[1m30ESC[0m, facet: ESC[1mESC[1m"true"ESC[0m, f.reservable_b.facet.mincount: ESC[1mESC[1m1ESC[0m, facet.field: ESC[1mESC[1m["reservable_b"]ESC[0m, q: ESC[1mESC[1m"*:*"ESC[0m} ]
> D, [2015-04-25T08:15:02.347015 #2367] DEBUG -- :   ESC[1mESC[32mSOLR Request (16.1ms)ESC[0m  [ path=ESC[1mESC[1mselectESC[0m parameters={fq: ESC[1mESC[1m["type:Manifestation", "resource_master_b:true", "required_role_id_i:[* TO 4]"]ESC[0m, sort: ESC[1mESC[1m"created_at_d desc, created_at_d desc"ESC[0m, start: ESC[1mESC[1m0ESC[0m, rows: ESC[1mESC[1m500ESC[0m, facet: ESC[1mESC[1m"true"ESC[0m, f.reservable_b.facet.mincount: ESC[1mESC[1m1ESC[0m, facet.field: ESC[1mESC[1m["reservable_b"]ESC[0m, q: ESC[1mESC[1m"*:*"ESC[0m} ]

> D, [2015-04-25T08:15:02.579735 #2367] DEBUG -- :   ESC[1mESC[32mSOLR Request (227.6ms)ESC[0m  [ path=ESC[1mESC[1mselectESC[0m parameters={fq: ESC[1mESC[1m["type:Manifestation", "resource_master_b:true", "required_role_id_i:[* TO 4]"]ESC[0m, sort: ESC[1mESC[1m"created_at_d desc, created_at_d desc"ESC[0m, start: ESC[1mESC[1m0ESC[0m, rows: ESC[1mESC[1m10ESC[0m, facet: ESC[1mESC[1m"true"ESC[0m, f.reservable_b.facet.mincount: ESC[1mESC[1m1ESC[0m, facet.field: ESC[1mESC[1m["reservable_b", "carrier_type_s", "library_sm", "language_s", "subject_ids_im"]ESC[0m, f.carrier_type_s.facet.mincount: ESC[1mESC[1m1ESC[0m, f.library_sm.facet.mincount: ESC[1mESC[1m1ESC[0m, f.language_s.facet.mincount: ESC[1mESC[1m1ESC[0m, f.pub_year_i.facet.mincount: ESC[1mESC[1m1ESC[0m, facet.range: ESC[1mESC[1m["pub_year_i"]ESC[0m, f.pub_year_i.facet.range.start: ESC[1mESC[1m"0"ESC[0m, f.pub_year_i.facet.range.end: ESC[1mESC[1m"10000"ESC[0m, f.pub_year_i.facet.range.gap: ESC[1mESC[1m"10"ESC[0m, f.subject_ids_im.facet.mincount: ESC[1mESC[1m1ESC[0m, q: ESC[1mESC[1m"*:*"ESC[0m} ]
> D, [2015-04-25T08:15:02.587578 #2367] DEBUG -- :   ESC[1mESC[36mManifestation Load (0.9ms)ESC[0m  ESC[1mSELECT id, original_title, title_transcription, required_role_id, carrier_type_id, access_address, volume_number_string, issue_number_string, serial_number_string, date_of_publication, pub_date, language_id, created_at, updated_at, volume_number_string, volume_number, issue_number_string, issue_number, serial_number, edition_string, edition, serial, statement_of_responsibility FROM "manifestations" WHERE "manifestations"."id" IN (2, 1)ESC[0m
> D, [2015-04-25T08:15:02.597110 #2367] DEBUG -- :   ESC[1mESC[35mItem Load (0.9ms)ESC[0m  SELECT "items".* FROM "items" WHERE "items"."manifestation_id" IN (1, 2)
> D, [2015-04-25T08:15:02.603598 #2367] DEBUG -- :   ESC[1mESC[36mSeriesStatement Load (3.1ms)ESC[0m  ESC[1mSELECT "series_statements".* FROM "series_statements" WHERE "series_statements"."root_manifestation_id" IN (1, 2)ESC[0m
> I, [2015-04-25T08:15:02.612740 #2367]  INFO -- :   Rendered vendor/bundle/ruby/2.2.0/bundler/gems/enju_flower-264a5904aa1a/app/views/manifestations/_index_form.html.erb (2.4ms)
> D, [2015-04-25T08:15:02.622406 #2367] DEBUG -- :   ESC[1mESC[32mSOLR Request (8.3ms)ESC[0m  [ path=ESC[1mESC[1mselectESC[0m parameters={fq: ESC[1mESC[1m["type:Manifestation"]ESC[0m, start: ESC[1mESC[1m0ESC[0m, rows: ESC[1mESC[1m30ESC[0m, q: ESC[1mESC[1m"*:*"ESC[0m} ]
> I, [2015-04-25T08:15:02.631839 #2367]  INFO -- :   Rendered vendor/bundle/ruby/2.2.0/bundler/gems/enju_flower-264a5904aa1a/app/views/manifestations/index.html.erb within layouts/manifestations (23.1ms)
> I, [2015-04-25T08:15:02.632558 #2367]  INFO -- : Completed 500 Internal Server Error in 456ms
> F, [2015-04-25T08:15:02.644634 #2367] FATAL -- :
> ActionView::Template::Error (comparison of Fixnum with nil failed):
>     27:   <% end %>
>     28:
>     29:   <%- if @manifestations.total_count > 0 -%>
>     30:     <p>
>     31:       <%= t('page.number_of_search_results', count: @count[:query_result], numdocs: Manifestation.search.total, seconds: sprintf("%.3f", @seconds)) -%>
>     32:       <% if @count[:query_result] > @max_number_of_results %>
>     33:         <br />
>   vendor/bundle/ruby/2.2.0/bundler/gems/enju_flower-264a5904aa1a/app/views/manifestations/index.html.erb:30:in `>'
>   vendor/bundle/ruby/2.2.0/bundler/gems/enju_flower-264a5904aa1a/app/views/manifestations/index.html.erb:30:in `_vendor_bundle_ruby_______bundler_gems_enju_flower____a____aa_a_app_views_manifestations_index_html_erb___3756600788864406998_100950320'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.0/lib/action_view/template.rb:145:in `block in render'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/notifications.rb:166:in `instrument'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.0/lib/action_view/template.rb:333:in `instrument'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.0/lib/action_view/template.rb:143:in `render'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.0/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.0/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/notifications.rb:164:in `block in instrument'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/notifications.rb:164:in `instrument'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.0/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.0/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.0/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.0/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.0/lib/action_view/renderer/template_renderer.rb:14:in `render'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.0/lib/action_view/renderer/renderer.rb:42:in `render_template'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.0/lib/action_view/renderer/renderer.rb:23:in `render'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.0/lib/action_view/rendering.rb:100:in `_render_template'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_controller/metal/streaming.rb:217:in `_render_template'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.0/lib/action_view/rendering.rb:83:in `render_to_body'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/abstract_controller/rendering.rb:25:in `render'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_controller/metal/rendering.rb:16:in `render'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
>   /usr/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/core_ext/benchmark.rb:12:in `ms'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:41:in `block in render'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
>   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
>   vendor/bundle/ruby/2.2.0/gems/sunspot_rails-2.2.0/lib/sunspot/rails/railties/controller_runtime.rb:15:in `cleanup_view_runtime'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:40:in `render'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_controller/metal/mime_responds.rb:216:in `respond_to'
>   vendor/bundle/ruby/2.2.0/gems/enju_biblio-0.1.0.pre65/app/controllers/manifestations_controller.rb:317:in `index'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/abstract_controller/base.rb:198:in `process_action'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_controller/metal/rendering.rb:10:in `process_action'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:117:in `call'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:117:in `call'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:219:in `block in halting_and_conditional'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:219:in `call'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:219:in `block in halting_and_conditional'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:151:in `call'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:151:in `call'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:151:in `call'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:151:in `call'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
</pre>

**Comment by yegusa** [comment]
gem 'enju_biblio', github: "next-l/enju_biblio", branch: "1.1"

を　Gemfile に追加して、bundle update, sudo restart enju_leaf したら、解決しました。
クローズします。

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre66 7ff3adc)
  * enju_circulation (0.1.0.pre43 528200b)
  * enju_event (0.1.17.pre24)
  * enju_flower (0.1.0.pre21 264a590)
  * enju_leaf (1.1.0.rc18 611cafa)
  * enju_library (0.1.0.pre40 4adbe7e)
  * enju_loc (0.1.0.pre4 52be501)
  * enju_manifestation_viewer (0.1.0.pre17)
  * enju_message (0.1.14.pre22)
  * enju_ndl (0.1.0.pre35 7b1388e)
  * enju_subject (0.1.0.pre29 1ab4640)

**Comment by yegusa** [comment]
念のため、

$ rails c production
> library = LibraryGroup.first
> library.max_number_of_results = 200
> library.family_name_first = true
> library.save

もしたほうが安全とのこと by @nabeta 

（私は、↑をしなくても、起きなくなりましたが）

update スクリプトにいれるので、実際に打つ必要は今後はないかもです。
