### ISSUE TITLE
cronタスクの登録時にエラーが発生する

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#626]
インストールスクリプトで実行される、cronタスクを実行するためのコマンドが失敗する。

```
bundle exec whenever --update-crontab
```

エラーは以下のとおり。

```
==> default: /home/vagrant/enju/vendor/bundle/ruby/2.2.0/gems/whenever-0.9.4/lib/whenever/job_list.rb:25:in `instance_eval'
==> default: : 
==> default: config/schedule.rb:23: syntax error, unexpected ':'
==> default:  (
==> default: SyntaxError
==> default: )
==> default: 	from /home/vagrant/enju/vendor/bundle/ruby/2.2.0/gems/whenever-0.9.4/lib/whenever/job_list.rb:25:in `initialize'
==> default: 	from /home/vagrant/enju/vendor/bundle/ruby/2.2.0/gems/whenever-0.9.4/lib/whenever.rb:10:in `new'
==> default: 	from /home/vagrant/enju/vendor/bundle/ruby/2.2.0/gems/whenever-0.9.4/lib/whenever.rb:10:in `cron'
==> default: 	from /home/vagrant/enju/vendor/bundle/ruby/2.2.0/gems/whenever-0.9.4/lib/whenever/command_line.rb:54:in `whenever_cron'
==> default: 	from /home/vagrant/enju/vendor/bundle/ruby/2.2.0/gems/whenever-0.9.4/lib/whenever/command_line.rb:106:in `updated_crontab'
==> default: 	from /home/vagrant/enju/vendor/bundle/ruby/2.2.0/gems/whenever-0.9.4/lib/whenever/command_line.rb:35:in `run'
==> default: 	from /home/vagrant/enju/vendor/bundle/ruby/2.2.0/gems/whenever-0.9.4/lib/whenever/command_line.rb:6:in `execute'
==> default: 	from /home/vagrant/enju/vendor/bundle/ruby/2.2.0/gems/whenever-0.9.4/bin/whenever:41:in `<top (required)>'
==> default: 	from /home/vagrant/enju/vendor/bundle/ruby/2.2.0/bin/whenever:23:in `load'
==> default: 	from /home/vagrant/enju/vendor/bundle/ruby/2.2.0/bin/whenever:23:in `<main>'
```

**Comment by nabeta** [comment]
以下のコミットで修正。
https://github.com/next-l/enju_leaf/commit/269b3827ef5abf5f1028d47e668e706e1a669769

**Comment by nakamura-akifumi** [comment]
mac os x (Yosemite) で新規で環境を作成し、確認しました。
update 出来たのでクローズします。

```
nakamuraakifumi-no-MacBook-Air:your_enju_1.1rc19 nakamura$ bundle exec whenever --update-crontab
[write] crontab file updated

nakamuraakifumi-no-MacBook-Air:your_enju_1.1rc19 nakamura$ crontab -l
# Begin Whenever generated tasks for: /Users/nakamura/app/enju/your_enju_1.1rc19/config/schedule.rb
0,0 0 * * * /bin/bash -l -c 'cd /Users/nakamura/app/enju/your_enju_1.1rc19 && bin/rails runner -e production '\''User.lock_expired_users'\'' >> /Users/nakamura/app/enju/your_enju_1.1rc19/log/cron_log.log 2>&1'

0 3 * * * /bin/bash -l -c 'cd /Users/nakamura/app/enju/your_enju_1.1rc19 && RAILS_ENV=production bundle exec rake sunspot:reindex --silent >> /Users/nakamura/app/enju/your_enju_1.1rc19/log/cron_log.log 2>&1'

0 0 * * * /bin/bash -l -c 'cd /Users/nakamura/app/enju/your_enju_1.1rc19 && RAILS_ENV=production bundle exec rake enju_circulation:expire --silent >> /Users/nakamura/app/enju/your_enju_1.1rc19/log/cron_log.log 2>&1'

0 5 * * * /bin/bash -l -c 'cd /Users/nakamura/app/enju/your_enju_1.1rc19 && RAILS_ENV=production bundle exec rake enju_circulation:send_notification --silent >> /Users/nakamura/app/enju/your_enju_1.1rc19/log/cron_log.log 2>&1'

0 * * * * /bin/bash -l -c 'cd /Users/nakamura/app/enju/your_enju_1.1rc19 && RAILS_ENV=production bundle exec rake enju_biblio:import --silent >> /Users/nakamura/app/enju/your_enju_1.1rc19/log/cron_log.log 2>&1'

0,5,10,15,20,25,30,35,40,45,50,55 * * * * /bin/bash -l -c 'cd /Users/nakamura/app/enju/your_enju_1.1rc19 && RAILS_ENV=production bundle exec rake enju_message:send --silent >> /Users/nakamura/app/enju/your_enju_1.1rc19/log/cron_log.log 2>&1'

# End Whenever generated tasks for: /Users/nakamura/app/enju/your_enju_1.1rc19/config/schedule.rb
```

gem は以下の通り。

```
nakamuraakifumi-no-MacBook-Air:your_enju_1.1rc19 nakamura$ bundle show
Gems included by the bundle:
  * actionmailer (4.2.2)
  * actionpack (4.2.2)
  * actionview (4.2.2)
  * activejob (4.2.2)
  * activemodel (4.2.2)
  * activerecord (4.2.2)
  * activesupport (4.2.2)
  * acts_as_list (0.7.2)
  * addressable (2.3.8)
  * arel (6.0.0)
  * attribute_normalizer (1.2.0)
  * awesome_nested_set (3.0.2)
  * aws-sdk (2.1.1)
  * aws-sdk-core (2.1.1)
  * aws-sdk-resources (2.1.1)
  * bcrypt (3.1.10)
  * binding_of_caller (0.7.2)
  * builder (3.2.2)
  * bundler (1.10.4)
  * byebug (5.0.0)
  * cancancan (1.11.0)
  * charlock_holmes (0.7.3)
  * chronic (0.10.2)
  * climate_control (0.0.3)
  * cocaine (0.5.7)
  * coffee-rails (4.1.0)
  * coffee-script (2.4.1)
  * coffee-script-source (1.9.1.1)
  * columnize (0.9.0)
  * dalli (2.7.4)
  * debug_inspector (0.0.2)
  * devise (3.5.1)
  * devise-encryptable (0.2.0)
  * dotenv (2.0.2)
  * dotenv-rails (2.0.2)
  * dynamic_form (1.1.4)
  * enju_biblio (0.1.0.pre66 ea0ce8b)
  * enju_circulation (0.1.0.pre45 2498d45)
  * enju_event (0.1.17.pre25 89152a6)
  * enju_flower (0.1.0.pre22 2c7586c)
  * enju_leaf (1.1.0.rc19 f288772)
  * enju_library (0.1.0.pre41 ad0b692)
  * enju_manifestation_viewer (0.1.0.pre18 6a4f552)
  * enju_message (0.1.14.pre23 e980eef)
  * enju_ndl (0.1.0.pre36 eaf7ed7)
  * enju_subject (0.1.0.pre30 06a65c8)
  * erubis (2.7.0)
  * exception_notification (4.1.1)
  * exception_notification-rake (0.2.1)
  * execjs (2.5.2)
  * faraday (0.9.1)
  * foreman (0.78.0)
  * friendly_id (5.1.0)
  * geocoder (1.2.9)
  * globalid (0.3.5)
  * highline (1.6.21)
  * i18n (0.7.0)
  * jbuilder (2.3.0)
  * jc-validates_timeliness (3.1.1)
  * jmespath (1.0.2)
  * jquery-rails (4.0.4)
  * jquery-ui-rails (4.2.1)
  * json (1.8.3)
  * kaminari (0.16.3)
  * kramdown (1.7.0)
  * library_stdnums (1.4.1)
  * lisbn (0.2.1)
  * loofah (2.0.2)
  * mail (2.6.3)
  * marc (1.0.0)
  * mime-types (2.6.1)
  * mimemagic (0.3.0)
  * mini_portile (0.6.2)
  * minitest (5.7.0)
  * mobylette (3.5)
  * mono_logger (1.1.0)
  * multi_json (1.11.1)
  * multipart-post (2.0.0)
  * nested_form (0.3.2)
  * nokogiri (1.6.6.2)
  * non-stupid-digest-assets (1.0.4)
  * nori (2.6.0)
  * options (2.3.2)
  * orm_adapter (0.5.0)
  * paper_trail (3.0.8)
  * paperclip (4.3.0)
  * paperclip-meta (1.2.0)
  * pr_geohash (1.0.0)
  * progress_bar (1.0.3)
  * rack (1.6.4)
  * rack-protection (1.5.3)
  * rack-test (0.6.3)
  * rails (4.2.2)
  * rails-deprecated_sanitizer (1.0.3)
  * rails-dom-testing (1.0.6)
  * rails-html-sanitizer (1.0.2)
  * rails_autolink (1.1.6)
  * railties (4.2.2)
  * rake (10.4.2)
  * rdoc (4.2.0)
  * redis (3.2.1)
  * redis-actionpack (4.0.0)
  * redis-activesupport (4.0.0)
  * redis-namespace (1.5.2)
  * redis-rack (1.5.0)
  * redis-rails (4.0.0)
  * redis-store (1.1.5)
  * responders (2.1.0)
  * resque (1.25.2)
  * resque-scheduler (4.0.0)
  * resque_mailer (2.2.7)
  * ri_cal (0.8.8)
  * rsolr (1.0.12)
  * rufus-scheduler (3.1.3)
  * sass (3.4.14)
  * sass-rails (5.0.3)
  * scrub_rb (1.0.1)
  * sdoc (0.4.1)
  * simple_form (3.1.0)
  * sinatra (1.4.6)
  * sitemap_generator (5.0.5)
  * spring (1.3.6)
  * sprockets (3.2.0)
  * sprockets-rails (2.3.1)
  * sqlite3 (1.3.10)
  * statesman (1.2.5)
  * sunspot (2.2.0)
  * sunspot_rails (2.2.0)
  * sunspot_solr (2.2.0)
  * thor (0.19.1)
  * thread_safe (0.3.5)
  * tilt (1.4.1)
  * timeliness (0.3.7)
  * turbolinks (2.5.3)
  * tzinfo (1.2.2)
  * uglifier (2.7.1)
  * unf (0.1.4)
  * unf_ext (0.0.7.1)
  * vegas (0.1.11)
  * warden (1.2.3)
  * web-console (2.1.3)
  * whenever (0.9.4)
```
