### ISSUE TITLE
rc19 VMでのエラー

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#639]
昨日付けで作成された rc19 用 VM ですが、起動時に、

* puppet agent
* chef-client

の2つのデーモンを起動する際にいづれもエラーが出ているようです。

**Comment by masao** [comment]
起動スクリプトを実行した際に出ているとおぼしきエラーメッセージの例：

```
$ sudo /etc/init.d/puppet start
 * Starting puppet agent
/usr/lib/ruby/vendor_ruby/puppet/defaults.rb:343: warning: duplicated key at line 344 ignored: :queue_type
/usr/lib/ruby/vendor_ruby/safe_yaml/syck_node_monkeypatch.rb:42:in `<top (required)>': uninitialized constant Syck (NameError)
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/vendor_ruby/safe_yaml/load.rb:171:in `<module:SafeYAML>'
        from /usr/lib/ruby/vendor_ruby/safe_yaml/load.rb:25:in `<top (required)>'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/vendor_ruby/safe_yaml.rb:1:in `<top (required)>'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/vendor_ruby/puppet/vendor/require_vendored.rb:4:in `<top (required)>'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/vendor_ruby/puppet/vendor.rb:38:in `require_libs'
        from /usr/lib/ruby/vendor_ruby/puppet/vendor.rb:51:in `load_vendored'
        from /usr/lib/ruby/vendor_ruby/puppet.rb:164:in `<module:Puppet>'
        from /usr/lib/ruby/vendor_ruby/puppet.rb:29:in `<top (required)>'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/vendor_ruby/puppet/util/command_line.rb:12:in `<top (required)>'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/bin/puppet:3:in `<main>'
   ...fail!
```

```
$ sudo /etc/init.d/chef-client start
 * Starting chef-client  chef-client
/usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- ya
jl/yajl (LoadError)
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/vendor_ruby/yajl.rb:1:in `<top (required)>'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/vendor_ruby/chef/json_compat.rb:21:in `<top (required)>'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/vendor_ruby/chef/http/json_input.rb:20:in `<top (required)>'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/vendor_ruby/chef/rest.rb:32:in `<top (required)>'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/vendor_ruby/chef/search/query.rb:21:in `<top (required)>'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/vendor_ruby/chef/dsl/data_query.rb:19:in `<top (required)>'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/vendor_ruby/chef/mixin/language.rb:20:in `<top (required)>'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/vendor_ruby/chef/dsl/platform_introspection.rb:217:in `<top (required)>'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/vendor_ruby/chef/resource.rb:21:in `<top (required)>'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/vendor_ruby/chef/dsl/recipe.rb:20:in `<top (required)>'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/vendor_ruby/chef/provider.rb:22:in `<top (required)>'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/vendor_ruby/chef/provider/execute.rb:21:in `<top (required)>'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/vendor_ruby/chef/provider/script.rb:20:in `<top (required)>'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/vendor_ruby/chef/provider/windows_script.rb:19:in `<top (required)>'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/vendor_ruby/chef/provider/batch.rb:19:in `<top (required)>'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/vendor_ruby/chef/providers.rb:19:in `<top (required)>'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/vendor_ruby/chef.rb:25:in `<top (required)>'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/bin/chef-client:22:in `<main>'
   ...fail!
```

**Comment by nabeta** [comment]
puppetとchefは仮想マシンの作成元のVagrant boxに最初からインストールされているのですが、puppetがRuby 2.2をサポートしていないようです。
https://tickets.puppetlabs.com/browse/PUP-3796

Enjuではpuppetとchefは使用していないので、実害はないと思いますが、次回仮想マシンを作るときにはRuby 2.1に戻したほうがよいでしょうか。

**Comment by masao** [comment]
これらエラーになっているデーモンを、自動起動からはずしてはいかがでしょうか。

**Comment by nabeta** [comment]
1.1.0.rc20の仮想マシンで、chef-clientとpuppetの自動起動を解除しました。
http://www.next-l.jp/?page=VM

仮想マシン作成スクリプトの以下の部分になります。
https://gist.github.com/nabeta/87d3a07e1d88c0c563f4#file-enju_leaf_script_ubuntu-trusty-sh-L35-L37

**Comment by masao** [comment]
起動時にエラーが起きなくなったことを確認しました。クローズします。
