### ISSUE TITLE
所蔵情報の新規作成を試みた際の挙動に関する報告

### ISSUE THREAD

**Issue by harasugi** [next-l/enju_leaf#666]
本棚テーブルのレコードが「Library bookmark」のみ、かつ図書館テーブルのレコードが「web」のみの場合に所蔵情報の新規作成を試みるとエラー画面が表示されます。

本棚テーブルのレコードが「Library bookmark」のみ、かつ図書館テーブルのレコードが2つ以上の場合に所蔵情報の新規作成を試みると本棚テーブルに「図書館名_default」のレコードが追加されますが、この「図書館名_default」のレコードをすべて削除してもう一度所蔵情報の新規作成を試みると図書館の一覧画面に遷移します。

滅多に無いことですが、一応のご報告まで。

**Comment by yegusa** [comment]
デモサーバーで確認するのは大変なので、仮想マシンでやるほうがよさそうですね。
まずは、現象を確認しましょう。

**Comment by masao** [comment]
rc19のVMで現象が再現することを確認しました。 log/production.log に出ているエラーは以下の通りです：

```
NoMethodError (undefined method `shelves' for nil:NilClass):
  vendor/bundle/ruby/2.2.0/gems/enju_biblio-0.1.0.pre67/app/controllers/items_controller.rb:275:in `prepare_options'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:430:in `block in make_lambda'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:143:in `call'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:143:in `block in halting_and_conditional'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:502:in `call'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:502:in `block in call'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:502:in `each'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:502:in `call'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:88:in `run_callbacks'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/abstract_controller/callbacks.rb:19:in `process_action'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/rescue.rb:29:in `process_action'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `block in instrument'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `instrument'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/abstract_controller/base.rb:137:in `process'
  vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/rendering.rb:30:in `process'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal.rb:196:in `dispatch'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal.rb:237:in `block in action'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:76:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:45:in `serve'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:43:in `block in serve'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:30:in `each'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:30:in `serve'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:821:in `call'
  vendor/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
  vendor/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
  vendor/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
  vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
  vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:25:in `call'
  vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/flash.rb:260:in `call'
  vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
  vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/cookies.rb:560:in `call'
  vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/query_cache.rb:36:in `call'
  vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:84:in `run_callbacks'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/rack/logger.rb:38:in `call_app'
  vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:26:in `tagged'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:68:in `tagged'
  vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
  vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
  vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/engine.rb:518:in `call'
  vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/application.rb:165:in `call'
  vendor/bundle/ruby/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:580:in `process_client'
  vendor/bundle/ruby/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:674:in `worker_loop'
  vendor/bundle/ruby/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:529:in `spawn_missing_workers'
  vendor/bundle/ruby/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:140:in `start'
  vendor/bundle/ruby/2.2.0/gems/unicorn-4.9.0/bin/unicorn:126:in `<top (required)>'
  vendor/bundle/ruby/2.2.0/bin/unicorn:23:in `load'
  vendor/bundle/ruby/2.2.0/bin/unicorn:23:in `<main>'


```

**Comment by yegusa** [comment]
これは、改修が必要ってことだよね？よろしくです。 → @nabeta

**Comment by masao** [comment]
修正を加えました。
webを除く図書館が無い状態で所蔵を作ろうとした際にエラーにならないようにしました。図書館の一覧にリダイレクトさせますが、その際に本棚を作るように促すメッセージが表示されていなかったので、それも表示するようにしました：
![next l enju leaf](https://cloud.githubusercontent.com/assets/38825/9189673/dda16c8a-4026-11e5-8687-126c0c4a5adb.png)
ご確認いただければ幸いです。

**Comment by nabeta** [comment]
はい、よいように思います。開発サーバにも反映済みです。

**Comment by yegusa** [comment]
手元の仮想マシンで確認しました。確認できましたのでクローズします。

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre67 fd360cc)
  * enju_circulation (0.1.0.pre46)
  * enju_event (0.1.17.pre26)
  * enju_flower (0.1.0.pre22)
  * enju_leaf (1.1.0.rc20 b0fc359)
  * enju_library (0.1.0.pre42 42800a4)
  * enju_manifestation_viewer (0.1.0.pre18)
  * enju_message (0.1.14.pre24 cf4c00a)
  * enju_ndl (0.1.0.pre37)
  * enju_subject (0.1.0.pre32)

1. すっぴんのEnju を起動
2. 「本棚」を「Library bookmark」のみにする（他の「本棚」をすべて（といっても1件だけ）消す）
![image](https://cloud.githubusercontent.com/assets/1328499/9288773/ee7dd24e-4393-11e5-9d02-94321b0c75ed.png)

3. ユーザーenjuadminとsystemの所属している図書館を　web（Wolrd Wide Web）に変更する（利用者がいると図書館を削除できないため）
4. 図書館を web だけにする
![image](https://cloud.githubusercontent.com/assets/1328499/9288767/841f8bae-4393-11e5-9c8c-819e5a8076a5.png)

5. 書誌を1件適当に登録する
6. 所蔵の「新規作成」のリンクをクリックする
![image](https://cloud.githubusercontent.com/assets/1328499/9288796/0dbb127e-4395-11e5-8de6-b66a2e777f09.png)
7. すると、図書館の画面にリダイレクトされる
![image](https://cloud.githubusercontent.com/assets/1328499/9288802/4771b45a-4395-11e5-9664-17122ceb9e46.png)

**Comment by harasugi** [comment]
@yegusa様、@masao様、@nabeta様
運用上、滅多にないことであるにも関わらず対応頂きましてありがとうございました。
