### ISSUE TITLE
同じ分類記号の分類ができてしまう

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#758]
http://localhost:8080/classifications
![image](https://cloud.githubusercontent.com/assets/1328499/10088981/ede68386-6359-11e5-8a52-5e95245bd4d8.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 212222f)
  * enju_circulation (0.1.0.pre48 912c42d)
  * enju_event (0.1.17.pre26 924a638)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 4e93af0)
  * enju_library (0.1.0.pre44 bc70658)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_oai (0.1.0.pre19 3608817)
  * enju_subject (0.1.0.pre33 bf1ac84)

**Comment by masao** [comment]
件名にも同じ問題があります。。。 #694 #697 を参照。

**Comment by nabeta** [comment]
同一の分類の種類では、重複した分類記号は作成できないようにしました。開発サーバに反映済みです。
http://dev.next-l.jp/classifications

**Comment by yegusa** [comment]
bundle update して、分類をアクセスしたら、

http://localhost:8080/classifications
![image](https://cloud.githubusercontent.com/assets/1328499/10099672/db3c0888-63c6-11e5-9705-a93de4231428.png)

We're sorry ってなります。

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 e15ebb7)
  * enju_circulation (0.1.0.pre48 912c42d)
  * enju_event (0.1.17.pre26 924a638)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 cc91c8d)
  * enju_library (0.1.0.pre44 bc70658)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 e44b953)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 9c7a2b1)

以下は、そのログです

vagrant@vagrant-ubuntu-trusty-64:~/enju$ diff /tmp/logorg.txt /tmp/log2.txt
123621a123622,123774
> I, [2015-09-25T11:49:32.828352 #5552]  INFO -- : Started GET "/classifications" for 127.0.0.1 at 2015-09-25 11:49:32 +0000
> I, [2015-09-25T11:49:32.831049 #5552]  INFO -- : Processing by ClassificationsController#index as HTML
> D, [2015-09-25T11:49:32.836064 #5552] DEBUG -- :   User Load (0.9ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ?  ORDER BY "users"."id" ASC LIMIT 1  [["id", 2]]
> D, [2015-09-25T11:49:32.840480 #5552] DEBUG -- :   LibraryGroup Load (1.2ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-25T11:49:32.841685 #5552] DEBUG -- : Cache read: available_languages
> D, [2015-09-25T11:49:32.843146 #5552] DEBUG -- : Cache fetch_hit: available_languages
> D, [2015-09-25T11:49:32.870749 #5552] DEBUG -- :   Role Load (0.5ms)  SELECT  "roles".* FROM "roles" INNER JOIN "user_has_roles" ON "roles"."id" = "user_has_roles"."role_id" WHERE "user_has_roles"."user_id" = ? LIMIT 1  [["user_id", 2]]
> D, [2015-09-25T11:49:32.873822 #5552] DEBUG -- :   CACHE (0.1ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-25T11:49:32.875623 #5552] DEBUG -- :   CACHE (0.3ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-25T11:49:32.877534 #5552] DEBUG -- :   CACHE (0.2ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-25T11:49:32.879308 #5552] DEBUG -- :   CACHE (0.1ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-25T11:49:32.881496 #5552] DEBUG -- :   CACHE (0.1ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-25T11:49:32.890898 #5552] DEBUG -- :   CACHE (0.1ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-25T11:49:32.895407 #5552] DEBUG -- :   CACHE (0.1ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-25T11:49:32.897758 #5552] DEBUG -- :   CACHE (0.1ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-25T11:49:32.899579 #5552] DEBUG -- :   CACHE (0.1ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-25T11:49:32.923902 #5552] DEBUG -- :   CACHE (0.1ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-25T11:49:32.926543 #5552] DEBUG -- :   CACHE (0.1ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-25T11:49:32.930603 #5552] DEBUG -- :   CACHE (0.2ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-25T11:49:32.933599 #5552] DEBUG -- :   CACHE (0.1ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-25T11:49:32.935278 #5552] DEBUG -- :   CACHE (0.1ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-25T11:49:32.937204 #5552] DEBUG -- :   CACHE (0.2ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-25T11:49:32.963878 #5552] DEBUG -- :   CACHE (0.3ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-25T11:49:32.966051 #5552] DEBUG -- :   CACHE (0.1ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-25T11:49:32.968757 #5552] DEBUG -- :   CACHE (0.1ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-25T11:49:32.974185 #5552] DEBUG -- :   CACHE (0.1ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-25T11:49:32.979559 #5552] DEBUG -- :   CACHE (0.0ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-25T11:49:32.982110 #5552] DEBUG -- :   CACHE (0.1ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-25T11:49:33.054584 #5552] DEBUG -- :   SOLR Request (13.4ms)  [ path=select parameters={fq: ["type:Classification"], start: 0, rows: 10, q: "*:*"} ]
> D, [2015-09-25T11:49:33.065104 #5552] DEBUG -- :   Classification Load (3.8ms)  SELECT "classifications".* FROM "classifications" WHERE "classifications"."id" IN (3, 4, 2, 5, 6, 7, 8, 9, 10, 11)
> I, [2015-09-25T11:49:33.091659 #5552]  INFO -- :   Rendered vendor/bundle/ruby/2.2.0/bundler/gems/enju_subject-9c7a2b1838bd/app/views/classifications/index.html.erb within layouts/application (16.0ms)
> I, [2015-09-25T11:49:33.092998 #5552]  INFO -- : Completed 500 Internal Server Error in 261ms (ActiveRecord: 8.8ms)
> F, [2015-09-25T11:49:33.102723 #5552] FATAL -- :
> ActionView::Template::Error (undefined method `label' for #<Classification:0x000000093ca998>):
>     20:     <th></th>
>     21:   </tr>
>     22:
>     23: <%- @classifications.each do |classification| -%>
>     24:   <tr class="line<%= cycle("0", "1") -%>">
>     25:     <td><%= link_to classification.category, classification -%></td>
>     26:     <td><%= classification.label -%></td>
>   vendor/bundle/ruby/2.2.0/gems/activemodel-4.2.3/lib/active_model/attribute_methods.rb:433:in `method_missing'
>   vendor/bundle/ruby/2.2.0/bundler/gems/enju_subject-9c7a2b1838bd/app/views/classifications/index.html.erb:23:in `block in _vendor_bundle_ruby_______bundler_gems_enju_subject__c_a_b____bd_app_views_classifications_index_html_erb___1012177574574817068_79210060'
>   vendor/bundle/ruby/2.2.0/bundler/gems/enju_subject-9c7a2b1838bd/app/views/classifications/index.html.erb:20:in `each'
>   vendor/bundle/ruby/2.2.0/bundler/gems/enju_subject-9c7a2b1838bd/app/views/classifications/index.html.erb:20:in `_vendor_bundle_ruby_______bundler_gems_enju_subject__c_a_b____bd_app_views_classifications_index_html_erb___1012177574574817068_79210060'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/template.rb:145:in `block in render'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:166:in `instrument'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/template.rb:333:in `instrument'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/template.rb:143:in `render'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `block in instrument'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `instrument'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/template_renderer.rb:14:in `render'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/renderer.rb:42:in `render_template'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/renderer.rb:23:in `render'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/rendering.rb:100:in `_render_template'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/streaming.rb:217:in `_render_template'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/rendering.rb:83:in `render_to_body'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/abstract_controller/rendering.rb:25:in `render'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/rendering.rb:16:in `render'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
>   /usr/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/core_ext/benchmark.rb:12:in `ms'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
>   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
>   vendor/bundle/ruby/2.2.0/gems/sunspot_rails-2.2.0/lib/sunspot/rails/railties/controller_runtime.rb:15:in `cleanup_view_runtime'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:43:in `render'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/mime_responds.rb:215:in `respond_to'
>   vendor/bundle/ruby/2.2.0/bundler/gems/enju_subject-9c7a2b1838bd/app/controllers/classifications_controller.rb:34:in `index'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/abstract_controller/base.rb:198:in `process_action'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/rendering.rb:10:in `process_action'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115:in `call'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115:in `call'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:553:in `block (2 levels) in compile'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:88:in `run_callbacks'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/abstract_controller/callbacks.rb:19:in `process_action'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/rescue.rb:29:in `process_action'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `block in instrument'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `instrument'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
>   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/abstract_controller/base.rb:137:in `process'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/rendering.rb:30:in `process'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal.rb:196:in `dispatch'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal.rb:237:in `block in action'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:76:in `call'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:45:in `serve'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:43:in `block in serve'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:30:in `each'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:30:in `serve'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:821:in `call'
>   vendor/bundle/ruby/2.2.0/gems/fix_microsoft_links-0.1.4/lib/fix_microsoft_links.rb:18:in `call'
>   vendor/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
>   vendor/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
>   vendor/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
>   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
>   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:25:in `call'
>   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/flash.rb:260:in `call'
>   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
>   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/cookies.rb:560:in `call'
>   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/query_cache.rb:36:in `call'
>   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:84:in `run_callbacks'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
>   vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/rack/logger.rb:38:in `call_app'
>   vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/rack/logger.rb:20:in `block in call'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:68:in `block in tagged'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:26:in `tagged'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:68:in `tagged'
>   vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/rack/logger.rb:20:in `call'
>   vendor/bundle/ruby/2.2.0/gems/request_store-1.2.0/lib/request_store/middleware.rb:8:in `call'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/request_id.rb:21:in `call'
>   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
>   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
>   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
>   vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/engine.rb:518:in `call'
>   vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/application.rb:165:in `call'
>   vendor/bundle/ruby/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:580:in `process_client'
>   vendor/bundle/ruby/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:674:in `worker_loop'
>   vendor/bundle/ruby/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:529:in `spawn_missing_workers'
>   vendor/bundle/ruby/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:140:in `start'
>   vendor/bundle/ruby/2.2.0/gems/unicorn-4.9.0/bin/unicorn:126:in `<top (required)>'
>   vendor/bundle/ruby/2.2.0/bin/unicorn:23:in `load'
>   vendor/bundle/ruby/2.2.0/bin/unicorn:23:in `<main>'
>

**Comment by nabeta** [comment]
以下を実行してください。
https://github.com/next-l/enju_leaf/issues/743#issuecomment-143172312

**Comment by yegusa** [comment]
確認しましたので、クローズします。

一覧：　061 / UDC がある
![image](https://cloud.githubusercontent.com/assets/1328499/10101478/f692dea6-63d3-11e5-8037-3f61e46b86bb.png)

分類の新規作成で、 061 / UDC をつくろうとするが、エラーがでて、できないようになっている。
![image](https://cloud.githubusercontent.com/assets/1328499/10101497/1012a438-63d4-11e5-95a0-f43366e41545.png)

これに起因するバグをみつけましたが、それは別issue #769 にします。

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 e15ebb7)
  * enju_circulation (0.1.0.pre48 912c42d)
  * enju_event (0.1.17.pre26 924a638)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 eef0879)
  * enju_library (0.1.0.pre44 bc70658)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 0a65823)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 9c7a2b1)

**Comment by nabeta** [comment]
#769 の対応のため再オープンします。

**Comment by yegusa** [comment]
#769 の影響範囲が大きそうなので、こちらも1.1.0より後に回します。
