### ISSUE TITLE
rakeのエラー

### ISSUE THREAD

**Issue by adamasharpe** [next-l/enju_leaf#86]
OS X Lion，Ruby2.0.0p247, Rails3.2.15.
rake db:migrate をすると最後のYYYYMMDDxxxxxxx_add_devise_to_users.rbのファイルでエラーになります。

```
PG::DuplicateColumn: ERROR:  column "email" of relation "users" already exists
: ALTER TABLE "users" ADD COLUMN "email" character varying(255) DEFAULT '' NOT NULL/Users/UserName/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/activerecord-3.2.15/lib/active_record/connection_adapters/postgresql_adapter.rb:650:in `exec'
（中略）
/Users/UserName/Sites/enju_appname/db/migrate/201310DDxxxxxx_add_devise_to_users.rb:5:in `block in up'
（以下略）
```

rake db:reset
rake db:migrate:reset
しても変わりません。

https://github.com/nabeta/enju_leaf/tree/master/db/migrate
を見ても該当するファイルがなく、タイムスタンプも１つだけ新しいです。こちらの方で勝手に出来たのかもしれません。
ログでは
       force  config/initializers/devise.rb
   identical  config/locales/devise.en.yml
    generate  devise
      invoke  active_record
      create    db/migrate/201310DDXXXXXX_add_devise_to_users.rb
といった具合に  rails g enju_leaf:setup の中で出てきます。

中身は以下のとおりです。

```
class AddDeviseToUsers < ActiveRecord::Migration
  def self.up
    change_table(:users) do |t|
      ## Database authenticatable
      t.string :email,              :null => false, :default => ""
      t.string :encrypted_password, :null => false, :default => ""

      ## Recoverable
      t.string   :reset_password_token
      t.datetime :reset_password_sent_at

      ## Rememberable
      t.datetime :remember_created_at

      ## Trackable
      t.integer  :sign_in_count, :default => 0, :null => false
      t.datetime :current_sign_in_at
      t.datetime :last_sign_in_at
      t.string   :current_sign_in_ip
      t.string   :last_sign_in_ip

      ## Confirmable
      # t.string   :confirmation_token
      # t.datetime :confirmed_at
      # t.datetime :confirmation_sent_at
      # t.string   :unconfirmed_email # Only if using reconfirmable

      ## Lockable
      # t.integer  :failed_attempts, :default => 0, :null => false # Only if lock strategy is :failed_attempts
      # t.string   :unlock_token # Only if unlock strategy is :email or :both
      # t.datetime :locked_at


      # Uncomment below if timestamps were not included in your original model.
      # t.timestamps
    end

    add_index :users, :email,                :unique => true
    add_index :users, :reset_password_token, :unique => true
    # add_index :users, :confirmation_token,   :unique => true
    # add_index :users, :unlock_token,         :unique => true
  end

  def self.down
    # By default, we don't want to make any assumption about how to roll back a migration when your
    # model already existed. Please edit below which fields you would like to remove in this migration.
    raise ActiveRecord::IrreversibleMigration
  end
end

```

**Comment by nabeta** [comment]
すでに時間がたっていますのでcloseしますが、もし問題が続いているようでしたらreopenしてください。
