### ISSUE TITLE
Enju起動時にエラーが出る： exception_notification-rake

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#933]
1.1系のEnju起動時にエラーが出ます。

```
$ bundle exec foreman start
11:12:04 solr.1   | started with pid 4558
11:12:04 resque.1 | started with pid 4559
11:12:04 web.1    | started with pid 4560
11:12:10 web.1    | /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/exception_notification-rake-0.2.1/lib/exception_notifier/rake/rake_patch.rb:27:in `<top (required)>': undefined method `application' for Rake:Module (NoMethodError)
11:12:10 web.1    |     from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
11:12:10 web.1    |     from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
11:12:10 web.1    |     from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
11:12:10 web.1    |     from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
11:12:10 web.1    |     from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/exception_notification-rake-0.2.1/lib/exception_notifier/rake.rb:2:in `<top (required)>'
11:12:10 web.1    |     from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
11:12:10 web.1    |     from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
11:12:10 web.1    |     from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
11:12:10 web.1    |     from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
11:12:10 web.1    |     from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/exception_notification-rake-0.2.1/lib/exception_notification/rake.rb:3:in `<top (required)>'
11:12:10 web.1    |     from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:85:in `require'
11:12:10 web.1    |     from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:85:in `rescue in block in require'
11:12:10 web.1    |     from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:68:in `block in require'
11:12:10 web.1    |     from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'
11:12:10 web.1    |     from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `require'
11:12:10 web.1    |     from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler.rb:134:in `require'
11:12:10 web.1    |     from /home/vagrant/enju/config/application.rb:7:in `<top (required)>'
11:12:10 web.1    |     from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:78:in `require'
11:12:10 web.1    |     from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:78:in `block in server'
11:12:10 web.1    |     from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:75:in `tap'
11:12:10 web.1    |     from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:75:in `server'
11:12:10 web.1    |     from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
11:12:10 web.1    |     from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
11:12:10 web.1    |     from bin/rails:4:in `require'
11:12:10 web.1    |     from bin/rails:4:in `<main>'
11:12:10 web.1    | exited with code 1
11:12:10 system   | sending SIGTERM to all processes
11:12:10 resque.1 | terminated by SIGTERM
11:12:10 solr.1   | rake aborted!
11:12:10 solr.1   | SignalException: SIGTERM
11:12:10 solr.1   | /home/vagrant/enju/config/application.rb:7:in `<top (required)>'
11:12:10 solr.1   | /home/vagrant/enju/Rakefile:4:in `require'
11:12:10 solr.1   | /home/vagrant/enju/Rakefile:4:in `<top (required)>'
11:12:10 solr.1   | (See full trace by running task with --trace)
11:12:10 solr.1   | exited with code 1
```

**Comment by masao** [comment]
sunspot_solr 2.2.1以降での変更が原因の模様。一種 #923 からの派生。
sunspot_solrを Gemfile で 2.2.0 に固定すると、問題はでなくなり、通常通り、起動できるようになった。

**Comment by masao** [comment]
更新手順として文書化されたら、閉じることにします。

**Comment by masao** [comment]
https://github.com/next-l/enju_leaf/wiki/Update#updating-to-110--111 にて文書化されましたので、クローズします。
