### ISSUE TITLE
一般ユーザ権限で自分のユーザ情報にアクセスしたときにRailsエラー

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#947]
1.2系です。
エラーメッセージは以下の通り：
```
16:45:15 web.1    | ActionView::Template::Error (unable to find policy `UserPolicy` for `#<User id: 3, email: "", encrypted_password: "$2a$10$82MFEC1JZ0bpj0e0KNwqbObozI.2bA.ZAVgyAv.nRdf...", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2015-12-06 07:44:56", last_sign_in_at: "2015-12-06 07:44:56", current_sign_in_ip: "10.0.2.2", last_sign_in_ip: "10.0.2.2", created_at: "2015-12-06 07:44:36", updated_at: "2015-12-06 07:44:56", username: "test", deleted_at: nil, expired_at: nil, failed_attempts: 0, unlock_token: nil, locked_at: nil, confirmed_at: nil>`):
16:45:15 web.1    |     22:   <% end %>
16:45:15 web.1    |     23:   <ul>
16:45:15 web.1    |     24:     <li><%= link_to t('page.edit'), edit_my_account_path -%></li>
16:45:15 web.1    |     25:     <li><%= link_to t('activerecord.models.registration'), edit_user_registration_path -%></li>
16:45:15 web.1    |     26:     <%- if policy(current_user).destroy? -%>
16:45:15 web.1    |     27:       <li><%= link_to t('page.destroy'), curent_user, data: {confirm: t('page.are_you_sure')}, method: :delete -%></li>
16:45:15 web.1    |     28:     <%- end -%>
16:45:15 web.1    |   pundit (1.0.1) lib/pundit/policy_finder.rb:30:in `policy!'
16:45:15 web.1    |   pundit (1.0.1) lib/pundit.rb:62:in `policy!'
16:45:15 web.1    |   pundit (1.0.1) lib/pundit.rb:137:in `policy'
16:45:15 web.1    |   actionpack (4.2.5) lib/abstract_controller/helpers.rb:67:in `policy'
16:45:15 web.1    |   /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/enju_leaf-882fa1999b6c/app/views/my_accounts/show.html.erb:25:in `__home_vagrant__rbenv_versions_______lib_ruby_gems_______bundler_gems_enju_leaf____fa____b_c_app_views_my_accounts_show_html_erb__1332028356381003772_70283133484700'
16:45:15 web.1    |   actionview (4.2.5) lib/action_view/template.rb:145:in `block in render'
16:45:15 web.1    |   activesupport (4.2.5) lib/active_support/notifications.rb:166:in `instrument'
16:45:15 web.1    |   actionview (4.2.5) lib/action_view/template.rb:333:in `instrument'
16:45:15 web.1    |   actionview (4.2.5) lib/action_view/template.rb:143:in `render'
16:45:15 web.1    |   actionview (4.2.5) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
16:45:15 web.1    |   actionview (4.2.5) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
16:45:15 web.1    |   activesupport (4.2.5) lib/active_support/notifications.rb:164:in `block in instrument'
16:45:15 web.1    |   activesupport (4.2.5) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
16:45:15 web.1    |   activesupport (4.2.5) lib/active_support/notifications.rb:164:in `instrument'
16:45:15 web.1    |   actionview (4.2.5) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
16:45:15 web.1    |   actionview (4.2.5) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
16:45:15 web.1    |   actionview (4.2.5) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
16:45:15 web.1    |   actionview (4.2.5) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
16:45:15 web.1    |   actionview (4.2.5) lib/action_view/renderer/template_renderer.rb:14:in `render'
16:45:15 web.1    |   actionview (4.2.5) lib/action_view/renderer/renderer.rb:42:in `render_template'
16:45:15 web.1    |   actionview (4.2.5) lib/action_view/renderer/renderer.rb:23:in `render'
16:45:15 web.1    |   actionview (4.2.5) lib/action_view/rendering.rb:100:in `_render_template'
16:45:15 web.1    |   actionpack (4.2.5) lib/action_controller/metal/streaming.rb:217:in `_render_template'
16:45:15 web.1    |   actionview (4.2.5) lib/action_view/rendering.rb:83:in `render_to_body'
16:45:15 web.1    |   actionpack (4.2.5) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
16:45:15 web.1    |   actionpack (4.2.5) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
16:45:15 web.1    |   actionpack (4.2.5) lib/abstract_controller/rendering.rb:25:in `render'
16:45:15 web.1    |   actionpack (4.2.5) lib/action_controller/metal/rendering.rb:16:in `render'
16:45:15 web.1    |   actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
16:45:15 web.1    |   activesupport (4.2.5) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
16:45:15 web.1    |   /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
16:45:15 web.1    |   activesupport (4.2.5) lib/active_support/core_ext/benchmark.rb:12:in `ms'
16:45:15 web.1    |   actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
16:45:15 web.1    |   actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
16:45:15 web.1    |   activerecord (4.2.5) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
16:45:15 web.1    |   sunspot_rails (2.2.2) lib/sunspot/rails/railties/controller_runtime.rb:15:in `cleanup_view_runtime'
16:45:15 web.1    |   actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:43:in `render'
16:45:15 web.1    |   actionpack (4.2.5) lib/action_controller/metal/mime_responds.rb:217:in `respond_to'
16:45:15 web.1    |   /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/enju_leaf-882fa1999b6c/app/controllers/my_accounts_controller.rb:6:in `show'
16:45:15 web.1    |   actionpack (4.2.5) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
16:45:15 web.1    |   actionpack (4.2.5) lib/abstract_controller/base.rb:198:in `process_action'
16:45:15 web.1    |   actionpack (4.2.5) lib/action_controller/metal/rendering.rb:10:in `process_action'
16:45:15 web.1    |   actionpack (4.2.5) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
16:45:15 web.1    |   activesupport (4.2.5) lib/active_support/callbacks.rb:117:in `call'
16:45:15 web.1    |   activesupport (4.2.5) lib/active_support/callbacks.rb:117:in `call'
16:45:15 web.1    |   activesupport (4.2.5) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
16:45:15 web.1    |   activesupport (4.2.5) lib/active_support/callbacks.rb:505:in `call'
16:45:15 web.1    |   activesupport (4.2.5) lib/active_support/callbacks.rb:505:in `call'
16:45:15 web.1    |   activesupport (4.2.5) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
16:45:15 web.1    |   activesupport (4.2.5) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
16:45:15 web.1    |   activesupport (4.2.5) lib/active_support/callbacks.rb:81:in `run_callbacks'
16:45:15 web.1    |   actionpack (4.2.5) lib/abstract_controller/callbacks.rb:19:in `process_action'
16:45:15 web.1    |   actionpack (4.2.5) lib/action_controller/metal/rescue.rb:29:in `process_action'
16:45:15 web.1    |   actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
16:45:15 web.1    |   activesupport (4.2.5) lib/active_support/notifications.rb:164:in `block in instrument'
16:45:15 web.1    |   activesupport (4.2.5) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
16:45:15 web.1    |   activesupport (4.2.5) lib/active_support/notifications.rb:164:in `instrument'
16:45:15 web.1    |   actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
16:45:15 web.1    |   actionpack (4.2.5) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
16:45:15 web.1    |   activerecord (4.2.5) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
16:45:15 web.1    |   actionpack (4.2.5) lib/abstract_controller/base.rb:137:in `process'
16:45:15 web.1    |   actionview (4.2.5) lib/action_view/rendering.rb:30:in `process'
16:45:15 web.1    |   actionpack (4.2.5) lib/action_controller/metal.rb:196:in `dispatch'
16:45:15 web.1    |   actionpack (4.2.5) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
16:45:15 web.1    |   actionpack (4.2.5) lib/action_controller/metal.rb:237:in `block in action'
16:45:15 web.1    |   actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:76:in `call'
16:45:15 web.1    |   actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
16:45:15 web.1    |   actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:45:in `serve'
16:45:15 web.1    |   actionpack (4.2.5) lib/action_dispatch/journey/router.rb:43:in `block in serve'
16:45:15 web.1    |   actionpack (4.2.5) lib/action_dispatch/journey/router.rb:30:in `each'
16:45:15 web.1    |   actionpack (4.2.5) lib/action_dispatch/journey/router.rb:30:in `serve'
16:45:15 web.1    |   actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:817:in `call'
16:45:15 web.1    |   fix_microsoft_links (0.1.4) lib/fix_microsoft_links.rb:18:in `call'
16:45:15 web.1    |   warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
16:45:15 web.1    |   warden (1.2.3) lib/warden/manager.rb:34:in `catch'
16:45:15 web.1    |   warden (1.2.3) lib/warden/manager.rb:34:in `call'
16:45:15 web.1    |   rack (1.6.4) lib/rack/etag.rb:24:in `call'
16:45:15 web.1    |   rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
16:45:15 web.1    |   rack (1.6.4) lib/rack/head.rb:13:in `call'
16:45:15 web.1    |   actionpack (4.2.5) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
16:45:15 web.1    |   actionpack (4.2.5) lib/action_dispatch/middleware/flash.rb:260:in `call'
16:45:15 web.1    |   rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
16:45:15 web.1    |   rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
16:45:15 web.1    |   actionpack (4.2.5) lib/action_dispatch/middleware/cookies.rb:560:in `call'
16:45:15 web.1    |   activerecord (4.2.5) lib/active_record/query_cache.rb:36:in `call'
16:45:15 web.1    |   activerecord (4.2.5) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
16:45:15 web.1    |   activerecord (4.2.5) lib/active_record/migration.rb:377:in `call'
16:45:15 web.1    |   actionpack (4.2.5) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
16:45:15 web.1    |   activesupport (4.2.5) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
16:45:15 web.1    |   activesupport (4.2.5) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
16:45:15 web.1    |   activesupport (4.2.5) lib/active_support/callbacks.rb:81:in `run_callbacks'
16:45:15 web.1    |   actionpack (4.2.5) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
16:45:15 web.1    |   actionpack (4.2.5) lib/action_dispatch/middleware/reloader.rb:73:in `call'
16:45:15 web.1    |   actionpack (4.2.5) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
16:45:15 web.1    |   actionpack (4.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
16:45:15 web.1    |   web-console (2.2.1) lib/web_console/middleware.rb:31:in `call'
16:45:15 web.1    |   actionpack (4.2.5) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
16:45:15 web.1    |   railties (4.2.5) lib/rails/rack/logger.rb:38:in `call_app'
16:45:15 web.1    |   railties (4.2.5) lib/rails/rack/logger.rb:20:in `block in call'
16:45:15 web.1    |   activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `block in tagged'
16:45:15 web.1    |   activesupport (4.2.5) lib/active_support/tagged_logging.rb:26:in `tagged'
16:45:15 web.1    |   activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `tagged'
16:45:15 web.1    |   railties (4.2.5) lib/rails/rack/logger.rb:20:in `call'
16:45:15 web.1    |   request_store (1.2.1) lib/request_store/middleware.rb:8:in `call'
16:45:15 web.1    |   actionpack (4.2.5) lib/action_dispatch/middleware/request_id.rb:21:in `call'
16:45:15 web.1    |   rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
16:45:15 web.1    |   rack (1.6.4) lib/rack/runtime.rb:18:in `call'
16:45:15 web.1    |   activesupport (4.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
16:45:15 web.1    |   rack (1.6.4) lib/rack/lock.rb:17:in `call'
16:45:15 web.1    |   actionpack (4.2.5) lib/action_dispatch/middleware/static.rb:116:in `call'
16:45:15 web.1    |   rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
16:45:15 web.1    |   railties (4.2.5) lib/rails/engine.rb:518:in `call'
16:45:15 web.1    |   railties (4.2.5) lib/rails/application.rb:165:in `call'
16:45:15 web.1    |   rack (1.6.4) lib/rack/lock.rb:17:in `call'
16:45:15 web.1    |   rack (1.6.4) lib/rack/content_length.rb:15:in `call'
16:45:15 web.1    |   rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
16:45:15 web.1    |   /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
16:45:15 web.1    |   /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
16:45:15 web.1    |   /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

**Comment by nabeta** [comment]
開発サーバで修正済みです。

**Comment by masao** [comment]
修正を確認したのでクローズします。
